### ISSUE TITLE
GooglePlayServicesNative & GooglePlayServicesAdRenderer missing from 'com.mopub.mediation:admob:17.0.0.2'

### ISSUE THREAD

**Issue by joeykrim** [mopub/mopub-android-mediation#103]
com.mopub.nativeads.GooglePlayServicesNative & com.mopub.nativeads.GooglePlayServicesAdRenderer are missing from 'com.mopub.mediation:admob:17.0.0.2'

Both GooglePlayServicesNative & GooglePlayServicesAdRenderer are present in 17.0.0.0 and 17.0.0.1 but not in 17.0.0.2

As a workaround - Manually adding https://github.com/mopub/mopub-android-mediation/blob/master/AdMob/com/mopub/nativeads/GooglePlayServicesAdRenderer.java
and https://github.com/mopub/mopub-android-mediation/blob/master/AdMob/com/mopub/nativeads/GooglePlayServicesNative.java resolves the missing files

**Comment by chauduyphanvu1** [comment]
@joeykrim, thanks for flagging this! The issue should now be resolved. Check back and let us know if you continue to see it.
