### ISSUE TITLE
FlurryCustomEventBanner was misplaced

### ISSUE THREAD

**Issue by mk-jones** [mopub/mopub-android-mediation#109]
The FlurryCustomEventBanner is missing after the move from the previous repo.

**Comment by chauduyphanvu1** [comment]
@mk-jones, Flurry has dropped support for banner for MoPub mediation, so we dropped the banner adapter from the repository. For more info on which ad format is supported for which ad network, check out our network pages [here](https://developers.mopub.com/docs/mediation/networks/yahooflurry/).

Vu Chau
MoPub SDK Team
