### ISSUE TITLE
AdMob rewarded videos lose listeners in concurrent ad requests

### ISSUE THREAD

**Issue by duanrui71** [mopub/mopub-android-mediation#124]
loadWithSdkInitialized  函数中。当出现视频重复加载时，将直接进行onRewardedVideoLoadSuccess操作，但是并没有将状态isAdLoaded 重置为 true. 导致内部状态不一致，进而导致hasVideoAvailable 会永远返回false.

**Comment by chauduyphanvu1** [comment]
@duanrui71 - thanks for letting us know about that! Could you fill in [this template](https://github.com/mopub/mopub-android-mediation/blob/master/ISSUE_TEMPLATE.md) to let us know the exact behavior you are seeing as well as the steps to reproduce the issue?

Vu Chau
MoPub SDK Team

**Comment by duanrui71** [comment]
1. **What is the issue?**
    > Rewarded Video 不支持多广告位。

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Rewarded Video
    * **Platform** (*Android, iOS, Unity*)
        > Android
    * **MoPub SDK Version**
        > com.mopub:mopub-sdk:5.4.1@aar
    * **Mediation SDK Name & Version**
        > com.google.android.gms:play-services-ads:17.1.2
    * **Mediation Adapter Version**
        > com.mopub.mediation:admob:17.1.2.2
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Provide the data here
    * **Device model and OS Version**
        > Provide the data here
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. 准备好两个Rewarded Video,只选择聚合Admob
        > 2. 加载(load)第一个Rewarded Video.
        > 3. 加载(load)第二个Rewarded Video..
        > 4. 展示第一个 Rewarded Video .
        > 5. 展示第二个 Rewarded Video .
    * **Observed behavior**
        > 第二个Rewarded Video 将无法展示
    * **Expected behavior** (if known)
        > Provide the data here
    * **Evidence** (if available)
        > . Admob的Rewarded Video广告位是一个单件(singleton).但是在com/mopub/mobileads/GooglePlayServicesRewardedVideo.java:174处的
mRewardedVideoAd.setRewardedVideoAdListener(GooglePlayServicesRewardedVideo.this);

此代码可能会被多次调用，但是只有最后一次调用的Listener有效。

**Comment by chauduyphanvu1** [comment]
@duanrui71 - thanks for the information. The issue is reproducible when AdMob rewarded videos are requested concurrently. We'll investigate that use case and see what can be done. Thanks!

**Comment by chauduyphanvu1** [comment]
@duanrui71 - we synced with Google on this use case, and were informed that the AdMob Mobile Ads SDK does not support concurrent rewarded video ad requests. Publishers are advised to request ads sequentially in this case. Let us know if you have any questions!
