### ISSUE TITLE
Facebook Audience Network mediation error

### ISSUE THREAD

**Issue by bmueller** [mopub/mopub-android-mediation#16]
I'm trying to incorporate Facebook ads into my Android app, but am getting an error in my logs when MoPub tries to load the ads:

D/MoPub: Attempting to invoke custom event: FacebookBanner
D/MoPub: Couldn't locate or instantiate custom event: FacebookBanner.
V/MoPub: MoPubErrorCode: Unable to find Native Network or Custom Event adapter.

I have FAN mediation added to my manifest file:

compile 'com.facebook.android:audience-network-sdk:4.28.0'
compile 'com.mopub.mediation:facebookaudiencenetwork:4.28.0.0'

And in MoPub's dashboard, I have the Custom Event Classes for Facebook entered as "FacebookBanner" and "FacebookInterstitial". 

I'm assuming based on the logs that I have the name of the custom event class wrong. Any idea how to fix this?

**Comment by rsatrasala** [comment]
Hello @bmueller, you seem to be using iOS MoPub adunits in your Android app. Ensure you use the right adunits to resolve this issue.

**Comment by bmueller** [comment]
Yes, that was the issue - I had set up Facebook Audience Network in MoPub a year and a half ago for an iOS app, and was just using that for the Android app. Didn't realize that I could now add Facebook directly without a custom event class. Thanks for the quick reply!
