### ISSUE TITLE
Unable to change AdMob GDPR consent after SDK init

### ISSUE THREAD

**Issue by giccisw** [mopub/mopub-android-mediation#169]
1. **What is the issue?**
    > Not possible to change NPA after SDK init.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [X] I searched https://developers.mopub.com/ and found no answer.
    - [X] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [X] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > All
    * **Platform** (*Android, iOS, Unity*)
        > Android
    * **MoPub SDK Version**
        > 5.7.1
    * **Mediation SDK Name & Version**
        > com.google.android.gms:play-services-ads:17.2.1
    * **Mediation Adapter Version**
        > com.mopub.mediation:admob:17.2.1.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > -
    * **Device model and OS Version**
        > All Android
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Initialize the SDK without GDPR consent
        > 2. User provides GDPR consent
    * **Observed behavior**
        > New consent applies after app restart, also in case the user revoked the GDPR consent!
    * **Expected behavior** (if known)
        > There should be a way to change the GDPR consent after initialization
    * **Evidence** (if available)
        > -

**Comment by giccisw** [comment]
In previous versions this was possible by accessing GooglePlayServicesMediationSettings class. Was a bit ugly but it was working. Now the equivalent GooglePlayServicesAdapterConfiguration has setNpaBundle private and only during SDK initialization it can be populated.
There are use cases in which the user could change his/her consent and we shall be allowed to apply it without restarting the app.

**Comment by chauduyphanvu1** [comment]
@giccisw, thanks for letting us know your use case. We'll check what we can do here to support it, and I'll post an update once there's a decision.

Vu Chau
MoPub SDK Team

**Comment by giccisw** [comment]
Any update on this?

**Comment by chauduyphanvu** [comment]
@giccisw, we have some planned work touching this code so we're waiting for that to be done first. Once that's over, I'll scope out the work necessary to support this feature. I will post an update!

**Comment by chauduyphanvu** [comment]
@giccisw, I've added support for this in https://github.com/mopub/mopub-android-mediation/commit/4e76005b45ca6090998e0309c18dfc705eb963aa (v18.2.0.4 of the Google adapters). 

You can pass in the npa String (`0` or `1`) at any time by calling `GooglePlayServicesAdapterConfiguration.setNpaBundle("NPA_STRING")`. Let us know if you need anything else!

**Comment by giccisw** [comment]
@chauduyphanvu, thank you for the changes.

They almost match my requirements, but I have the following comment: the AdMob documentation does not state that "npa" could be set to "0" or "1", but just that it could be not set or set to "1". Most probably "0" and not set are equivalent, but I would prefer to stick to the docs to be on the safe side.

To allow clearing the `npaBundle` the `setNpaBundle()` method should be something like:

```
    public static void setNpaBundle(String npaValue) {
        npaBundle = new Bundle();
        if (!TextUtils.isEmpty((npaValue)))
            npaBundle.putString(KEY_NPA, npaValue);
    }
```
Thank you.

**Comment by chauduyphanvu** [comment]
@giccisw, this is done in https://github.com/mopub/mopub-android-mediation/commit/a61be11428618f8867886607c40907d20ed2abe0. Let us know if you need anything else!

**Comment by giccisw** [comment]
Perfect, thanks.
