### ISSUE TITLE
about  path of "MoPub SDK"

### ISSUE THREAD

**Issue by GITHUB243884919** [mopub/mopub-android-mediation#170]
1. **What is the issue?**
    > mopub-android not found
     in  the settings.gradle
def mopubSdkDir = file('mopub-android').exists() &&
                  file(".gitmodules").text.contains('[submodule "mopub-android"]') ?
        'mopub-android' : 'mopub-android-sdk'

and in the  .gitmodules
[submodule "mopub-android"]
	path = mopub-android
	url = https://github.com/mopub/mopub-android.git
[submodule "mopub-android-sdk"]
	path = mopub-android-sdk
	url = https://github.com/mopub/mopub-android-sdk.git 

but there is not https://github.com/mopub/mopub-android.git

so I think   modify the file settings.gradle
// MoPub SDK
//def mopubSdkDir = file('mopub-android').exists() &&
//                  file(".gitmodules").text.contains('[submodule "mopub-android"]') ?
//        'mopub-android' : 'mopub-android-sdk'
def mopubSdkDir = 'mopub-android-sdk'

**Comment by chauduyphanvu1** [comment]
@GITHUB243884919, could you explain what you are trying to do here before getting that error? If you want to clone the repository to access the mediation adapters, you probably will want the public-facing versions, so feel free to comment out the Gradle check like you did above.

Vu Chau
MoPub SDK Team

**Comment by GITHUB243884919** [comment]
I want build mopub-android-mediation in my computer. you mean is I need download it  form releases 
https://github.com/mopub/mopub-android-mediation/releases

**Comment by chauduyphanvu1** [comment]
@GITHUB243884919, check out https://github.com/mopub/mopub-android-mediation/issues/172#issuecomment-502692700, where I explained the differences between the aars you need for mediation.
