### ISSUE TITLE
Didn't find class "com.google.android.gms.ads.rewarded.RewardedAdLoadCallback"

### ISSUE THREAD

**Issue by GITHUB243884919** [mopub/mopub-android-mediation#171]
1. **What is the issue?**
    >I can not watch Rewarded Video in my Unity Andriod Game。Pleases help me, Thanks you !!!
i saw import com.google.android.gms.ads.rewarded.RewardedAdLoadCallback;  in code.
where is it? I need download some thing? 

there is the device log

I have integrated  mopub and admob in Unity（Android）。I have download mopub-android-mediation and copy mopub-admob-adapters-17.2.1.0..arr to my Unity project。
When I run my game and clicked a button for  watching Rewarded Video.， but there is not video。I have adb logcat for watch the Android log， I have found:
06-13 15:52:54.122 17781 17781 I MoPub   : [com.mopub.mobileads.MoPubRewardedVideoManager][onAdSuccess] SDK Log - Couldn't create custom event with class name com.mopub.mobileads.GooglePlayServicesRewardedVideo
....
06-13 15:52:54.440 17781 17781 I MoPub   : No ads found for ad unit.
06-13 15:52:54.848 17781 17781 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.mopub.mobileads.GooglePlayServicesRewardedVideo$1>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/rewarded/RewardedAdLoadCallback;
......
06-13 15:52:54.849 17781 17781 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.rewarded.RewardedAdLoadCallback" on path: DexPathList[[zip file "/data/app/com.minigame.chengyu.az-1/base.apk"],nativeLibraryDirectories=[/data/app/com.minigame.chengyu.az-1/lib/arm, /data/app/com.minigame.chengyu.az-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
.....
06-13 15:52:54.849 17781 17781 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
.....

I have builded mopub-android-mediation in my computer， and copy new mopub-admob-adapters-17.2.1.0..arr  to my Unity project， but I wathed the same error。

Pleases help me, Thanks you again!!!

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ ] I searched https://developers.mopub.com/ and found no answer.
    - [ ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Rewarded Video
    * **Platform** (*Android, iOS, Unity*)
        > Unity Android
    * **MoPub SDK Version**
        > 5.5
    * **Mediation SDK Name & Version**
        > 
    * **Mediation Adapter Version**
        > mopub-admob-adapters-17.2.1.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > mopub ：d4334ab87913499abdc598438cdb7fbc admob ：ca-app-pub-2920699096839371~8732331210

    * **Device model and OS Version**
        >  Android 7.1.1
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Do this.
        > 2. Do that.
    * **Observed behavior**
        > Provide the data here
    * **Expected behavior** (if known)
        > Provide the data here
    * **Evidence** (if available)
        > I have integrated  mopub and admob in Unity（Android）。I have download mopub-android-mediation and copy mopub-admob-adapters-17.2.1.0..arr to my Unity project。
When I run my game and clicked a button for  watching Rewarded Video.， but there is not video。I have adb logcat for watch the Android log， I have found:
06-13 15:52:54.122 17781 17781 I MoPub   : [com.mopub.mobileads.MoPubRewardedVideoManager][onAdSuccess] SDK Log - Couldn't create custom event with class name com.mopub.mobileads.GooglePlayServicesRewardedVideo
....
06-13 15:52:54.440 17781 17781 I MoPub   : No ads found for ad unit.
06-13 15:52:54.848 17781 17781 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.mopub.mobileads.GooglePlayServicesRewardedVideo$1>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/rewarded/RewardedAdLoadCallback;
......
06-13 15:52:54.849 17781 17781 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.rewarded.RewardedAdLoadCallback" on path: DexPathList[[zip file "/data/app/com.minigame.chengyu.az-1/base.apk"],nativeLibraryDirectories=[/data/app/com.minigame.chengyu.az-1/lib/arm, /data/app/com.minigame.chengyu.az-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
.....
06-13 15:52:54.849 17781 17781 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
.....

**Comment by chauduyphanvu1** [comment]
@GITHUB243884919, you are getting this issue because you don't have the AdMob Mobile Ads SDK imported in your Unity project. This is the same as https://github.com/mopub/mopub-android-mediation/issues/172 you opened. Make sure you follow my suggestions on https://github.com/mopub/mopub-android-mediation/issues/172 to integrate both mediation adapters and SDKs via the Unity SDK Manager.

Vu Chau
MoPub SDK Team
