### ISSUE TITLE
Unity Andriod Crash 

### ISSUE THREAD

**Issue by GITHUB243884919** [mopub/mopub-android-mediation#172]
1. **What is the issue?**
    > copy mopub-facebookaudiencenetwork-adapters-5.3.1.0.aar in my unity project, then build apk, and run it on phone. it is crashed!

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ ] I searched https://developers.mopub.com/ and found no answer.
    - [ ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Provide the data here
    * **Platform** (*Android, iOS, Unity*)
        > Android  Unity
    * **MoPub SDK Version**
        > 5.5
    * **Mediation SDK Name & Version**
        > Provide the data here
    * **Mediation Adapter Version**
        > mopub-facebookaudiencenetwork-adapters-5.3.1.0.aar 
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > mopub d4334ab87913499abdc598438cdb7fbc facebook: 2386844721593548_2392237347720952
    * **Device model and OS Version**
        > android 7.1.1
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Do this.
        > 2. Do that.
    * **Observed behavior**
        > Provide the data here
    * **Expected behavior** (if known)
        > Provide the data here
    * **Evidence** (if available)
        > 06-13 16:32:59.144 28326 28351 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/ads/AudienceNetworkAds;

**Comment by chauduyphanvu1** [comment]
@GITHUB243884919, from the error (NoClassDefFoundError), it looks like the Facebook Audience Network SDK is not integrated (or integrated but later removed) into your app project. Could you confirm if that is the case? Make sure you import the Facebook Audience Network SDK from [here](https://developers.mopub.com/publishers/mediation/integrate/). 

Vu Chau
MoPub SDK Team

**Comment by GITHUB243884919** [comment]
> @GITHUB243884919, from the error (NoClassDefFoundError), it looks like the Facebook Audience Network SDK is not integrated (or integrated but later removed) into your app project. Could you confirm if that is the case? Make sure you import the Facebook Audience Network SDK from [here](https://developers.mopub.com/publishers/mediation/integrate/).
> 
> Vu Chau
> MoPub SDK Team

I have copied mopub-facebookaudiencenetwork-adapters-5.3.1.0.aar to my Unity project. under the Assets/Plugins/Android           
mopub-facebookaudiencenetwork-adapters-5.3.1.0.aar is not Facebook Audience Network SDK ?

**Comment by chauduyphanvu1** [comment]
@GITHUB243884919, `mopub-facebookaudiencenetwork-adapters-5.3.1.0.aar` is the mediation adapters, not the Facebook Audience Network SDK. You will still need its SDK to be able to make ad requests and not crash the app.

Since you said you are on Unity, the easier way will be to use the [Unity SDK Manager](https://developers.mopub.com/publishers/unity/get-started/#option-1-use-the-sdk-manager-recommended) to download and install mediation SDKs and adapters. Simply select the network, and hit `Install`. All the steps will be taken care of on your behalf.

Check that out and let us know if you still see the crash!

**Comment by GITHUB243884919** [comment]
> @GITHUB243884919, `mopub-facebookaudiencenetwork-adapters-5.3.1.0.aar` is the mediation adapters, not the Facebook Audience Network SDK. You will still need its SDK to be able to make ad requests and not crash the app.
> 
> Since you said you are on Unity, the easier way will be to use the [Unity SDK Manager](https://developers.mopub.com/publishers/unity/get-started/#option-1-use-the-sdk-manager-recommended) to download and install mediation SDKs and adapters. Simply select the network, and hit `Install`. All the steps will be taken care of on your behalf.
> 
> Check that out and let us know if you still see the crash!

Thank you。 But I can use SDK, My SDK Window can not show any Network SDKs, I have to Integrated Manually。 I have download mopub-android-mediation form there， and copy aar to my Unity project。
It not success! So I have builded  mopub-android-mediation in  my computer. and copy new *.aar to my Unity proejct. But I saw the same error in the log.
![mopub_sdk_manager](https://user-images.githubusercontent.com/17681628/59478524-2511cd00-8e8c-11e9-8cb6-7300ceb739b3.png)

**Comment by chauduyphanvu1** [comment]
@GITHUB243884919, the aar you are using from your description only contains the adapters and not the Facebook Audience Network SDK (it comes in a separate aar and requires a separate download). You can download the Facebook SDK aar from [this site](https://developers.facebook.com/docs/audience-network/download/#android). You do not need to rebuild aars.

**Comment by GITHUB243884919** [comment]
> @GITHUB243884919, the aar you are using from your description only contains the adapters and not the Facebook Audience Network SDK (it comes in a separate aar and requires a separate download). You can download the Facebook SDK aar from [this site](https://developers.facebook.com/docs/audience-network/download/#android). You do not need to rebuild aars.

Thank you very much!!! I feel good， I feel I look hope~
I have 3 questions:
1.I am visiting https://developers.facebook.com/docs/audience-network/download/#android there is lot of version of "facebook Android Audience Network SDK".  I do not know what is my choice. 
2.As you say, I need Admob(google)network SDK too, Could you tell me its web sit. and How to choice version?
3. Why I can not use Mopub SDK Manager in Unity. I can see any platforms（google，facebook...）SDK in SDK window of Unity, I have screenshot to you at above.

**Comment by GITHUB243884919** [comment]
> @GITHUB243884919, the aar you are using from your description only contains the adapters and not the Facebook Audience Network SDK (it comes in a separate aar and requires a separate download). You can download the Facebook SDK aar from [this site](https://developers.facebook.com/docs/audience-network/download/#android). You do not need to rebuild aars.

I have download AudienceNetwork and version is 5.3.1 , crash again :( 
This time, there is not  "java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/ads/AudienceNetworkAds;" in the log. 
instead, 
the log shows  : 06-18 13:04:30.432 29206 29225 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.MobileAds" on path: DexPathList[[zip file "/data/app/com.minigame.chengyu.az-1/base.apk"],nativeLibraryDirectories=[/data/app/com.minigame.chengyu.az-1/lib/arm, /data/app/com.minigame.chengyu.az-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]

I think i still miss something, maybe is Admob(google)network SDK too. 
Please help me again. I feel I very close to sunccessed. thanks you agin.

**Comment by chauduyphanvu1** [comment]
You can usually choose the newest version of mediation SDKs to integrate. To know which versions we support, visit our [Mediation Integration Tool](https://developers.mopub.com/publishers/mediation/integrate/). 

To download the AdMob Mobile Ads SDK, because it's included in Google Play services, you will need to download `com.google.android.gms:play-services-ads`. That will be the AdMob SDK. This is your download link: https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads/17.2.1/play-services-ads-17.2.1.aar.

Because you are still having crashes, I believe you are not putting the SDKs into the correct location in your project. Could you confirm you are putting the SDK aar's correctly like this?

![image](https://user-images.githubusercontent.com/25616035/59689940-8b5d5f00-91ae-11e9-87d6-61881b6c8e0d.png)

**Comment by GITHUB243884919** [comment]
> You can usually choose the newest version of mediation SDKs to integrate. To know which versions we support, visit our [Mediation Integration Tool](https://developers.mopub.com/publishers/mediation/integrate/).
> 
> To download the AdMob Mobile Ads SDK, because it's included in Google Play services, you will need to download `com.google.android.gms:play-services-ads`. That will be the AdMob SDK. This is your download link: https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads/17.2.1/play-services-ads-17.2.1.aar.
> 
> Because you are still having crashes, I believe you are not putting the SDKs into the correct location in your project. Could you confirm you are putting the SDK aar's correctly like this?
> 
> ![image](https://user-images.githubusercontent.com/25616035/59689940-8b5d5f00-91ae-11e9-87d6-61881b6c8e0d.png)
thank you~
I have downloaded play-service-ads-17.2.1.aar and copy it to /Assets/Plugins/Android, But it still crash.
![mopub_0619](https://user-images.githubusercontent.com/17681628/59733013-ffffce80-927e-11e9-9706-65d1f642da7c.jpg)

The log looks like before:
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/MobileAds;
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.MobileAds"

**Comment by chauduyphanvu1** [comment]
I see the problem now. We don't have many publishers using the manual integration so the documentation does not contain the most up-to-date SDK dependencies. For AdMob, you will need to download and add the following aars to your Unity project (`Assets/Plugins/Android`):

```
// Play services dependencies
play-services-ads-base-17.2.1.aar
play-services-measurement-base-16.3.0.aar
play-services-measurement-sdk-api-16.3.0.aar
play-services-ads-17.2.1.aar
play-services-ads-identifier-17.0.0.aar
play-services-ads-lite-18.0.0.aar
play-services-basement-17.0.0.aar
play-services-gass-18.0.0.aar

// AdMob adapters
mopub-admob-adapters-17.2.1.0.aar
```

Ensure the versions match those in the list. Having multiple different versions for multiple Play services dependencies can lead to compilation issues in Unity. That is one of the disadvantages of not having the SDK Manager / Jar Resolver working here, since it'd handle version management for you. Could you open a separate issue report for how you cannot use the SDK Manager? Thank you!

**Comment by GITHUB243884919** [comment]
> I see the problem now. We don't have many publishers using the manual integration so the documentation does not contain the most up-to-date SDK dependencies. For AdMob, you will need to download and add the following aars to your Unity project (`Assets/Plugins/Android`):
> 
> ```
> // Play services dependencies
> play-services-ads-base-17.2.1.aar
> play-services-measurement-base-16.3.0.aar
> play-services-measurement-sdk-api-16.3.0.aar
> play-services-ads-17.2.1.aar
> play-services-ads-identifier-17.0.0.aar
> play-services-ads-lite-18.0.0.aar
> play-services-basement-17.0.0.aar
> play-services-gass-18.0.0.aar
> 
> // AdMob adapters
> mopub-admob-adapters-17.2.1.0.aar
> ```
> 
> Ensure the versions match those in the list. Having multiple different versions for multiple Play services dependencies can lead to compilation issues in Unity. That is one of the disadvantages of not having the SDK Manager / Jar Resolver working here, since it'd handle version management for you. Could you open a separate issue report for how you cannot use the SDK Manager? Thank you!

Thank you~
I will commit a new issue for can not use SDK Manager later.
Could you tell me  download url of those aar files. I can not found any infomation form google's web sit.
I guess these in google's Android SDK Manager. but I can not found these in my SDK Manager, and I do not know how to download these aars in Android SDK Manager.

**Comment by chauduyphanvu1** [comment]
You can use the link I posted previously, and replace the AAR name and the version numbers with the one you want to download: https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads/17.2.1/play-services-ads-17.2.1.aar

Or, if you have downloaded the Android SDK, check your download folder. You might be able to find them there as well: https://stackoverflow.com/questions/47672929/google-play-services-aar-download-for-above-11-0-4

**Comment by GITHUB243884919** [comment]
> You can use the link I posted previously, and replace the AAR name and the version numbers with the one you want to download: https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads/17.2.1/play-services-ads-17.2.1.aar
> 
> Or, if you have downloaded the Android SDK, check your download folder. You might be able to find them there as well: https://stackoverflow.com/questions/47672929/google-play-services-aar-download-for-above-11-0-4

Thank you reply soon~
I view https://stackoverflow.com/questions/47672929/google-play-services-aar-download-for-above-11-0-4 but I did  not found these aar files.
Then I have edited these url  in my Chrome, but it can not download  and shows 404 error.
play-services-ads-base-17.2.1.aar
https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads-base/17.2.1/play-services-ads-base-17.2.1.aar

play-services-measurement-base-16.3.0.aar
https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-base/16.3/play-services-measurement-base-16.3.0.aar

play-services-measurement-sdk-api-16.3.0.aar
https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-sdk-api/16.3/play-services-measurement-sdk-api-16.3.0.aar

play-services-ads-identifier-17.0.0.aar
https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads-identifier/17/play-services-ads-identifier-17.0.0.aar

play-services-ads-lite-18.0.0.aar
https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads-lite/18/play-services-ads-lite-18.0.0.aar

play-services-basement-17.0.0.aar
https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-basement/17/play-services-basement-17.0.0.aar

play-services-gass-18.0.0.aar
https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-gass/18/play-services-gass-18.0.0.aar

**Comment by GITHUB243884919** [comment]
> I see the problem now. We don't have many publishers using the manual integration so the documentation does not contain the most up-to-date SDK dependencies. For AdMob, you will need to download and add the following aars to your Unity project (`Assets/Plugins/Android`):
> 
> ```
> // Play services dependencies
> play-services-ads-base-17.2.1.aar
> play-services-measurement-base-16.3.0.aar
> play-services-measurement-sdk-api-16.3.0.aar
> play-services-ads-17.2.1.aar
> play-services-ads-identifier-17.0.0.aar
> play-services-ads-lite-18.0.0.aar
> play-services-basement-17.0.0.aar
> play-services-gass-18.0.0.aar
> 
> // AdMob adapters
> mopub-admob-adapters-17.2.1.0.aar
> ```
> 
> Ensure the versions match those in the list. Having multiple different versions for multiple Play services dependencies can lead to compilation issues in Unity. That is one of the disadvantages of not having the SDK Manager / Jar Resolver working here, since it'd handle version management for you. Could you open a separate issue report for how you cannot use the SDK Manager? Thank you!

I found a web sit can download these aar， but when I build Unity project，Unity show error：

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536

**Comment by GITHUB243884919** [comment]
> I see the problem now. We don't have many publishers using the manual integration so the documentation does not contain the most up-to-date SDK dependencies. For AdMob, you will need to download and add the following aars to your Unity project (`Assets/Plugins/Android`):
> 
> ```
> // Play services dependencies
> play-services-ads-base-17.2.1.aar
> play-services-measurement-base-16.3.0.aar
> play-services-measurement-sdk-api-16.3.0.aar
> play-services-ads-17.2.1.aar
> play-services-ads-identifier-17.0.0.aar
> play-services-ads-lite-18.0.0.aar
> play-services-basement-17.0.0.aar
> play-services-gass-18.0.0.aar
> 
> // AdMob adapters
> mopub-admob-adapters-17.2.1.0.aar
> ```
> 
> Ensure the versions match those in the list. Having multiple different versions for multiple Play services dependencies can lead to compilation issues in Unity. That is one of the disadvantages of not having the SDK Manager / Jar Resolver working here, since it'd handle version management for you. Could you open a separate issue report for how you cannot use the SDK Manager? Thank you!

Thank you very much~
I have resoved the problem about error:  [0, 0xffff]: 65536 and my apk can install and it can run also.
But, I still can not play RewardedVideo. I hvae integrated Facebook and admob.
MoPub Unit ID :d4334ab87913499abdc598438cdb7fbc
Admob :ca-app-pub-2920699096839371~8732331210
Facebook placement:2386844721593548_2392237347720952
I found these infomation in log:
06-20 14:27:14.728 26005 26005 I MoPub   : [com.mopub.mobileads.MoPubRewardedVideoManager][fetchAd] SDK Log - Loading rewarded ad request for ad unit d4334ab87913499abdc598438cdb7fbc with URL https://ads.mopub.com/m/ad?v=6&id=d4334ab87913499abdc598438cdb7fbc&nv=5.5.0%2Bunity&dn=OPPO%2COPPO%20R11s%2CR11s&bundle=com.minigame.chengyu.az&ll=39.962395%2C116.44266&lla=29&llf=78948&llsdk=1&z=%2B0800&o=p&w=1080&h=2160&sc=3.0&mcc=460&mnc=01&cn=China%20Unicom&ct=6&av=1.0.2&udid=mp_tmpl_advertising_id&dnt=mp_tmpl_do_not_track&gdpr_applies=0&force_gdpr_applies=0&current_consent_status=unknown&mr=1&android_perms_ext_storage=0&vv=0
06-20 14:27:14.735 26005 26026 W GooglePlayServicesUtil: Google Play services out of date.  Requires 12451000 but found 10298448

**Comment by chauduyphanvu1** [comment]
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536

What this error log means is that the project contains too many methods (probably from the many SDKs and libraries), such that the number of method exceeds 65536 in total (therefore the name `DexIndexOverflowException`). What you need to do to resolve this exception is to enable multidex in your Unity project by following the [instructions here](https://appmediation.com/unity-enable-multidex/). Once that's done, you will have more than 1 dex files to contain all of classes and methods when you make an Android build.

> But, I still can not play RewardedVideo. I hvae integrated Facebook and admob.

It could be a simple no-fill situation, which means the ad networks do not have inventory to return ads at the time of your ad request. Did you have any luck later? Could you also request using test ad unit IDs instead (to validate your integration and implementation)? If everything works with test ads, then it's an issue with the ad unit IDs you were using. 

You can find the AdMob test ad unit IDs [here](https://developers.google.com/admob/android/test-ads#sample_ad_units). For Facebook Audience Network, you can enable test mode by calling `MoPubAndroid.AddFacebookTestDeviceId("YOUR_DEVICE_ID_SHOWN_IN_CONSOLE_LOG")` in C#.

> In the log， I feel something that very strange。you can find them in line 1072 from 0620_4.txt
Unable to find class com.mopub.mobileads.TapjoyAdapterConfiguration, ChartboostAdapterConfiguration。。。。。

You can ignore those log messages. They are informational, not error logs. They mean the MoPub SDK is attempting to initialize those ad network SDKs but their adapters are not found in your project, so initialization for them will be skipped. Initialization will take place for the networks whose adapters exist in your project (in this case, Facebook and AdMob).

**Comment by GITHUB243884919** [comment]
> > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
> 
> What this error log means is that the project contains too many methods (probably from the many SDKs and libraries), such that the number of method exceeds 65536 in total (therefore the name `DexIndexOverflowException`). What you need to do to resolve this exception is to enable multidex in your Unity project by following the [instructions here](https://appmediation.com/unity-enable-multidex/). Once that's done, you will have more than 1 dex files to contain all of classes and methods when you make an Android build.
> 
> > But, I still can not play RewardedVideo. I hvae integrated Facebook and admob.
> 
> It could be a simple no-fill situation, which means the ad networks do not have inventory to return ads at the time of your ad request. Did you have any luck later? Could you also request using test ad unit IDs instead (to validate your integration and implementation)? If everything works with test ads, then it's an issue with the ad unit IDs you were using.
> 
> You can find the AdMob test ad unit IDs [here](https://developers.google.com/admob/android/test-ads#sample_ad_units). For Facebook Audience Network, you can enable test mode by calling `MoPubAndroid.AddFacebookTestDeviceId("YOUR_DEVICE_ID_SHOWN_IN_CONSOLE_LOG")` in C#.
> 
> > In the log， I feel something that very strange。you can find them in line 1072 from 0620_4.txt
> > Unable to find class com.mopub.mobileads.TapjoyAdapterConfiguration, ChartboostAdapterConfiguration。。。。。
> 
> You can ignore those log messages. They are informational, not error logs. They mean the MoPub SDK is attempting to initialize those ad network SDKs but their adapters are not found in your project, so initialization for them will be skipped. Initialization will take place for the networks whose adapters exist in your project (in this case, Facebook and AdMob).
Thank you 
I am in my home now, I will try it in my office tomorrow. But I do not know what is "...ad networks do not have inventory to return ads ..." if my game or app is published in GooglePlay Store, that play ad need luck time? I do not understand. And Facebook need add Test DeviceId .......

**Comment by GITHUB243884919** [comment]
> > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
> 
> What this error log means is that the project contains too many methods (probably from the many SDKs and libraries), such that the number of method exceeds 65536 in total (therefore the name `DexIndexOverflowException`). What you need to do to resolve this exception is to enable multidex in your Unity project by following the [instructions here](https://appmediation.com/unity-enable-multidex/). Once that's done, you will have more than 1 dex files to contain all of classes and methods when you make an Android build.
> 
> > But, I still can not play RewardedVideo. I hvae integrated Facebook and admob.
> 
> It could be a simple no-fill situation, which means the ad networks do not have inventory to return ads at the time of your ad request. Did you have any luck later? Could you also request using test ad unit IDs instead (to validate your integration and implementation)? If everything works with test ads, then it's an issue with the ad unit IDs you were using.
> 
> You can find the AdMob test ad unit IDs [here](https://developers.google.com/admob/android/test-ads#sample_ad_units). For Facebook Audience Network, you can enable test mode by calling `MoPubAndroid.AddFacebookTestDeviceId("YOUR_DEVICE_ID_SHOWN_IN_CONSOLE_LOG")` in C#.
> 
> > In the log， I feel something that very strange。you can find them in line 1072 from 0620_4.txt
> > Unable to find class com.mopub.mobileads.TapjoyAdapterConfiguration, ChartboostAdapterConfiguration。。。。。
> 
> You can ignore those log messages. They are informational, not error logs. They mean the MoPub SDK is attempting to initialize those ad network SDKs but their adapters are not found in your project, so initialization for them will be skipped. Initialization will take place for the networks whose adapters exist in your project (in this case, Facebook and AdMob).


Thank you~
I have added MoPubAndroid.AddFacebookTestDeviceId("892D127999AE79AA6DD5A4BA20F7F4EB");
in my c# code。 and only facebook is Integrated。but it still can not play ad。
I only add c# code for this thing？ It do not need to setting web sit （mopub ？ facebook？ or both？）？
I have another question， that is about admob test。
You tell me can use test unit id，if I not only need to change test  unit id in c# but also need to  set some thing at web sit （Mopub ？ Admob？ or both？）

**Comment by GITHUB243884919** [comment]
> > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
> 
> What this error log means is that the project contains too many methods (probably from the many SDKs and libraries), such that the number of method exceeds 65536 in total (therefore the name `DexIndexOverflowException`). What you need to do to resolve this exception is to enable multidex in your Unity project by following the [instructions here](https://appmediation.com/unity-enable-multidex/). Once that's done, you will have more than 1 dex files to contain all of classes and methods when you make an Android build.
> 
> > But, I still can not play RewardedVideo. I hvae integrated Facebook and admob.
> 
> It could be a simple no-fill situation, which means the ad networks do not have inventory to return ads at the time of your ad request. Did you have any luck later? Could you also request using test ad unit IDs instead (to validate your integration and implementation)? If everything works with test ads, then it's an issue with the ad unit IDs you were using.
> 
> You can find the AdMob test ad unit IDs [here](https://developers.google.com/admob/android/test-ads#sample_ad_units). For Facebook Audience Network, you can enable test mode by calling `MoPubAndroid.AddFacebookTestDeviceId("YOUR_DEVICE_ID_SHOWN_IN_CONSOLE_LOG")` in C#.
> 
> > In the log， I feel something that very strange。you can find them in line 1072 from 0620_4.txt
> > Unable to find class com.mopub.mobileads.TapjoyAdapterConfiguration, ChartboostAdapterConfiguration。。。。。
> 
> You can ignore those log messages. They are informational, not error logs. They mean the MoPub SDK is attempting to initialize those ad network SDKs but their adapters are not found in your project, so initialization for them will be skipped. Initialization will take place for the networks whose adapters exist in your project (in this case, Facebook and AdMob).

Thank you~ about error 65535

**Comment by chauduyphanvu1** [comment]
The MoPub SDK supports all Android versions newer than Android 4, so 8 and 9 should also be fine and have also been tested on. Are you sure the error popup does not pertain to some configurations at the application-level in your Unity project? 

If there are any questions, feel free to email support@mopub.com so we can look into your implementation! Thank you.

**Comment by GITHUB243884919** [comment]
> The MoPub SDK supports all Android versions newer than Android 4, so 8 and 9 should also be fine and have also been tested on. Are you sure the error popup does not pertain to some configurations at the application-level in your Unity project?
> 
> If there are any questions, feel free to email [support@mopub.com](mailto:support@mopub.com) so we can look into your implementation! Thank you.


Thank you~
I have 3 questions and 1 suggest
**1.About "...ad networks do not have inventory to return ads ..."** 
I do not know what mean is "...ad networks do not have inventory to return ads ..."(your answer) If my game is published in GooglePlay Store, Then play ad need luck time? I do not understand that. could you tell me more  detail . I think that there is a AD could be show in anytime if I called Mopub's API, And it play Facebook's ad need add Test DeviceId, I donot know my user's DeviceId .What should I do? .......

**2.About Test**
I have added MoPubAndroid.AddFacebookTestDeviceId("892D127999AE79AA6DD5A4BA20F7F4EB");
in my c# code。 and only facebook is Integrated。but it still can not play ad。
I only add c# code for this thing？ It do not need to setting web sit （mopub ？ facebook？ or both？）？about admob test。You told me could use test unit id，if I not only need to change test unit id in c# but also need to set some thing at web sit （Mopub ？ Admob？ or both？）

**3. About  Android8,9 shows " Your hardware does not support this application.."**
I think Mopub can supports Android8,9.   I think that I must have done something wrong。In My Unity porject include Mopub and other SDK(aar,jar) So I will create a new project that it only include Mopub.
     As you say about " application-level ", I do not think so. Because my apk could be run in Android8,9 if I remove all google services aar files and new AndroidManifest file(I create a new file) and mainTemplate.gradle. You know I add AndroidManifest and mainTemplate.gradle because error 65536. I have done some thing for it , that is same as you told https://appmediation.com/unity-enable-multidex/

**Suggest for Test**
I think a better way that you provide a mopub unit id. that id include admob id, facebook id .... Why I say that? Because I have used a test mopub unit id(from your  web sit ), and it can play AD. I think that AD is mopub test AD ， not admob AD. I have viewed log file, It look like it donot call any interface of google. And that time, I donot copy any google service aar files and facebok network aar file . I have tested, It is not crash if donot copy any google service and facebok network aar file and it only include google adapter. But if copy facebook adapter, It will be crash, I have viewed log file , It looks like facebook call some interface of google service and there is not google service aar files.
      Another reason is : Programer , just like me, we do not manage unit id(Mopub, Admob, Facebook... ) and we do not set up it in web sit also。That things are done by another guy。I think most company is that。
