### ISSUE TITLE
I still Can not play reward video (Unity Android)

### ISSUE THREAD

**Issue by GITHUB243884919** [mopub/mopub-android-mediation#177]
1. **What is the issue?**
    >I can not play rewardvideo  in my app still
our mopub unit id ：d4334ab87913499abdc598438cdb7fbc
I use admob test id adMobAppId = ca-app-pub-3940256099942544/5224354917 form https://developers.google.com/admob/android/test-ads#sample_ad_units
or our admob id ca-app-pub-2920699096839371~8732331210。

**this is log file**
[pure_0624_02.txt](https://github.com/mopub/mopub-android-mediation/files/3323166/pure_0624_02.txt)

**this is my c# code for Mopub and Admob。**
 MoPub.MediatedNetwork adMobMediatedNetwork = new MoPub.SupportedNetwork.AdMob();
            adMobMediatedNetwork.MediationSettings = new Dictionary<string, object>()
            {
                {"npa", "1"}
            };
            adMobMediatedNetwork.NetworkConfiguration = new Dictionary<string, object>()
            {
                //adMobAppId = ca-app-pub-3940256099942544/5224354917
                {"app_id", adMobAppId}
            };

            MoPubBase.LogLevel logLevel = MoPubBase.LogLevel.MPLogLevelNone;
            if (isDebugMode)
            {
                logLevel = MoPubBase.LogLevel.MPLogLevelDebug;
            }

            MoPub.InitializeSdk(new MoPub.SdkConfiguration
            {
                //AdUnitId = m_bannerAdUnitId,
                AdUnitId = m_rewardedVideoAdUnitId,
                LogLevel = logLevel,
                //                AllowLegitimateInterest = true,

                MediatedNetworks = new MoPub.MediatedNetwork[]
                {
                    //appLovinMediatedNetwork,
                    adMobMediatedNetwork,
                    //unityMediatedNetwork,
                    //facebookMediatedNetwork,
                    //vungleMediatedNetwork
                }
            });

            MoPub.LoadBannerPluginsForAdUnits(new string[] { m_bannerAdUnitId });
            MoPub.LoadInterstitialPluginsForAdUnits(new string[] { m_interstitialAdUnitId });
            //m_rewardedVideoAdUnitId = d4334ab87913499abdc598438cdb7fbc
            MoPub.LoadRewardedVideoPluginsForAdUnits(new string[] { m_rewardedVideoAdUnitId });

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ ] I searched https://developers.mopub.com/ and found no answer.
    - [ ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        >  Rewarded Video,
    * **Platform** (*Android, iOS, Unity*)
        > Android Unity
    * **MoPub SDK Version**
        >5.5.0
    * **Mediation SDK Name & Version**
        >play-services-ads-17.2.1
    * **Mediation Adapter Version**
        > mopub-admob-adapters-17.2.1.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > MoPub Ad Unit ID :d4334ab87913499abdc598438cdb7fbc
        >admob  ca-app-pub-3940256099942544/5224354917 (from https://developers.google.com/admob/android/test-ads#sample_ad_units)
    * **Device model and OS Version**
        > android 7,8,9
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Do this.
        > 2. Do that.
    * **Observed behavior**
        > Provide the data here
    * **Expected behavior** (if known)
        > Provide the data here
    * **Evidence** (if available)
        > Attach logs (device/network), mini debug builds (source code preferably), stack traces, screenshots / screen recordings, etc.
06-24 10:55:31.256 17401 17401 I MoPub   : [com.mopub.mobileads.MoPubRewardedVideoManager][onAdSuccess] SDK Log - Couldn't create custom event with class name com.mopub.mobileads.FacebookRewardedVideo
06-24 10:55:31.258 17401 17401 I MoPub   : [com.mopub.mobileads.MoPubRewardedVideoManager][fetchAd] SDK Log - Loading rewarded ad request for ad unit d4334ab87913499abdc598438cdb7fbc with URL
06-24 10:55:31.260 17401 17401 I MoPub   : [com.mopub.mobileads.MoPubRewardedVideoManager][onAdSuccess] SDK Log - Couldn't create custom event with class name com.mopub.mobileads.GooglePlayServicesRewardedVideo
06-24 10:55:31.260 17401 17401 I MoPub   : [com.mopub.mobileads.MoPubRewardedVideoManager][fetchAd] SDK Log - Loading rewarded ad request for ad unit d4334ab87913499abdc598438cdb7fbc with URL
06-24 10:55:31.264 17401 17519 I MoPub   : [com.mopub.common.GpsHelper][fetchAdvertisingInfoSync] SDK Log - Unable to obtain Google AdvertisingIdClient.Info via reflection.
06-24 10:55:31.270 17401 17401 I MoPub   : [com.mopub.network.AdLoader][fetchAd] Ad requesting from AdServer: https://ads.mopub.com/m/ad
06-24 10:55:31.270 17401 17401 I MoPub   : {"request_id":"93f1bb7d0228446d972f14fd39642525_00475a71003e15df","exclude_targeting_hash":"4e7c9cc76cea828557e5ca8c83ed734f","ct":"6","exclude":"1374003c8bf711e9b793506b4b161d6c,137471d48bf711e9b793506b4b161d6c","current_consent_status":"unknown","cppck":"8C9E9","v":"6","dn":"OPPO,OPPO R11s,R11s","bundle":"com.minigame.chengyu.az","o":"p","id":"d4334ab87913499abdc598438cdb7fbc","rtc":"1","udid":"mopub:a3dd5dfb-8035-41fb-80e7-13fa378f3d90","mcc":"460","nv":"5.5.0+unity","sc":"3.0","ac":"1","tqr":"XRA7pMaDhksQzMt2qNP_HnRvlP5oAx_p2LTeuQ","force_gdpr_applies":"0","llf":"-2023165887","cn":"China Unicom","z":"+0800","dnt":"0","mr":"1","gdpr_applies":"0","h":"2160","w":"1080","av":"1.0.2","lla":"0","mnc":"01","android_perms_ext_storage":"0","ll":"99999.0,99999.0","vv":"0"}
06-24 10:55:31.552 17401 17401 I MoPub   : [com.mopub.network.TrackingRequest$1][onResponse] SDK Log - Successfully hit tracking endpoint: https://ads.mopub.com/m/attempt
06-24 10:55:31.553 17401 17401 I MoPub   : [com.mopub.network.TrackingRequest$1][onResponse] SDK Log - Successfully hit tracking endpoint: https://ads.mopub.com/m/attempt
06-24 10:55:32.396 17401 17509 I MoPub   : [com.mopub.network.MultiAdResponse][parseSingleAdResponse] Ad server responded with:
06-24 10:55:32.396 17401 17509 I MoPub   : {"content":"","metadata":{"x-adtype":"clear","x-backfill":"clear","x-refreshtime":60}}
06-24 10:55:32.399 17401 17401 I MoPub   : [com.mopub.network.AdLoader$1][onErrorResponse] Ad server responded with:
06-24 10:55:32.399 17401 17401 I MoPub   : No ads found for ad unit.
![QQ图片20190625092903](https://user-images.githubusercontent.com/17681628/60062425-b8b88880-972b-11e9-9015-26ee254091e2.png)

**Comment by chauduyphanvu** [comment]
@GITHUB243884919, it looks like there are issues instantiating the adapters (`Couldn't create custom event with class name`) in your game. Could you confirm you have the adapter aar's in Assets/Plugins/Android? If you have the APK, you can also reverse-engineer it to see if they exist in the `com.mopub.mobileads` package.

Vu Chau
MoPub SDK Team

**Comment by GITHUB243884919** [comment]
> @GITHUB243884919, it looks like there are issues instantiating the adapters (`Couldn't create custom event with class name`) in your game. Could you confirm you have the adapter aar's in Assets/Plugins/Android? If you have the APK, you can also reverse-engineer it to see if they exist in the `com.mopub.mobileads` package.
> 
> Vu Chau
> MoPub SDK Team
Thank you ~
I will use SDK Manager try again。I think use manually is not  a right way and I can use SDK Manager now.

**Comment by RannarYang** [comment]
I have the same question when I use sdk manager.

**Comment by chauduyphanvu** [comment]
@RannarYang, happy to help! 

What is the issue you are seeing and could you provide the details to help us reproduce it? If the issue is different from the one reported here, please consider opening a separate issue report. Thanks!

**Comment by LongLostPenPal** [comment]
I have the same question too , but I sill confused how to solve this problem.
I use Unity 2019.2.21f , MoPub 5.11.1 , AdMob 1.4.11 . I cant play reward video
` I/MoPub: [com.mopub.mobileads.MoPubRewardedVideoManager][onAdSuccess] SDK Log - Couldn't create custom event with class name com.mopub.mobileads.GooglePlayServicesRewardedVideo`
other Networks SDKs (such as AdColony AppLLovin) works well

**Comment by LongLostPenPal** [comment]
> @GITHUB243884919, it looks like there are issues instantiating the adapters (`Couldn't create custom event with class name`) in your game. Could you confirm you have the adapter aar's in Assets/Plugins/Android? If you have the APK, you can also reverse-engineer it to see if they exist in the `com.mopub.mobileads` package.
> 
> Vu Chau
> MoPub SDK Team

I have the same question too , but I sill confused how to solve this problem.
I use Unity 2019.2.21f , MoPub 5.11.1 , AdMob 1.4.11 . I cant play reward video
I/MoPub: [com.mopub.mobileads.MoPubRewardedVideoManager][onAdSuccess] SDK Log - Couldn't create custom event with class name com.mopub.mobileads.GooglePlayServicesRewardedVideo
other Networks SDKs (such as AdColony AppLLovin) works well
and there is no  adapter aar's in Assets/Plugins/Android

**Comment by chauduyphanvu** [comment]
@LongLostPenPal, if you are using AdMob 1.4.11 (equivalent to the 19.2.0.1 on Android and 7.61.0.1 on iOS), you need to **use the MoPub Unity SDK 5.13.0 at the minimum**, since that version of the adapters contains API-breaking changes that were introduced in the 5.13.0 SDK release.

More information is available in the [Android](https://github.com/mopub/mopub-ios-mediation/blob/master/AdMob/CHANGELOG.md) and [iOS](https://github.com/mopub/mopub-ios-mediation/blob/master/AdMob/CHANGELOG.md) changelogs. Let us know if there are any questions!

**Comment by LongLostPenPal** [comment]
> @LongLostPenPal, if you are using AdMob 1.4.11 (equivalent to the 19.2.0.1 on Android and 7.61.0.1 on iOS), you need to **use the MoPub Unity SDK 5.13.0 at the minimum**, since that version of the adapters contains API-breaking changes that were introduced in the 5.13.0 SDK release.
> 
> More information is available in the [Android](https://github.com/mopub/mopub-ios-mediation/blob/master/AdMob/CHANGELOG.md) and [iOS](https://github.com/mopub/mopub-ios-mediation/blob/master/AdMob/CHANGELOG.md) changelogs. Let us know if there are any questions!

it worked for me !  Thanks reply  ~

**Comment by LongLostPenPal** [comment]
> > @LongLostPenPal, if you are using AdMob 1.4.11 (equivalent to the 19.2.0.1 on Android and 7.61.0.1 on iOS), you need to **use the MoPub Unity SDK 5.13.0 at the minimum**, since that version of the adapters contains API-breaking changes that were introduced in the 5.13.0 SDK release.
> > More information is available in the [Android](https://github.com/mopub/mopub-ios-mediation/blob/master/AdMob/CHANGELOG.md) and [iOS](https://github.com/mopub/mopub-ios-mediation/blob/master/AdMob/CHANGELOG.md) changelogs. Let us know if there are any questions!
> 
> it worked for me ! Thanks for reply ~



> @LongLostPenPal, if you are using AdMob 1.4.11 (equivalent to the 19.2.0.1 on Android and 7.61.0.1 on iOS), you need to **use the MoPub Unity SDK 5.13.0 at the minimum**, since that version of the adapters contains API-breaking changes that were introduced in the 5.13.0 SDK release.
> 
> More information is available in the [Android](https://github.com/mopub/mopub-ios-mediation/blob/master/AdMob/CHANGELOG.md) and [iOS](https://github.com/mopub/mopub-ios-mediation/blob/master/AdMob/CHANGELOG.md) changelogs. Let us know if there are any questions!

It Crash With MoPub 5.13.0 In Some Devices #272
