### ISSUE TITLE
[Unity] AndroidX compilation issues with AdMob and Facebook Audience Network

### ISSUE THREAD

**Issue by GITHUB243884919** [mopub/mopub-android-mediation#178]
1. **What is the issue?**
    > Unity Android Build error after Add Facebook audience-network(Use SDK Manager)
    > I download Unity Sample App from https://developers.mopub.com/publishers/tools/sample-apps/
       My Unity project use  sdkManager download Google Admob build successed and it can be runed at phone.  then  I download audience-network  by SDK Manager. build error
![微信图片_20190626140125](https://user-images.githubusercontent.com/17681628/60155097-d533ee00-981b-11e9-8cff-583698ccfdad.png)
And I can found com.android.support.support-compat-28.0.0.aar in my project 
I modified manifest.xml , added tools:replace="android:appComponentFactory", but show same error
![微信图片_20190626180644](https://user-images.githubusercontent.com/17681628/60171554-67002300-983d-11e9-901b-87bb54c51f8f.png)

![image](https://user-images.githubusercontent.com/17681628/60171496-4afc8180-983d-11e9-85c5-b05fa8d4b580.png)

But I use Unity Sample App and I only download Facebook audience-network, I can build successed.
My Unity Version is Unity 2018.4.2f1  More detail error info is below.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ ] I searched https://developers.mopub.com/ and found no answer.
    - [ ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Provide the data here
    * **Platform** (*Android, iOS, Unity*)
        > Android Unity*
    * **MoPub SDK Version**
        > 5.7.1
    * **Mediation SDK Name & Version**
        > Facebook audience-network :1.3.0
        > Google(Admob 1.1.4)
    * **Mediation Adapter Version**
        > Provide the data here
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Provide the data here
    * **Device model and OS Version**
        > Provide the data here
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Do this.
        > 2. Do that.
    * **Observed behavior**
        > Provide the data here
    * **Expected behavior** (if known)
        > Provide the data here
    * **Evidence** (if available)
        > CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity-2018.4.2f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\OpenJDK\Windows\bin\java.exe -classpath "C:\Program Files\Unity-2018.4.2f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.6.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[
D:\fzy\study_project\mopub-unity-sdk-master\unity-sample-app\Temp\gradleOut\src\main\AndroidManifest.xml:22:18-86 Error:
	Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [:androidx.core.core-1.0.0:] AndroidManifest.xml:22:18-86
	is also present at [:com.android.support.support-compat-28.0.0:] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:4:3-15:17 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [:androidx.core.core-1.0.0:] AndroidManifest.xml:22:18-86
  	is also present at [:com.android.support.support-compat-28.0.0:] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:4:3-15:17 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
]
stdout[
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (28.0.2) for Android Gradle Plugin 3.2.0.
Android SDK Build Tools 28.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Observed package id 'build-tools;20.0.0' in inconsistent location 'D:\fzy\tools\jf_android-sdk-windows\android-sdk-windows\build-tools\android-4.4W' (Expected 'D:\fzy\tools\jf_android-sdk-windows\android-sdk-windows\build-tools\20.0.0')
Observed package id 'build-tools;23.0.1' in inconsistent location 'D:\fzy\tools\jf_android-sdk-windows\android-sdk-windows\build-tools\android-6.0' (Expected 'D:\fzy\tools\jf_android-sdk-windows\android-sdk-windows\build-tools\23.0.1')
Observed package id 'platforms;android-23' in inconsistent location 'D:\fzy\tools\jf_android-sdk-windows\android-sdk-windows\platforms\android-6.0' (Expected 'D:\fzy\tools\jf_android-sdk-windows\android-sdk-windows\platforms\android-23')
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (28.0.2) for Android Gradle Plugin 3.2.0.
Android SDK Build Tools 28.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
:checkReleaseClasspath UP-TO-DATE
:preBuild UP-TO-DATE
:MoPub.plugin:preBuild UP-TO-DATE
:MoPub.plugin:preReleaseBuild UP-TO-DATE
:MoPub.plugin:checkReleaseManifest
:MoPub.plugin:processReleaseManifest
:preReleaseBuild
:MoPub.plugin:compileReleaseAidl NO-SOURCE
:compileReleaseAidl NO-SOURCE
:MoPub.plugin:packageReleaseRenderscript NO-SOURCE
:compileReleaseRenderscript UP-TO-DATE
:checkReleaseManifest UP-TO-DATE
:generateReleaseBuildConfig UP-TO-DATE
:prepareLintJar UP-TO-DATE
:mainApkListPersistenceRelease UP-TO-DATE
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources UP-TO-DATE
:MoPub.plugin:compileReleaseRenderscript
:MoPub.plugin:generateReleaseResValues
:MoPub.plugin:generateReleaseResources
:MoPub.plugin:packageReleaseResources
:mergeReleaseResources UP-TO-DATE
:createReleaseCompatibleScreenManifests UP-TO-DATE
:processReleaseManifest

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

:processReleaseManifest FAILED
16 actionable tasks: 7 executed, 9 up-to-date
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <103137eb219949558cde9ab87892d16a>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <103137eb219949558cde9ab87892d16a>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <103137eb219949558cde9ab87892d16a>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <103137eb219949558cde9ab87892d16a>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <103137eb219949558cde9ab87892d16a>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <103137eb219949558cde9ab87892d16a>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <103137eb219949558cde9ab87892d16a>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <103137eb219949558cde9ab87892d16a>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <103137eb219949558cde9ab87892d16a>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <103137eb219949558cde9ab87892d16a>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:286)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by chauduyphanvu** [comment]
@GITHUB243884919, this is happening because the Jar Resolver in the MoPub Unity SDK Manager resolves to v18.0.0 of Google Play services, which pulls in AndroidX dependencies (instead of the regular Android support libraries - note the `androidx` in the package name in the error message), which causes build conflicts with the non-AndroidX libraries. 

Which ad networks & adapters are you integrating? Could you send us the Jar Resolver logs when it finishes resolving? That should provide details on which dependency is pulling Play services 18.0.0 / AndroidX. Alternatively, if you already know which libraries are doing that, you can delete the AndroidX aar's and use the regular Android support aar's. 

We're testing with AndroidX internally and will roll out a solution soon. More updates to come.

Vu Chau
MoPub SDK Team

**Comment by GITHUB243884919** [comment]
> @GITHUB243884919, this is happening because the Jar Resolver in the MoPub Unity SDK Manager resolves to v18.0.0 of Google Play services, which pulls in AndroidX dependencies (instead of the regular Android support libraries - note the `androidx` in the package name in the error message), which causes build conflicts with the non-AndroidX libraries.
> 
> Which ad networks & adapters are you integrating? Could you send us the Jar Resolver logs when it finishes resolving? That should provide details on which dependency is pulling Play services 18.0.0 / AndroidX. Alternatively, if you already know which libraries are doing that, you can delete the AndroidX aar's and use the regular Android support aar's.
> 
> We're testing with AndroidX internally and will roll out a solution soon. More updates to come.
> 
> Vu Chau
> MoPub SDK Team
2 question:
1. I  integrate Facebook audience-network :1.3.0 and Google(Admob 1.1.4)。 Should  I copy adapters without SDKManager ？ I think only use SDK Manager can get adapters （Facebook ，admob）to my project。
2. I do not know how to get  Jar Resolver logs , These logs in store in my computer?  Could you tell me more detail?
Screenshot was my SDK Manager When I have download Admob， Then I have download Facebook audience-network，
![60151032-c7776c00-980d-11e9-8f42-4c0285e5a37b](https://user-images.githubusercontent.com/17681628/60198326-e3155d80-9873-11e9-8b28-d4257669addf.png)

**Comment by chauduyphanvu** [comment]
Thank you for the confirmation. The combination of Facebook Audience Network and AdMob seems to be resolving to v18.0.0 of Play services for us too, and it will get AndroidX dependencies into the Unity project via the Jar Resolver. 

Could you try integrating the adapters and network SDKs manually? Or you could try integrating one manually and one via the SDK Manager. You will have to go back to [these links](https://github.com/mopub/mopub-android-mediation/issues/172#issuecomment-503820928) to get the non-AndroidX stuff that Google needs. Do a project-wide search for `androidx` - if there's no result, compilation should succeed.

**Comment by GITHUB243884919** [comment]
> Thank you for the confirmation. The combination of Facebook Audience Network and AdMob seems to be resolving to v18.0.0 of Play services for us too, and it will get AndroidX dependencies into the Unity project via the Jar Resolver.
> 
> Could you try integrating the adapters and network SDKs manually? Or you could try integrating one manually and one via the SDK Manager. You will have to go back to [these links](https://github.com/mopub/mopub-android-mediation/issues/172#issuecomment-503820928) to get the non-AndroidX stuff that Google needs. Do a project-wide search for `androidx` - if there's no result, compilation should succeed.

Thank you very much~
Manually ? I already afraid it now :(  I do not know how many aar or jar need to copy to my project。Could you solve it。 My Unity project is download form your web sit https://developers.mopub.com/publishers/tools/sample-apps/
You my use Unity  and SDK Manager  easy to meet this problem. 
My boss very care about this. I have done it for two weeks, but I still is not successed!

**Comment by chauduyphanvu** [comment]
We understand, and we are working on ensuring compatibility with AndroidX now. In the meantime, there's no other workaround other than pinning Google Play services to a version before v18.0.0 (for example, by integrating adapters + SDKs manually so you can bypass the Jar Resolver). I'll update this thread if there are other workarounds.

**Comment by GITHUB243884919** [comment]
> We understand, and we are working on ensuring compatibility with AndroidX now. In the meantime, there's no other workaround other than pinning Google Play services to a version before v18.0.0 (for example, by integrating adapters + SDKs manually so you can bypass the Jar Resolver). I'll update this thread if there are other workarounds.

I try to use SDK Manager that version is 5.5.0 ， but still build error。This time  error message is not same as use 5.7.1
![QQ图片20190629094504](https://user-images.githubusercontent.com/17681628/60378278-a2276f80-9a52-11e9-84f7-17002af4981e.png)
![QQ图片20190629094134](https://user-images.githubusercontent.com/17681628/60378280-a6538d00-9a52-11e9-9526-9c5adeb3c04a.png)

**Comment by chauduyphanvu** [comment]
@GITHUB243884919, I expect AndroidX-related compatibility issues to still be applicable even when you use a lower version of the MoPub Unity SDK. When conflicts between more than one dependencies arise, in this case the Jar Resolver will continue to get Play services 18.0.0 and that will download AndroidX aar's to your project. The safest workaround would be to integrate your ad networks and adapters manually (and skip the SDK Manager / Jar Resolver).

**Comment by chauduyphanvu** [comment]
@GITHUB243884919, this issue should be resolved in the 5.8.0 release of the MoPub Unity SDK. You can now enable the Jetifier in the Play Services Resolver's settings to resolve AndroidX conflicts. Let us know if you continue seeing the issue!
