### ISSUE TITLE
Can not Play reward rewardedVideo(Unity Sample App + sdkmanager + admob)

### ISSUE THREAD

**Issue by GITHUB243884919** [mopub/mopub-android-mediation#179]
1. **What is the issue?**
    > Can not Play reward rewardedVideo(Unity Sample App + sdkmanager) .
    > I download Unity Sample App from https://developers.mopub.com/publishers/tools/sample-apps/
My Unity project use sdkManager download Google Admob 
and I add below in AndroidManifest.xml
		<meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-2920699096839371~8732331210"/>
 and I modified MoPubDemoGUI.cs
Change mopub reward unit id to ours d4334ab87913499abdc598438cdb7fbc
    //private readonly string[] _rewardedVideoAdUnits = { "920b6145fb1546cf8b5cf2ac34638bb7" };
    private readonly string[] _rewardedVideoAdUnits = { "d4334ab87913499abdc598438cdb7fbc" };

and I modified MoPubDemoGUI's function Start() , set NetworkConfiguration  and MediationSettings 
                    NetworkConfiguration = new Dictionary<string,object> {
                        //{ "key1", value },
                        //{ "key2", value },
                        {"app_id", "ca-app-pub-2920699096839371~8732331210"}
                    },

                    // Global mediation settings (per ad request).
                    MediationSettings = new Dictionary<string,object> {
                        //{ "key1", value },
                        //{ "key2", value },
                         {"npa", "1"}
                    },

I did not edit MoPubRequestOptions because I do not know what is that?
Final, I can not play ad that show No ads found.

I use adb logcat get more detail
[onlygoogle_01.txt](https://github.com/mopub/mopub-android-mediation/files/3328980/onlygoogle_01.txt)

![微信图片_20190626161611](https://user-images.githubusercontent.com/17681628/60163247-c7876400-982d-11e9-9658-9f9981970cd3.jpg)

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ ] I searched https://developers.mopub.com/ and found no answer.
    - [ ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Provide the data here
    * **Platform** (*Android, iOS, Unity*)
        > Provide the data here
    * **MoPub SDK Version**
        > Provide the data here
    * **Mediation SDK Name & Version**
        > Provide the data here
    * **Mediation Adapter Version**
        > Provide the data here
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Provide the data here
    * **Device model and OS Version**
        > Provide the data here
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Do this.
        > 2. Do that.
    * **Observed behavior**
        > Provide the data here
    * **Expected behavior** (if known)
        > Provide the data here
    * **Evidence** (if available)
        > Attach logs (device/network), mini debug builds (source code preferably), stack traces, screenshots / screen recordings, etc.

**Comment by chauduyphanvu** [comment]
@GITHUB243884919, I checked the logs and it looks like the issue is implementation-specific (not adapter- or SDK- specific). Could you email support@mopub.com with all the details so we can help you? Thank you.

Vu Chau
MoPub SDK Team
