### ISSUE TITLE
[Android] AppLovin rewarded video adapter not recognizing valid `sdk` instance and fails

### ISSUE THREAD

**Issue by chauduyphanvu** [mopub/mopub-android-mediation#183]
1. **What is the issue?**
    > AppLovin rewarded video adapter throws an exception for invalid SDK key even if the key is defined.

2. **Fill in the below template as detailed as possible:**
    * **Ad Format**
        > Rewarded Video only (other adapters from Applovin work fine)
    * **Platform**
        > Android
    * **MoPub SDK Version**
        > N/A
    * **Mediation SDK Name & Version**
        > AppLovin 9.7.2.
    * **Mediation Adapter Version**
        > AppLovin 9.7.2.0 adapters
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > b28c982f77dd4c68a9e36ab7a1a87c1a
    * **Device model and OS Version**
        > N/A (any Android phone)
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Pass in the SDK Key at MoPub's initialization time using the MoPub Android sample app:

        ```java
        Map<String, String> applovinConfig = new HashMap<>();
        applovinConfig.put("sdk_key", "g9p0buIGwmV205uzWu93fLFLsxAwz_ve9hflay_UiVXiaQf5Iq8yAOI0JTwHSqxcVaL4XLZEs5yQVcWpRelb21");

        final SdkConfiguration.Builder configBuilder = new SdkConfiguration.Builder(
                "b195f8dd8ded45fe847ad89ed1d016da");
        configBuilder.withLogLevel(DEBUG);
        configBuilder.withMediatedNetworkConfiguration(AppLovinAdapterConfiguration.class.getName(), applovinConfig);
       ```

        > 2. Make an ad request for rewarded video using the ad unit ID given above. 

    * **Observed behavior**
        > Exception stack trace: https://gist.github.com/chauduyphanvu/081c679f679269350afce567aa4cf374.

    * **Expected behavior** (if known)
        > There should be no exception and the ad request should succeed because the SDK key is there. Another way is to hard-code the SDK key string [on this line](https://github.com/mopub/mopub-android-mediation/blob/master/AppLovin/src/main/java/com/mopub/mobileads/AppLovinRewardedVideo.java#L349) and it is also failing while it should not. This does not happen with other AppLovin adapter classes. I noticed that if I replace [this line](https://github.com/mopub/mopub-android-mediation/blob/master/AppLovin/src/main/java/com/mopub/mobileads/AppLovinRewardedVideo.java#L369) with `incent = AppLovinIncentivizedInterstitial.create(zoneId, sdk);` (i.e. the one below it), it will work because the `sdk` instance has the SDK key returned from [this line](https://github.com/mopub/mopub-android-mediation/blob/master/AppLovin/src/main/java/com/mopub/mobileads/AppLovinRewardedVideo.java#L353).

    * **Evidence** (if available)
        > Above

**Comment by chauduyphanvu** [comment]
@thomasmso, could you take a look at this one? Let me know if you need more details. The use case is we also want to support publishers passing in the SDK Key through MoPub at initialization time (in addition to inputting it into the Manifest). At the ad request time, all non-rewarded adapters can read the key and make ad requests successfully. The rewarded adapter chokes because it's using the other `AppLovinIncentivizedInterstitial.create()` call that doesn't accept an `sdk` (which has the SDK Key).

**Comment by thomasmso** [comment]
Hey - we'll just need to update [this](https://github.com/mopub/mopub-android-mediation/blob/master/AppLovin/src/main/java/com/mopub/mobileads/AppLovinRewardedVideo.java#L369) line to

```
incent = AppLovinIncentivizedInterstitial.create(sdk);
```

The way that line works, it'll check the SDK key in the Android Manifest (which may not exist in this new world, and crash).

PR here: https://github.com/mopub/mopub-android-mediation/pull/184

**Comment by chauduyphanvu** [comment]
Thanks for the quick action! We'll incorporate the fix from that PR into a release we'll make.
