### ISSUE TITLE
Unity Adapter not Initializing

### ISSUE THREAD

**Issue by CWftw** [mopub/mopub-android-mediation#188]
Hi,

I am having an issue getting Unity Ads to display in my Android application. I followed the documentation here: https://developers.mopub.com/publishers/mediation/networks/unityads/

These are the versions I am using:
```
api('com.mopub:mopub-sdk:5.8.0@aar') {
    transitive = true
}

// Unity Ads
api 'com.unity3d.ads:unity-ads:3.2.0'
api 'com.mopub.mediation:unityads:3.2.0.0'
```

When MoPub initializes I get the following logs:

```
[com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log - Initializing com.mopub.mobileads.UnityAdsAdapterConfiguration version 3.2.0.0 with network sdk version 3.2.0 and with params {}

[com.mopub.mobileads.UnityAdsAdapterConfiguration][initializeNetwork] Adapter UnityAdsAdapterConfiguration Log - Unity Ads initialization not started. Context is not an Activity. Note that initialization on the first app launch is a no-op. 

[com.mopub.common.AdapterConfigurationManager][onNetworkInitializationFinished] SDK Log - class com.mopub.mobileads.UnityAdsAdapterConfiguration initialized with error code Native Network or Custom Event adapter was configured incorrectly.
```

I was originally calling MoPub.initializeSdk() with an application context, but using an activity as the context does not fix this issue. See the error below:

https://github.com/mopub/mopub-android-mediation/blob/65ed8df2975d75e55f29366b8b6d68b5f3ec8f7c/UnityAds/src/main/java/com/mopub/mobileads/UnityAdsAdapterConfiguration.java#L76-L77

**Comment by hmertkahraman** [comment]
Hi @CWftw,

Thanks for reaching out on this to us. To have a better understanding of the topic, may I ask you if you're only integrating Unity Ads, or are there other certified ad networks in your project too; and if so, are they working properly, and only Unity Ads is not working?

Seems like the context you're passing has some issues. The main method for initializing MoPub SDK is: `MoPub.initializeSdk` which has the Context as the first input parameter. You mention passing in app and activity contexts. Activity context _should_ ideally work. What context are you passing into it, can you please provide more info on this with code snippets and details?

Thanks,
MoPub Team

**Comment by thetechguy10** [comment]
I am also having this error also with the ironsource sdk.

**Comment by hmertkahraman** [comment]
Hi @thetechguy10 ,

Thanks again for reaching out. You might see this on several networks in addition to Unity Ads and ironSource, which is fine (again per the explanation in the above comment).

As soon as you can show ads properly for these networks, and observe lazy initializations on the logs, this is expected behavior.

Please let us know if you have any additional questions.

Thanks,
Mert

**Comment by CWftw** [comment]
Hi @hmertkahraman ,

I wouldn't have made the issue if Unity ads were working, they were not. Your mention of lazy initialization of the adapter led me to the solution which was to pass an activity context to the constructor of MoPubView().

~ Colin
