### ISSUE TITLE
RewardVideo count not load and get nothing callback.

### ISSUE THREAD

**Issue by YangKunCheng** [mopub/mopub-android-mediation#209]
Mopub Init code:

SdkConfiguration sdkConfiguration = new SdkConfiguration.Builder(model.getPlatformAppId())
                .withLogLevel(BuildConfig.DEBUG?MoPubLog.LogLevel.DEBUG:MoPubLog.LogLevel.NONE)
                .withLegitimateInterestAllowed(false)
                .build();

MoPub.initializeSdk(context, sdkConfiguration, sInstance.initSdkListener());

We load RewardedVideo after MoPub initialed but VideoListener count not get any callBack.

RewardedVideo load code:
MoPubRewardedVideos.setRewardedVideoListener(sVideoListener);
MoPubRewardedVideos.loadRewardedVideo(mAdModel.getPid());

**Comment by YangKunCheng** [comment]
Get some log below:
SDK Log - MoPub rewarded ad was not initialized. You must call MoPub.initializeRewardedVideo() before loading 

But initializeRewardedVideo() is a private method

**Comment by chauduyphanvu** [comment]
@YangKunCheng, please make sure to initialize the MoPub SDK with an `Activity Context` before you request rewarded videos. 

> SDK Log - MoPub rewarded ad was not initialized. You must call MoPub.initializeRewardedVideo() before loading

> But initializeRewardedVideo() is a private method

The correct call is `MoPub.initializeSdk()` ([see here](https://github.com/mopub/mopub-android-sdk/blob/3652a2edbbc72868cf07b72204ce18bc340b3511/mopub-sample/src/main/java/com/mopub/simpleadsdemo/MoPubSampleActivity.java#L137) for usage example).

Vu Chau
MoPub Support Team
