### ISSUE TITLE
UnityAds banner failing - unable to serve ad due to invalid internal state

### ISSUE THREAD

**Issue by npace** [mopub/mopub-android-mediation#218]
1. **What is the issue?**
On our Android app, loading a UnityAds banner using UnityAds SDK 3.4.0 with MoPub SDK 5.8.0 and mediation for Unity 3.4.0.0 does not work. Loading the same banner directly through UnityAds 3.4.0 works.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
Banner
    * **Platform** (*Android, iOS, Unity*)
Android
    * **MoPub SDK Version**
5.8.0
    * **Mediation SDK Name & Version**
UnityAds 3.4.0.
    * **Mediation Adapter Version**
3.4.0.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
78bd3c5446bd4e2b93bf5f0b7d8a86d2
    * **Device model and OS Version**
Android 8.0 on Emulator 29.2.1-5889189
    * **Steps to reproduce the issue** (include integration steps if not standard)
        Initialise the MoPub Android SDK with an ad zone that only uses Unity mediation.
    * **Observed behavior**
        The device's LogCat displays some errors and reports no fill; the banner does not show up.
    * **Expected behavior** (if known)
        The banner should load. Loading it using UnityAds 3.4.0 and following Unity's documentation works.
    * **Evidence** (if available)
        [mopub-unity-log.txt](https://github.com/mopub/mopub-android-mediation/files/4025469/mopub-unity-log.txt)
        We use a ton of mediations so the log is a bit cluttered. I don't know whether that's related to the issue.
        The Unity game ID is `3405205` and the placement ID is `JMO_A_banner_test`.
        I believe the most important lines in the log are around `I/MoPub: [com.mopub.mobileads.AdViewController][loadFailUrl] Ad failed to load: (10,000) Unable to serve ad due to invalid internal state.`
        I noticed that loading the banner through Unity takes at least 30 seconds, could this be related to your invalid internal state?
        I also tried enabling/disabling Unity's test mode for that ad, but it made no difference.
        The code I used to load the ad is:
```
        val adZone = "78bd3c5446bd4e2b93bf5f0b7d8a86d2" // ad zone with just one Unity line item
        val config = SdkConfiguration.Builder(adZone)
                .withLogLevel(MoPubLog.LogLevel.DEBUG)
                .build()
        MoPub.initializeSdk(this, config) {
            moPubView = MoPubView(this).also {
                it.adUnitId = adZone
                it.testing = true
                it.loadAd()
            }
            rootlayout.addView(moPubView)
        }
```

**Comment by dravyan** [comment]
@npace, thank you for reporting this. In order to use the latest version of UntiyAds adapter 3.4.0.0, you need to be on at least 5.9.0 or higher version of MoPub SDK. Please update to SDK 5.10.0 and test it. Let us know if you still run into any issues after updating the SDK.

Thanks,
Dravya Nataraj
MoPub SDK Team

**Comment by npace** [comment]
@dravyan thanks for the quick response!
I updated MoPub SDK to 5.10.0 and ran some more tests on the emulator and on a physical device - Huawei P20 Pro @ Android 9.1.0.

The "invalid internal state" error log is gone, but the mediation is still unable to load a banner. The UnityAds SDK itself is still able to load the same banner.
Here are logs from loading the banner both through MoPub mediation and directly through UnityAds:
[mopub-unity-log-mediation.txt](https://github.com/mopub/mopub-android-mediation/files/4029449/mopub-unity-log-mediation.txt)
[mopub-unity-log-direct.txt](https://github.com/mopub/mopub-android-mediation/files/4029451/mopub-unity-log-direct.txt)

This could be a race condition. I saw the banner through MoPub once out of ~20 attempts.

What should I do next?

**Comment by dravyan** [comment]
@npace, could you share the banner adunits you are using so we can try to reproduce the behavior?

Thanks,
Dravya

**Comment by npace** [comment]
Sure, @dravyan 

The MoPub ad unit we've set up for this is `78bd3c5446bd4e2b93bf5f0b7d8a86d2` - it just contains one Unity line item, using a valid configuration for our app.

**Comment by dravyan** [comment]
@npace, I tried test with MoPub sample app and I am able to fetch the ad for the adunit.

 `I/MoPub: [com.mopub.mobileads.UnityBanner][onBannerLoaded][JMO_A_banner_test] Adapter UnityBanner successfully loaded ad
2020-01-13 21:14:44.233 3518-3518/com.mopub.mobileads.testing I/MoPub: [com.mopub.mobileads.UnityBanner][onBannerLoaded][JMO_A_banner_test] Adapter UnityBanner attempting to show ad
2020-01-13 21:14:44.233 3518-3518/com.mopub.mobileads.testing I/MoPub: [com.mopub.mobileads.UnityBanner][onBannerLoaded][JMO_A_banner_test] Adapter UnityBanner successfully showed ad
2020-01-13 21:14:44.233 3518-3518/com.mopub.mobileads.testing I/MoPub: [com.mopub.mobileads.CustomEventBannerAdapter][onBannerLoaded] SDK Log - onBannerLoaded() success. Attempting to show.
2020-01-13 21:14:44.233 3518-3518/com.mopub.mobileads.testing I/MoPub: [com.mopub.mobileads.MoPubView][adLoaded] Ad loaded
2020-01-13 21:14:44.235 3518-3518/com.mopub.mobileads.testing I/MoPub: [com.mopub.mobileads.MoPubView][setAdContentView] Attempting to show ad
2020-01-13 21:14:44.235 3518-3518/com.mopub.mobileads.testing I/MoPub: [com.mopub.mobileads.MoPubView][setAdContentView] Ad shown
2020-01-13 21:14:44.235 3518-3518/com.mopub.mobileads.testing I/MoPub: [com.mopub.mobileads.MoPubView][trackNativeImpression] Ad Log - Tracking impression. MoPubView internal.
2020-01-13 21:14:44.238 3518-3518/com.mopub.mobileads.testing I/MoPub: [com.mopub.mobileads.testing.MoPubSampleActivity$4][onImpression] SDK Log - impression for adUnitId= 78bd3c5446bd4e2b93bf5f0b7d8a86d2`

If the ad fails to load, then the UnityAds has no fill to serve as the below error is from the Unity Ads SDK.
`2020-01-13 21:18:59.999 3518-4545/com.mopub.mobileads.testing E/UnityAds: com.unity3d.services.core.api.Sdk.logError() (line:70) :: No fill for placement JMO_A_banner_test`

Can you let us know if you have enabled Test mode on the Unity dashboard?. If so, can you turn off test mode and give it a try?

Thanks,
Dravya Nataraj
MoPub Team

**Comment by npace** [comment]
Hello again and thanks for the follow-up.

I tried testing the ad unit using the sample app and still got no fill. In the meantime, we noticed that unity line items are actually filling for our users in production.

This leads me to believe two things:
1. The MoPub SDK update from 5.8 to 5.10 somehow helped in production
2. There is something wrong with the devices I'm testing on.

Do you have any suggestions about why my devices might be getting no fill when loading Unity ads through mediation? This doesn't seem to be a problem for direct Unity ads or for other mediations through MoPub...

Either way, the "invalid internal state" error is gone, so we can close this issue.

**Comment by dravyan** [comment]
@npace, try disabling the test mode for the device you are testing on for Unity Ads. Thank you for confirming that the `Invalid internal state` error is resolved.

Thanks,
MoPub Team
