### ISSUE TITLE
Apk Can not pass Google Play

### ISSUE THREAD

**Issue by GITHUB243884919** [mopub/mopub-android-mediation#219]
1. **What is the issue?**
    > Apk Can not pass Google Play.
      Our app apk（Unity-Android） was uploaded to Google Play, then it tell us the app use android.permission.ACCESS_COARSE_LOCATION. We checked our Unity project, we can not find
this. but we find it in the mopub-sdk-base.aar. In the file AndroidManifest.xml of the mopub-sdk-base.aar. it show that 
    uses-permission android:name="android.permission.INTERNET" 
    uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"
    uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"
Then we removed android.permission.ACCESS_COARSE_LOCATION and builded app again.
Now your app already in the Google Play's app store.
![GP](https://user-images.githubusercontent.com/17681628/71972547-d2dd3280-3247-11ea-99e2-25fc3e9fbba7.png)

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ ] I searched https://developers.mopub.com/ and found no answer.
    - [ ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Provide the data here
    * **Platform** (*Android, iOS, Unity*)
        >Android,  Unity
    * **MoPub SDK Version**
        > 5.10.1
    * **Mediation SDK Name & Version**
        > Provide the data here
    * **Mediation Adapter Version**
        > Provide the data here
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Provide the data here
    * **Device model and OS Version**
        > Provide the data here
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Do this.
        > 2. Do that.
    * **Observed behavior**
        > Provide the data here
    * **Expected behavior** (if known)
        > Provide the data here
    * **Evidence** (if available)
        > Attach logs (device/network), mini debug builds (source code preferably), stack traces, screenshots / screen recordings, etc.

**Comment by hmertkahraman** [comment]
Hi @GITHUB243884919 ,

Thanks for reaching out to us about this. 

You can refer to [this section](https://developers.mopub.com/publishers/android/integrate/#step-3-update-your-android-manifest) of our documentation for the explanation, and follow the guidance.

Please let us know if you have any additional questions.

Thanks,
MoPub Team

**Comment by GITHUB243884919** [comment]
> Hi @GITHUB243884919 ,
> 
> Thanks for reaching out to us about this.
> 
> You can refer to [this section](https://developers.mopub.com/publishers/android/integrate/#step-3-update-your-android-manifest) of our documentation for the explanation, and follow the guidance.
> 
> Please let us know if you have any additional questions.
> 
> Thanks,
> MoPub Team

Thanks for you reply.
I made a test. I do not remove uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION from  AndroidManifest.xml of the mopub-sdk-base.aar. And I add <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" tools:node="remove" /> to our 
Unity project's AndroidManifest.xml.  and build again, the apk still show has ACCESS_COARSE_LOCATION。 Our mopub sdk version is 5.10.0

**Comment by hmertkahraman** [comment]
Hi @GITHUB243884919 ,

You mentioned that Google Play store rejected your submission as it uses `ACCESS_COARSE_LOCATION` permission. So we understand you want to remove it completely.

In order to remove it, unlike you mention, could you please remove ACCESS_COARSE_LOCATION permission entry from your AndroidManifest at Unity level? So that when you export to Android, it will not have the permission.

Please let us know if this doesn't work for you.

Thanks,
MoPub Team

**Comment by GITHUB243884919** [comment]
> Hi @GITHUB243884919 ,
> 
> You mentioned that Google Play store rejected your submission as it uses `ACCESS_COARSE_LOCATION` permission. So we understand you want to remove it completely.
> 
> In order to remove it, unlike you mention, could you please remove ACCESS_COARSE_LOCATION permission entry from your AndroidManifest at Unity level? So that when you export to Android, it will not have the permission.
> 
> Please let us know if this doesn't work for you.
> 
> Thanks,
> MoPub Team

thank you~ I see. I build unity Android app without Android Studio，I build it by Unity's  Gradle Model. 
I remove android.permission.ACCESS_COARSE_LOCATION from the file AndroidManifest.xml of the mopub-sdk-base.aar.  every things are ok!
Thank you again~
