### ISSUE TITLE
admob mediation native render bug

### ISSUE THREAD

**Issue by Kyba1985** [mopub/mopub-android-mediation#22]
Hi , i'm using mopub native render in adapter of recyclerview.

After the first admob native ad is rendered when the app must render the second one the native ad is not shown but is shown only the adv indicator of google.

I think the problem is in the method removeGoogleNativeAdView of GooglePlayServicesAdRenderer.
After a few session of debugger with layout inspector i noticed that this method removes the wrong view from hierarchy to be used on the next bind. The google native app install has a view before che cardview

![schermata 2018-04-18 alle 12 19 42](https://user-images.githubusercontent.com/13661071/38927401-f11446f4-4305-11e8-90e7-10b354f4b14a.png)

where is rendered the adv and when this method get the view with:

View actualNativeView = ((ViewGroup) adView).getChildAt(0);

it takes the wrong view.

I fixed it with:
View actualNativeView = ((ViewGroup) adView).getChildAt(1);

(update: i cannot test the native content at this time so i can't know the exactly view hierarchy when content native must be show so i change with this:

`                View actualNativeView = null;
                for (int i = 0; i < ((ViewGroup) adView).getChildCount(); i++) {
                    View viewChild = ((ViewGroup) adView).getChildAt(i);
                    if (viewChild instanceof CardView) {
                        actualNativeView = viewChild;
                        break;
                    }
                }
`

)

Check if is a real bug in your class.
i'm using the playservices version 15.0.0

**Comment by chauduyphanvu1** [comment]
Confirming receipt. Investigating.

**Comment by chauduyphanvu1** [comment]
@rampara Can you take a look and help with this? I quickly checked out the suggested fix and can confirm the issue went away. Was there a recent change in the Mobile Ads SDK that caused this issue? The existing adapter code worked fine previously.
