### ISSUE TITLE
Admob mediation - unable to link account

### ISSUE THREAD

**Issue by CodeMaschineX** [mopub/mopub-android-mediation#249]
Same error as described on this link.
https://github.com/mopub/mopub-android-mediation/issues/211

**Comment by chauduyphanvu** [comment]
@CodeMaschineX, thanks for letting us know! I've informed the rest of the team and will provide an update.

Vu Chau
MoPub Tea,

**Comment by chauduyphanvu** [comment]
@CodeMaschineX, this issue has now been fixed. Let us know if you need anything else!

**Comment by JCSHoosier** [comment]
@chauduyphanvu without opening up a new issue, this appears to be happening for me today as well.

**Comment by ingsaurabh** [comment]
I am also facing the same issue, apart from this, I am also facing issue while using **Unity** mediation, when I enter API key in **Network** tab it says **Invalid Credentials**

**Comment by chauduyphanvu** [comment]
@JCSHoosier @ingsaurabh, thanks for letting us know. We're looking into these issues right now. Stay tuned!

**Comment by chauduyphanvu** [comment]
This issue has now been fixed. Please retry!

**Comment by ingsaurabh** [comment]
Unity is fixed while admob not completely, now in Network tab under reporting status it says "error : Network reporting has failed. Please go to Network Settings and update your credentials."

**Comment by chauduyphanvu** [comment]
@ingsaurabh, thanks for letting us know. Taking a look now.

**Comment by chauduyphanvu** [comment]
This should have been fixed now. Let us know if you continue seeing the error!

**Comment by ingsaurabh** [comment]
Nope still same error

**Comment by chauduyphanvu** [comment]
@Mouadabdelghafouraitali - are you still seeing this issue? It worked fine when I've tried it just now.
