### ISSUE TITLE
Failed resolution of Lcom/chartboost/sdk/ChartboostDelegate

### ISSUE THREAD

**Issue by benjisora** [mopub/mopub-android-mediation#26]
Hi,
My Android app crashes if I enable Chartboost interstitials from the MoPub console. I've been using the new mediation integration tool, and it's working fine when I receive an ad from AdMob.

Here is how I import the adapters : 
```groovy
    compile('com.mopub:mopub-sdk-banner:4.20.0@aar') {
        transitive = true
    }
    compile('com.mopub:mopub-sdk-interstitial:4.20.0@aar') {
        transitive = true
    }
    compile('com.mopub:mopub-sdk-native-video:4.20.0@aar') {
        transitive = true
    }

    // Chartboost
    compile 'com.mopub.mediation:chartboost:7.1.0.0'
```
Here is the error : 
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/chartboost/sdk/ChartboostDelegate;
        at com.mopub.mobileads.ChartboostShared.getDelegate(ChartboostShared.java:90)
        at com.mopub.mobileads.ChartboostInterstitial.loadInterstitial(ChartboostInterstitial.java:54)
        at com.mopub.mobileads.CustomEventInterstitialAdapter.loadInterstitial(CustomEventInterstitialAdapter.java:85)
        at com.mopub.mobileads.MoPubInterstitial$MoPubInterstitialView.loadCustomEvent(MoPubInterstitial.java:462)
        at com.mopub.mobileads.AdViewController.loadCustomEvent(AdViewController.java:191)
        at com.mopub.mobileads.AdViewController.onAdLoadSuccess(AdViewController.java:150)
        at com.mopub.mobileads.AdViewController$1.onSuccess(AdViewController.java:120)
        at com.mopub.network.AdRequest.deliverResponse(AdRequest.java:368)
        at com.mopub.network.AdRequest.deliverResponse(AdRequest.java:47)
        at com.mopub.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Do you have any idea how to fix this ?

Thank you,

**Comment by chauduyphanvu1** [comment]
Hello, the `ChartboostDelegate` class resides within the Chartboost SDK, and as far as I know Chartboost does not have a JCenter package that our integration tool can link to, so it seems like only the adapter and not their SDK is getting imported. 

Did you [download their SDK Jar](https://answers.chartboost.com/en-us/articles/download) separately and import that to your app project?

**Comment by benjisora** [comment]
I did not, the goal was to get rid of all the specific network SDK jars and use MopubInterstitial (+ the imported adapters from the mediation tools). We were trying to stay as independent from the specific networks used with MoPub.

So I guess there is no other choice than to import the jar to use Chartboost with MoPub ?

**Comment by benjisora** [comment]
Will I be able to use the imported adapter for Chartboost by just importing the SDK jar into the project, or do I have to manually handle everything ?

**Comment by chauduyphanvu1** [comment]
> Will I be able to use the imported adapter for Chartboost by just importing the SDK jar into the project, or do I have to manually handle everything ?

Yes, the adapter works with the Chartboost SDK Jar once you have imported _both_.

The new `NoClassDefFoundError` is about a file in the adapter. Once you've synced Gradle, check to make sure the file `ChartboostShared` is located in your app project. You might also want to add a rule to Proguard (if you are using Proguard) to keep all Chartboost*.java files (or work backwards by reverse-engineering the APK to see if they are all there). Here's how it looks in my setup when I imported the adapter: https://s3.us-east-2.amazonaws.com/chauduyphanvu/ChartboostShared.png.

**Comment by benjisora** [comment]
This new `NoClassDefFoundError` appears even though I do see the `ChartboostShared` imported class in the project, it looks just the same as on the screenshot you sent, and the imported class contains the inner class that is said not to be found...

I'll see about proguard rules when I can update my project, thank you for your time so far

**Comment by chauduyphanvu1** [comment]
Hm that's strange. Are you multidex-ing by any chance and having it configured properly? What's your minSdkVersion? If 20 or below, try this: https://developer.android.com/studio/build/multidex#mdex-gradle.

**Comment by benjisora** [comment]
I have multidexing properly configured, and minSDK is 16. Here's what I included in the `build.gradle` : 
```
    compile('com.mopub:mopub-sdk-banner:4.20.0@aar') {
        transitive = true
    }
    compile('com.mopub:mopub-sdk-interstitial:4.20.0@aar') {
        transitive = true
    }
    compile('com.mopub:mopub-sdk-native-video:4.20.0@aar') {
        transitive = true
    }
    // Chartboost
    compile 'com.mopub.mediation:chartboost:7.1.0.0'
```
Here's what I see from the `Project` tab, when looking at the imported mediation adapter lib:
![chartboost_mediation_adapter](https://user-images.githubusercontent.com/15685057/39998696-3190b9b6-5787-11e8-8323-97fb030e8288.png)

The error I am getting is this one : 
```
java.lang.NoClassDefFoundError: com.mopub.mobileads.ChartboostShared$ChartboostSingletonDelegate
        at com.mopub.mobileads.ChartboostShared.<clinit>(ChartboostShared.java:33)
        at com.mopub.mobileads.ChartboostInterstitial.loadInterstitial(ChartboostInterstitial.java:54)
        at com.mopub.mobileads.CustomEventInterstitialAdapter.loadInterstitial(CustomEventInterstitialAdapter.java:85)
        at com.mopub.mobileads.MoPubInterstitial$MoPubInterstitialView.loadCustomEvent(MoPubInterstitial.java:462)
        at com.mopub.mobileads.AdViewController.loadCustomEvent(AdViewController.java:191)
        at com.mopub.mobileads.AdViewController.onAdLoadSuccess(AdViewController.java:150)
        at com.mopub.mobileads.AdViewController$1.onSuccess(AdViewController.java:120)
        at com.mopub.network.AdRequest.deliverResponse(AdRequest.java:368)
        at com.mopub.network.AdRequest.deliverResponse(AdRequest.java:47)
        at com.mopub.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5728)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```
But inside the imported `ChartboostShared` class, I do see the inner `ChartboostSingletonDelegate` : 
```
public static class ChartboostSingletonDelegate extends ChartboostDelegate implements CustomEventRewardedVideoListener {
    ...
```

I'm trying to include the Chartboost SDK, but with no success so far. I downloaded the `.jar` file, and placed it in a `libs` folder. My `build.gradle` is compiling `fileTree(dir: 'libs', include: ['*.jar'])`, so this should be it, right ?

**Comment by chauduyphanvu1** [comment]
Make sure to right-click on the Chartboost `jar` in Android Studio, and select "Add as library" for Gradle. Once done, you should see a line in your `build.gradle` that says `implementation files('../libs/chartboost-7.2.0.jar')`.

I'm still curious how that still causes one file in your Chartboost adapter binaries not to be found, though. Let me know whether adding the Chartboost SDK fixes this.

**Comment by benjisora** [comment]
I did try this as well, in my `build.gradle` I now have the `compile files('.../libs/chartboost.jar')` line, but it does not fix the error from appearing. Same `NoClassDefFoundError`, same `ChartboostShared$ChartboostSingletonDelegate` !

It seems to appear on the `ChartboostInterstitial.loadInterstitial(...)` method, when it reaches this line : 
```java
if (ChartboostShared.getDelegate().hasInterstitialLocation(this.mLocation) && ChartboostShared.getDelegate().getInterstitialListener(this.mLocation) != interstitialListener) {
```
Reading from the `ChartboostShared` imported class, the `ChartboostShared.getDelegate()` should normally be returning an instance of the `ChartboostShared.ChartboostSingletonDelegate` inner class, but it crashes there due to this inner class not being found for some reason.

**Comment by chauduyphanvu1** [comment]
@benjisora, I'm attaching a mini working project with just MoPub and Chartboost that you can reference: https://s3.us-east-2.amazonaws.com/chauduyphanvu/MoPub_Chartboost.zip. My recommendation is to start from an empty project, and gradually add MoPub, Chartboost, and the adapters, and run that with a Chartboost-enabled ad unit ID.

**Comment by benjisora** [comment]
I think I found where the issue comes from. When using your mini project only, with my adUnit (chartboost enabled), I get no ads, and a toast pops up without encountering the issue described before (I suppose this means something console-wise is not properly configured, but that's another topic).

Then I simply add AdMob to the project, so I end up with : 


**build.gradle:**
   ```groovy
   implementation 'com.google.android.gms:play-services-ads:15.0.1'
    implementation('com.mopub:mopub-sdk:5.0.0@aar') {
        transitive = true
    }

    implementation 'com.mopub.mediation:chartboost:7.2.0.0'
    implementation files('src/main/java/mopub/com/libs/chartboost-7.2.0.jar')

    // added line, for AdMob.
    implementation 'com.mopub.mediation:admob:15.0.0.1'
   ```

**AndroidManifest:**
   ```xml
   <manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <application ... >
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <!-- All ad formats -->
        <activity android:name="com.mopub.common.MoPubBrowser" android:configChanges="keyboardHidden|orientation|screenSize"/>

        <!-- Interstitials -->
        <activity android:name="com.mopub.mobileads.MoPubActivity" android:configChanges="keyboardHidden|orientation|screenSize"/>
        <activity android:name="com.mopub.mobileads.MraidActivity" android:configChanges="keyboardHidden|orientation|screenSize"/>

        <!-- Rewarded Video and Rewarded Playables (not used)-->
        <activity android:name="com.mopub.mobileads.RewardedMraidActivity" android:configChanges="keyboardHidden|orientation|screenSize"/>
        <activity android:name="com.mopub.mobileads.MraidVideoPlayerActivity" android:configChanges="keyboardHidden|orientation|screenSize"/>

        <activity
            android:name="com.chartboost.sdk.CBImpressionActivity"
            android:configChanges="keyboardHidden|orientation|screenSize"
            android:excludeFromRecents="true"
            android:hardwareAccelerated="true"
            android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />

        <!-- Added those two blocks for AdMob -->
        <meta-data android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

        <activity android:name="com.google.android.gms.ads.AdActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"/>
    </application>
   </manifest>
   ```

When I run the project, while still keeping only Chartboost enabled from the console, this time it crashes with the `NoClassDefFoundError ChartboostShared$ChartboostSingletonDelegate` error.

it also keeps telling me via Toast that the configuration is not complete, and to check the logs and Manifest... Any clues ?

Thank you for your time 😄

**Comment by chauduyphanvu1** [comment]
Can you send over your project with the ad unit ID that consistently triggers that crash?

**Comment by benjisora** [comment]
Here you go. I commented AdMob's compile line, and placed my adUnit.
[MoPub_Chartboost.zip](https://github.com/mopub/mopub-android-mediation/files/2016991/MoPub_Chartboost.zip)

**Comment by chauduyphanvu1** [comment]
I can't repro the crash (the adapter is already imported):

<img width="1440" alt="screen shot 2018-05-18 at 10 47 21 am" src="https://user-images.githubusercontent.com/25616035/40241582-5e927b98-5a89-11e8-947a-570e9395388c.png">

**Comment by benjisora** [comment]
After a few tries, I can't seem to make the app crash again, though I still don't get any ad for Chartboost with my adUnit, even though you seemed to get one yourself on the exact same project. I keep getting these lines : 
```java
D/MoPub: Loading url: ...
D/MoPub: Loading custom event interstitial adapter.
D/MoPub: Attempting to invoke custom event: com.mopub.mobileads.ChartboostInterstitial
D/MoPub: Chartboost interstitial ad failed to load.Error: NO_AD_FOUND
V/MoPub: MoPubErrorCode: Third-party network failed to provide an ad.
D/MoPub: Loading failover url: ...
    Loading url: ...
I/MoPub: Ad failed to load.
```
I tried several Android versions, via emulators and real devices, and I successfully get ads from AdMob when I enable it in the console. I don't understand how you could have gotten an ad once while I can't seem to receive any from Chartboost...

**Comment by chauduyphanvu1** [comment]
This is somewhat a different issue now - could you reach out to support@mopub.com for additional assistance? Thanks!

**Comment by ber4444** [comment]
@chauduyphanvu1 do you accept PRs for this repo? We (from Chartboost) could submit a sample that shows how to integrate. Your online docs are outdated at several places so it would be useful to have a sample in general, for other ad networks as well.

**Comment by chauduyphanvu1** [comment]
@ber4444, thanks for getting in touch. If PRs are for non-adapter purposes, feel free to email our mediation alias with the doc page/section you wish to see updated to reflect Chartboost's integration best practices. In the future we intend to showcase such app, though!

**Comment by kapupararavi** [comment]
Add chartboost.jar file into your plugin folder. This will fix your problem.
*You can find this file when you download Android SDK.
