### ISSUE TITLE
Facebook Mediation Crash

### ISSUE THREAD

**Issue by ingsaurabh** [mopub/mopub-android-mediation#273]
1. **What is the issue?**
    > App crash in production 

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x ] I searched https://developers.mopub.com/ and found no answer.
    - [ x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Banner, Interstitial
    * **Platform** (*Android, iOS, Unity*)
        > Android
    * **MoPub SDK Version**
        > 5.13.1
    * **Mediation SDK Name & Version**
        > 'com.facebook.android:audience-network-sdk:5.10.0'
    'com.mopub.mediation:facebookaudiencenetwork:5.10.0.1'
    * **Mediation Adapter Version**
        > 5.10.0.1
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Provide the data here
    * **Device model and OS Version**
        > Almost all phones below 5
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > Its in production, couldn't produce it with local testing
    * **Observed behavior**
        > Provide the data here
    * **Expected behavior** (if known)
        > Provide the data here
    * **Evidence** (if available)
        > Fatal Exception: java.lang.NoClassDefFoundError
com.facebook.ads.redexgen.X.8O
com.facebook.ads.redexgen.X.XF.A00 (XF.java:57034)
com.facebook.ads.redexgen.X.XF.<init> (XF.java:57030)
com.facebook.ads.redexgen.X.XC.A01 (XC.java:56918)
com.facebook.ads.redexgen.X.Xb.A01 (Xb.java:57328)
com.facebook.ads.redexgen.X.Xb.A0B (Xb.java:57360)
com.facebook.ads.redexgen.X.5p.getBidderToken (5p.java:13647)
com.facebook.ads.BidderTokenProvider.getBidderToken (BidderTokenProvider.java:28)
com.mopub.mobileads.FacebookAdapterConfiguration$1.run (FacebookAdapterConfiguration.java:123)
java.lang.Thread.run (Thread.java:818)

**Comment by LongLostPenPal** [comment]
i have same [issues](https://github.com/mopub/mopub-unity-sdk/issues/132#issuecomment-656630805)

**Comment by chauduyphanvu** [comment]
@ingsaurabh, thanks for letting us know! We are aware of this crash and have been working with the Facebook Audience Network team on resolving it.

In the meantime, please downgrade the Facebook SDK version to 5.9.x, which does not trigger this crash. 

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
**Update**:

You can downgrade the Facebook Audience Network SDK version integrated in the app. 5.9.1 is the latest stable version. You do not need to downgrade to MoPub 5.12.0.

**Comment by chauduyphanvu** [comment]
Fixed in https://github.com/mopub/mopub-android-mediation/commit/9a7ceb944b421096e6bfa3d9f4af6a082073f3be. Let us know if you continue seeing the crash!

**Comment by ingsaurabh** [comment]
**Note: For expired interstitials, publishers need to call `destroy()` before requesting a new ad.**, is this doable in mediation?

**Comment by chauduyphanvu** [comment]
> **Note: For expired interstitials, publishers need to call `destroy()` before requesting a new ad.**, is this doable in mediation?

Yes, you can call it on your `MoPubInterstitial` instance.

**Comment by ingsaurabh** [comment]
Something like this

> public void onInterstitialFailed(MoPubInterstitial interstitial, MoPubErrorCode errorCode) {
                            Log.e(LOGTAG, "onInterstitialFailed " + errorCode);
                            if(errorCode == MoPubErrorCode.EXPIRED) {
                                moPubInterstitial.destroy();
                            }
                            moPubInterstitial.load();
                        }

**Comment by chauduyphanvu** [comment]
The adapter is sending `FULLSCREEN_SHOW_ERROR` ([code](https://github.com/mopub/mopub-android-mediation/blob/master/FacebookAudienceNetwork/src/main/java/com/mopub/mobileads/FacebookInterstitial.java#L74)) so that is the one you should check against. Additionally, we do not recommend immediately calling `load()` as soon as you receive `onInterstitialFailed()`, since you will be rate limited.
