### ISSUE TITLE
NullPointerException UnityBannerSize.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by ingsaurabh** [mopub/mopub-android-mediation#275]
1. **What is the issue?**
    > App crash in production

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ x] I searched https://developers.mopub.com/ and found no answer.
    - [x ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Banner
    * **Platform** (*Android, iOS, Unity*)
        > Android
    * **MoPub SDK Version**
        > 5.13.1
    * **Mediation SDK Name & Version**
        > 'com.unity3d.ads:unity-ads:3.4.6'
'com.mopub.mediation:unityads:3.4.6.0'
    * **Mediation Adapter Version**
        > 3.4.6.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Provide the data here
    * **Device model and OS Version**
        > Android 7, 8, 9 Gionee, Huawie, LGE, Oppo
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > Its in production, couldn't produce it with local testing
    * **Observed behavior**
        > Provide the data here
    * **Expected behavior** (if known)
        > Provide the data here
    * **Evidence** (if available)
        > Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'int com.unity3d.services.banners.UnityBannerSize.getWidth()' on a null object reference
com.unity3d.services.banners.bridge.BannerBridge.load (BannerBridge.java:16)
com.unity3d.services.banners.BannerView.bridgeLoad (BannerView.java:201)
com.unity3d.services.banners.BannerView.access$300 (BannerView.java:24)
com.unity3d.services.banners.BannerView$3.onSdkInitialized (BannerView.java:170)
com.unity3d.services.core.configuration.InitializationNotificationCenter$1.run (InitializationNotificationCenter.java:48)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6317)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:872)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:762)

**Comment by dravyan** [comment]
@ingsaurabh, thank you for reporting the issue. Could you share the adunit or steps to replicate the issue?. Is this a native Android app or built on Unity?

Thanks,
MoPub Team

**Comment by ingsaurabh** [comment]
Adunitt is 

> fb43585c7e1f4069b1ccefe9eacc01c8

Can't tell steps to replicate in local testing, it is reported in Firebase

**Comment by dravyan** [comment]
@ingsaurabh, thank you. The NPE is triggered by the Unity Ads SDK. We will see what we can do to take care of this.

Thanks,
MoPub Team

**Comment by hmertkahraman** [comment]
Hi @ingsaurabh ,

Were you able to observe the issue with the new adapters towards Unity Ads SDK version: 3.4.8 ? If not would you please be able to see if the update fixes the issue?

In addition, do you have any additional context on this issue that we can use as an insight? Any pattern on device / OS specs, or were any repro steps revealed in time?

Thanks,
Mert

**Comment by ingsaurabh** [comment]
I haven't tried new one, will let here know when we try

**Comment by hmertkahraman** [comment]
Thank you please let us know.

**Comment by hmertkahraman** [comment]
Hi @ingsaurabh ,

Could you please try 3.5.0.0 adapters for this and let us know of the results?

Thanks,
Mert

**Comment by ingsaurabh** [comment]
Hi, tested with 3.4.8, seems fixed, closing for now will update if needed
