### ISSUE TITLE
GooglePlayServicesAdRenderer does't show MediaContent

### ISSUE THREAD

**Issue by Antiglobalist** [mopub/mopub-android-mediation#281]
Hi, i am using GooglePlayServicesAdRenderer and there GooglePlayServicesNativeAd

My native ads can't show media content in MediaView

The problem is in class GooglePlayServicesNativeAd. There:
com.google.android.gms.ads.formats.NativeAdOptions.Builder optionsBuilder
optionsBuilder.setReturnUrlsForImageAssets(true);

I think here should be 
optionsBuilder.setReturnUrlsForImageAssets(false);

Coz if we set True we should use ImageView

In debug mode i changed property to false and Media content is showed

com.mopub:mopub-sdk:5.13.1
com.mopub.mediation:admob:19.3.0.0
com.google.android.gms:play-services-ads:19.3.0

**Comment by chauduyphanvu** [comment]
@Antiglobalist, thanks for letting us know! We are aware of this issue and have been in touch with Google to discuss a fix for it. Rest assured—impressions will continue to be tracked. 

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
@Antiglobalist, this issue has been addressed in https://github.com/mopub/mopub-android-mediation/commit/8ce94c5ec2389adf9408cc4c461e5f21977cc5c4. Let us know if you continue to see the issue.
