### ISSUE TITLE
java.lang.AbstractMethodError: abstract method "void com.mopub.mobileads.AdLifecycleListener$FullscreenInteractionListener.onAdDismissed()

### ISSUE THREAD

**Issue by fbrescia** [mopub/mopub-android-mediation#298]
1. **What is the issue?**
I'm getting the following crash report in App Center:
```
com.mopub.mobileads.ChartboostShared$ChartboostSingletonDelegate.didDismissInterstitial
ChartboostShared.java, line 341
java.lang.AbstractMethodError: abstract method "void com.mopub.mobileads.AdLifecycleListener$FullscreenInteractionListener.onAdDismissed()"
```

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Platform** (*Android, iOS, Unity*)
        Android, compiled with:
        - Gradle v5.6.4
        - Android Gradle plugin v3.6.4
        - Android SDK Build Tools v29.0.3
        - compileSdkVersion 29
        - targetSdkVersion 29
    * **MoPub SDK Version**
        v5.13.1 and v5.14.0
    * **Mediation SDK Name & Version**
        Charboost SDK v8.1.0
    * **Mediation Adapter Version**
        com.mopub.mediation:chartboost v8.1.0.1
    * **Steps to reproduce the issue**
        I guess it's occurring when one tries to dismiss a Chartboost interstitial ad.
    * **Observed behavior**
        The application crashes.
    * **Expected behavior**
        The application does not crash.
    * **Evidence**
        The following stacktrace:
```
com.mopub.mobileads.ChartboostShared$ChartboostSingletonDelegate.didDismissInterstitial ChartboostShared.java:341
com.chartboost.sdk.impl.a.d SourceFile:9
com.chartboost.sdk.impl.a$a.run SourceFile:31
android.os.Handler.handleCallback Handler.java:883
android.os.Handler.dispatchMessage Handler.java:100
android.os.Looper.loop Looper.java:237
android.app.ActivityThread.main ActivityThread.java:8154
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:496
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1100
```
produces the following exception:
```
java.lang.AbstractMethodError: abstract method "void com.mopub.mobileads.AdLifecycleListener$FullscreenInteractionListener.onAdDismissed()"
```

**Comment by fbrescia** [comment]
If it helps, a similar issue also occurs after having completed a Charboost rewarded ad, e.g.:
```
com.mopub.mobileads.ChartboostShared$ChartboostSingletonDelegate.didCompleteRewardedVideo ChartboostShared.java:465
com.chartboost.sdk.Model.c.h SourceFile:7
com.chartboost.sdk.impl.u1.v SourceFile:2
com.chartboost.sdk.impl.u1.z SourceFile:3
com.chartboost.sdk.impl.v1$a.run SourceFile:9
android.os.Handler.handleCallback Handler.java:751
android.os.Handler.dispatchMessage Handler.java:95
android.os.Looper.loop Looper.java:154
android.app.ActivityThread.main ActivityThread.java:6816
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run ZygoteInit.java:1565
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1453
```
which produces the following error:
```
java.lang.AbstractMethodError: abstract method "void com.mopub.mobileads.AdLifecycleListener$FullscreenInteractionListener.onAdComplete(com.mopub.common.MoPubReward)"
```

**Comment by hmertkahraman** [comment]
Hi @fbrescia ,

Thanks for sharing the details.

We would like to reproduce the issue on our end to find the root cause and then apply a fix if needed. To do this, can we please request repro steps from you, if you're able to obtain or reproduce on your end? Do you have any additional details apart from these stacktraces?

Thanks,
MoPub Team

**Comment by fbrescia** [comment]
Hi @hmertkahraman ,

As reproducing the issue implies being served with a Chartboost interstitial or rewarded ad, one is not able to reproduce it easily. That's why we are relying on App Center crash reports for this kind of issue.

Anyway, I think we found an explanation for this error, and a possible fix for it.

The `AbstractMethodError` occurs when calling methods annotated with `@JvmDefault`, and it seems that the Android Gradle plugin, starting from v3.5, strips default method implementations under certain conditions.
Setting `android.enableDexingArtifactTransform=false` in the `gradle.properties` file, please correct me if I'm wrong, restores the previous Android Gradle plugin behavior, fixing the calls to the `@JvmDefault` annotated methods.

Let me know if you have further information on this issue.

Thanks,
Franck

**Comment by hmertkahraman** [comment]
Hi @fbrescia ,

We'll work on the reproduction of this issue and get back to you on this.

Thanks,
Mert

**Comment by coldwinter2** [comment]
The same issue.
Cause a lot of crashes in our app.
Please fix this as soon as possible.

**Comment by hmertkahraman** [comment]
Hi @fbrescia ,

We released a new set of Chartboost Android adapters: Android 8.1.0.2 (Unitypackage 1.1.26). Would you be able to update to these adapters, and observe if the issue persists and let us know?

Thanks,
Mert

**Comment by fbrescia** [comment]
Hi @hmertkahraman ,

I'll let you know if the issue persists with the new adapter.
I don't think so since the fix seems to fit, thus I'm closing the issue.

Thanks,
Franck
