### ISSUE TITLE
Facebook adapter sdk 6.2.0.0 always return test ads.

### ISSUE THREAD

**Issue by Ham-mer** [mopub/mopub-android-mediation#304]
1. **What is the issue?**
    > Facebook adapter sdk 6.2.0.0 always return test ads.

2. In 6.2.0.0, we find `AdSettings.setTestMode(true);`

implementation 'com.mopub.mediation:facebookaudiencenetwork:6.2.0.0'
https://bintray.com/mopub/mopub-android-mediation/com.mopub.mediation.facebookaudiencenetwork/6.2.0.0

<img width="1165" alt="截屏2020-11-03 下午12 47 45" src="https://user-images.githubusercontent.com/53942562/97950729-d3e0e100-1dd2-11eb-8dc4-5e3cb5cca2e1.png">

**Comment by p158276** [comment]
Hi @Ham-mer ,
Thanks for reaching out. 
This issue has been addressed in Facebook Android [6.2.0.1](https://github.com/mopub/mopub-android-mediation/commit/189501f2d480b6a5ef9acfede0d61583d61b1bb7) adapter. Let us know if you continue to see the issue.

Yoyo Lin 
MoPub Team

**Comment by Ham-mer** [comment]
@p158276 

Hi, this issue has been fixed in Facebook Android 6.2.0.1 adapter sdk, thank you~
