### ISSUE TITLE
Chartboost's initialization via ChartboostAdapterConfiguration not started as the context calling it is missing or null.

### ISSUE THREAD

**Issue by paradizIscool** [mopub/mopub-android-mediation#307]
1. **What is the issue?**
   Chartboost initialization failed due to not parameters

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Provide the data here
    * **Platform** (*Android, iOS, Unity*)
        > Android and Unity
    * **MoPub SDK Version**
        > 5.14.10 5.15
    * **Mediation SDK Name & Version**
        > ChartboostAdapterConfiguration: Adapter version 8.1.0.2, SDK version 8.1.0
    dapter version 8.1.0.2
        > Provide the data here
    pixel 4a, android 11
        > Provide the data here
    * **Evidence** (if available)
        > 

        > [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log - Initializing com.mopub.mobileads.ChartboostAdapterConfiguration version 8.1.0.2 with network sdk version 8.1.0 and with params {}
        > [com.mopub.mobileads.ChartboostAdapterConfiguration][initializeNetwork] Adapter ChartboostAdapterConfiguration Log - Chartboost's initialization via ChartboostAdapterConfiguration not started as the context calling it is missing or null.

Following the documentation, the configuration is set by the waterfall, the waterfall is configuration is good.

**Comment by p158276** [comment]
Hi @paradizIscool ,

Thanks for reaching out. The reason why you receiving this warning is that you are not passing Chartboost's App ID and App signature during MoPub Initialization. This is optional by using Chartboost mediation. 
If you can ensure Chartboost's App ID and App signature are configured correctly on the MoPub dashboard, the setting will be cached and you are able to see the initialization successfully next time after the ad request in the first launch.

Yoyo Lin
MoPub Team

**Comment by paradizIscool** [comment]
Chartboost App ID and App signature are configured correctly on the MoPub dashboard, this is not the first launch. We have data for all other partners. We have this warning in production games, we didn't notice this log a couple of weeks ago before the release, maybe we missed it, maybe it wasn't.

**Comment by p158276** [comment]
Hi @paradizIscool ,
Thanks for the detailed information. 
The behavior you are seeing is unintended, and it seems to happen due to we are not caching the ID in Chartboost adapter. A workaround to mitigate it is to [pass the `appId` and `appSignature` during MoPub initialization](https://developers.mopub.com/publishers/android/initialize/#example). I circle back this issue and get back to you when we have any updates.

**Comment by p158276** [comment]
Hi @paradizIscool ,
This issue has been addressed in https://github.com/mopub/mopub-android-mediation/commit/eedbbce4dd0242aae982c87428b605f1930676ae. Let us know if you continue to see the issue.
