### ISSUE TITLE
Requesting AdMob Native extra assets

### ISSUE THREAD

**Issue by svenoaks** [mopub/mopub-android-mediation#308]
1. **What is the issue?**
    > How to request and use the extra native ad assets from AdMob.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ x] I searched https://developers.mopub.com/ and found no answer.
    - [x ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Native Static
    * **Platform** (*Android, iOS, Unity*)
        > Android
    * **MoPub SDK Version**
        > 5.15.0
    * **Mediation SDK Name & Version**
        > MoPub
    * **Mediation Adapter Version**
        > com.mopub.mediation:admob:19.5.0.3
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > 084ba522607848d2a8745da6abe03e46
    * **Device model and OS Version**
        > OnePlus 7 Pro Android 10
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Create GPS ad renderer:
```
val googlePlayServicesAdRenderer = GooglePlayServicesAdRenderer(
            GooglePlayServicesViewBinder.Builder(R.layout.ad_player_native)
                    .iconImageId(R.id.ad_app_icon)
                    .titleId(R.id.ad_headline)
                    .textId(R.id.ad_body_small)
                    .callToActionId(R.id.ad_call_to_action)
                    .privacyInformationIconImageId(R.id.ad_privacy)
                    .addExtra(GooglePlayServicesAdRenderer.VIEW_BINDER_KEY_STAR_RATING,
                            R.id.ad_star_rating)
                    .addExtra(GooglePlayServicesAdRenderer.VIEW_BINDER_KEY_PRICE,
                            R.id.ad_price)
                    .addExtra(GooglePlayServicesAdRenderer.VIEW_BINDER_KEY_STORE,
                            R.id.ad_store)
                    .addExtra(GooglePlayServicesAdRenderer.VIEW_BINDER_KEY_ADVERTISER,
                            R.id.ad_advertiser)
                    .build())
```
> 2. makeRequest() with no arguments or with
```
val desiredAssets = EnumSet.of(
            NativeAdAsset.TITLE,
            NativeAdAsset.TEXT,
            NativeAdAsset.ICON_IMAGE,
            NativeAdAsset.CALL_TO_ACTION_TEXT,
            NativeAdAsset.STAR_RATING,
            NativeAdAsset.SPONSORED,
    )
```
How to request the assets for GPS extras?
    * **Observed behavior**
        > Nothing is ever filled in for star rating, key price, store, advertiser.
    * **Expected behavior** (if known)
        > The extra assets are filled in when available.

Additionally, why does the id for the star rating use a `TextView` instead of a `RatingBar`?

**Comment by chauduyphanvu** [comment]
@svenoaks, based on [Google's documentation](https://developers.google.com/android/reference/com/google/android/gms/ads/formats/UnifiedNativeAd#getStarRating()), the native ads must be "app install ads" in order for the extra assets (star rating, price, store, and advertiser) to be available. Then, only if they are available will the adapters show them: https://github.com/mopub/mopub-android-mediation/blob/master/AdMob/src/main/java/com/mopub/nativeads/GooglePlayServicesNative.java#L637-L647. 

How often are you not getting the extra assets? Does your XML have the Views to accommodate them when they are available? 

Let us know if there are any questions.
Vu Chau
MoPub Team

**Comment by svenoaks** [comment]
Yes, the layouts have the TextViews referenced. It's very difficult to get app install ads to test since

a. AdMob test unit Id's for native rarely serve an ad, and when they do, they're not app install ads.
b. Using a device set up for test ads or the emulator doesn't serve app install ads.
c. If you manage to get some live ads to test it seems you get blacklisted or rate limited really quickly.

That being said I did manage to pull a couple ads that were surely 'App Install' ads and test with the configuration shown above. They were ads for Pokemon Go and TikTok. In those cases, the extra assets are not filled in. All the other items are filled in so the ads were loading successfully.

**Comment by chauduyphanvu** [comment]
@svenoaks - thanks for the confirmation. I'll do some tests to see if I can reproduce that. Will update the thread.

**Comment by hoanghiephui** [comment]
> @svenoaks - thanks for the confirmation. I'll do some tests to see if I can reproduce that. Will update the thread.

Hey @chauduyphanvu 
Can you tell when the problem is solved. I also have this problem.

Thanks.

**Comment by chauduyphanvu** [comment]
@hoanghiephui, it's been very hard to get AdMob native ads with the extra assets so I haven't been able to reproduce this issue. I will keep trying and will let you know if there is progress. Thanks!
