### ISSUE TITLE
Access GooglePlayServicesNativeAd class from outside

### ISSUE THREAD

**Issue by amsdamsgram** [mopub/mopub-android-mediation#327]
1. **What is the issue?**
    Is it possible to set GooglePlayServicesNativeAd class public so we can access it from outside the package?

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Native Static
    * **Platform** (*Android, iOS, Unity*)
        > Android
    * **MoPub SDK Version**
        > 5.15.0
    * **Mediation SDK Name & Version**
        > Admob 19.5.0
    * **Mediation Adapter Version**
        > Admob 19.5.0.3
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > 8f25616bc6894f6db6fe92751a0dceb6
    
I'm using Mopub and Admob to display native ads. According to the documentation of the mopub SDK, `nativeAd.getBaseNativeAd()` is not returning the same thing if the ad comes from Mopub or a mediation network.
When this is an ad from Admob, `nativeAd.getBaseNativeAd()` is returning a `GooglePlayServicesNativeAd` but I can't access it. I get an error when building: `error: GooglePlayServicesNativeAd is not public in GooglePlayServicesNative; cannot be accessed from outside package`. How can I access to the ad data for a Admob ad?

Here is the code, I have:

```
@Override
    public void onNativeLoad(NativeAd nativeAd) {
        String title = "";
        String mainText = "";
        String callToActionText = "";
        String mainImageSource = "";
        String iconImageSource = "";
        String privacyIconImageSource = "";

        if (nativeAd.getBaseNativeAd() instanceof StaticNativeAd) {
            StaticNativeAd staticNativeAd = (StaticNativeAd) nativeAd.getBaseNativeAd();
            title = staticNativeAd.getTitle();
            mainText = staticNativeAd.getText();
            callToActionText = staticNativeAd.getCallToAction();
            mainImageSource = staticNativeAd.getMainImageUrl();
            iconImageSource = staticNativeAd.getIconImageUrl();
            privacyIconImageSource = staticNativeAd.getPrivacyInformationIconImageUrl();
        } else {
            GooglePlayServicesNative.GooglePlayServicesNativeAd googleNativeAd = (GooglePlayServicesNative.GooglePlayServicesNativeAd) nativeAd.getBaseNativeAd();
            title = googleNativeAd.getTitle();
            mainText = googleNativeAd.getText();
            callToActionText = googleNativeAd.getCallToAction();
            mainImageSource = googleNativeAd.getMainImageUrl();
            iconImageSource = googleNativeAd.getIconImageUrl();
            privacyIconImageSource = googleNativeAd.getPrivacyInformationIconImageUrl();
        }
```

Thanks for your help,

**Comment by chauduyphanvu** [comment]
@amsdamsgram, taking a look now. We should be able to make the class `public`. Stay tuned!

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
Done in https://github.com/mopub/mopub-android-mediation/commit/2aa36e0783ecc3e59794946283e9bf15ec6be500. Let us know if you need anything else.

**Comment by amsdamsgram** [comment]
Thanks!
