### ISSUE TITLE
`notifyItemRangeInserted` do not load more ads when insert items into list.

### ISSUE THREAD

**Issue by sinhpn92** [mopub/mopub-android-mediation#335]
1. **What is the issue?**
    `notifyItemRangeInserted` do not load more ads when insert items into list.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ x] I searched https://developers.mopub.com/ and found no answer.
    - [x ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        Native ad placer
    * **Platform** (*Android, iOS, Unity*)
        Android
    * **MoPub SDK Version**
        5.16.4
    * **Mediation SDK Name & Version**
```
        implementation('com.mopub:mopub-sdk:5.16.4@aar') {
           transitive = true
        }
        implementation('com.mopub:mopub-sdk-fullscreen:5.16.4@aar') {
            transitive = true
       }
       implementation('com.mopub:mopub-sdk-native-static:5.16.4@aar') {
           transitive = true
       }
       implementation('com.mopub:mopub-sdk-banner:5.16.4@aar') {
           transitive = true
       }
        implementation 'com.facebook.android:audience-network-sdk:6.3.0'
        implementation 'com.mopub.mediation:facebookaudiencenetwork:6.3.0.0'
        implementation 'com.mopub.mediation:admob:19.8.0.0'
        implementation 'com.applovin:applovin-sdk:10.1.1'
        implementation 'com.mopub.mediation:applovin:10.1.1.0'
```
   
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Load the ads with page 1 of list
        > 2. Scroll down to load more page of list. Call `notifyItemRangeInserted` function when insert items to list.
        -> The ads in the next page which have inserted to the list do not added.
        
        
        
How to load ads when inserted items? We do not want to `notifyDataSetChanged` on inserted items, because it's bad experiences.

**Comment by chauduyphanvu** [comment]
@sinhpn92, have you tried the recommendation on https://developers.mopub.com/publishers/android/native-recyclerview/#keeping-ads-in-the-same-relative-position? 

```java
notifyItemInserted(position);
notifyItemRemoved(position);
notifyItemsInserted(position, count);
notifyItemsRemoved(position, count);
```

Vu Chau
MoPub Team

**Comment by sinhpn92** [comment]
@chauduyphanvu
Yes, I did.
I my own Adapter I have used DiffUtil to handle the view changed with the data list. And notify in the callback like that:
```
protected val listUpdateCallback by lazy {
        object: ListUpdateCallback {
            override fun onInserted(position: Int, count: Int) {
                Log.logD("--> onInserted: $position | $count")
                if (count > 1) {
                    if (position >= items.size) notifyDataSetChanged()
                    else notifyItemRangeInserted(position + 1, count)
                } else if (position == 0) {
                    notifyItemInserted(position)
                } else {
                    notifyItemChanged(position)
                }
            }

            override fun onRemoved(position: Int, count: Int) {
                Log.logD("--> onRemoved: $position | $count")
                if (count > 1) notifyItemRangeRemoved(position, count)
                else notifyItemRemoved(position)
            }

            override fun onMoved(fromPosition: Int, toPosition: Int) {
                Log.logD("--> onMoved: $fromPosition | $toPosition")
                notifyItemMoved(fromPosition, toPosition)
            }

            override fun onChanged(position: Int, count: Int, payload: Any?) {
                Log.logD("--> onChanged: $position | $count")
                if (count > 1) notifyItemRangeChanged(position, count)
                else notifyItemChanged(position)
            }
        }
    }
```

The repeating ad position not working there. Ads only loaded with the fixed position.

**Comment by chauduyphanvu** [comment]
@sinhpn92, I'm not clear what the issue you are reporting is (it seems to be two related issues). Let me tackle the latest one you described.

When you create your ad unit ID on the MoPub dashboard, did you set it up with an interval (something like in the screenshot below)? You can also plug your ad unit ID into the MoPub Android sample app on this repository to check for the default behavior.

![image](https://user-images.githubusercontent.com/25616035/113931265-43af2980-97c0-11eb-852a-d4c4dbbc5ad0.png)

**Comment by sinhpn92** [comment]
@chauduyphanvu 
I saw that this issue by the code below:
            ```
@Override
            public void onItemRangeInserted(final int positionStart, final int itemCount) {
                final int adjustedStartPosition = mStreamAdPlacer.getAdjustedPosition(positionStart);
                final int newOriginalCount = mOriginalAdapter.getItemCount();
                mStreamAdPlacer.setItemCount(newOriginalCount);
                final boolean addingToEnd = positionStart + itemCount >= newOriginalCount;
                if (KEEP_ADS_FIXED == mStrategy
                        || (INSERT_AT_END == mStrategy
                        && addingToEnd)) {
                    notifyDataSetChanged();
                } else {
                    for (int i = 0; i < itemCount; i++) {
                        // We insert itemCount items at the original position, moving ads downstream.
                        mStreamAdPlacer.insertItem(positionStart);
                    }
                    notifyItemRangeInserted(adjustedStartPosition, itemCount);
                }
            }
```

I have used ```KEEP_ADS_FIXED``` to keep ads to load. If not, the issue which I have reported will be happen.

**Comment by chauduyphanvu** [comment]
@sinhpn92, I'm not sure I understood the issue here. Is it you aren't able to load extra ads no matter what you do?

Just so we are on the same page, could you confirm if this issue reproduces in the MoPub Android sample app? If so, what are the steps?

Thank you.

**Comment by sinhpn92** [comment]
Ok let's me try in the sample app.
