### ISSUE TITLE
AppLovinAdService#getBidToken() called from main thread

### ISSUE THREAD

**Issue by brewin** [mopub/mopub-android-mediation#338]
1. **What is the issue?**
    > [AppLovinAdService] AppLovinAdService#getBidToken() called from main thread! Necessary signals may not be collected in time!

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Banner
    * **Platform** (*Android, iOS, Unity*)
        > Android
    * **MoPub SDK Version**
        > 5.16.4
    * **Mediation SDK Name & Version**
        > AppLovin 10.1.2
    * **Mediation Adapter Version**
        > AppLovin 10.1.2.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > 
    * **Device model and OS Version**
        > 
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Initialize AppLovin SDK
        > 2.
    * **Observed behavior**
        > Error message.
    * **Expected behavior** (if known)
        > Not called on main thread, no error message.
    * **Evidence** (if available)
        >

**Comment by p158276** [comment]
Hi @brewin ,

Thanks for reaching out. We collect bid tokens in the main thread for the third-party network when the ad request happened. Bidder token is meant to be a getter method in the adapter. The reason we do bidder token on the main thread is that we construct the ad request on whichever thread the publisher calls to load the ad. We don't want to thread hop just to get a bidder token. 

Yoyo Lin
MoPub team
