### ISSUE TITLE
GooglePlayServicesAdRenderer doesn't set scale type to MediaView

### ISSUE THREAD

**Issue by sanovikov71** [mopub/mopub-android-mediation#340]
Hi, I use AdMob mediation library and sometimes the creative inside the native Google ad is not centered properly, it can be located to the left part of the screen for example.

It looks that MediaView that is used in GooglePlayServicesAdRenderer.java does not have correct scale type.

I think it is possible to set the scale type
`mediaView.setImageScaleType(ScaleType.CENTER_CROP);`
right after creation of the MediaView
`MediaView mediaview = new MediaView(nativeAdView.getContext()); // line 200`

I tried that when debugging and did not see misplaced creatives after that.

Lib versions:
'com.mopub:mopub-sdk:5.16.4@aar'
'com.google.android.gms:play-services-ads:20.0.0'
'com.mopub.mediation:admob:20.0.0.0'

**Comment by chauduyphanvu** [comment]
@sanovikov71, thanks for the suggestion. Would you be able to submit that change in a Pull Request so we can review more thoroughly? 

Vu Chau
MoPub Team

**Comment by sanovikov71** [comment]
@chauduyphanvu Hi, sure, I have created a PR for this https://github.com/mopub/mopub-android-mediation/pull/341

**Comment by brewin** [comment]
I have noticed that some Google banner ads are aligned to the left even with the MoPubView layout_width set to match_parent. I don't know if it's the same as this issue with native ads. If it is, maybe this fix can be applied to banner ads as well?

Two creatives I saw that were aligned to the left were from Geico and Lucky Charms, if that helps at all.

**Comment by chauduyphanvu** [comment]
@brewin - banner and native ads use different Views under the hood, so this same fix cannot be applied to banner ads. We'd need to investigate the banner alignment issue before we can recommend a fix.

If you can reproduce the same issue with banners, please open a separate GitHub Issue report and we can resume the conversation over there. Thanks!

**Comment by chauduyphanvu** [comment]
@sanovikov71, fixed in https://github.com/mopub/mopub-android-mediation/commit/fd400baf91557bbd0c11a33a801540199638a041. Thanks!
