### ISSUE TITLE
Admob Native MediaView scale wrong when use 4G(Mobile Data)

### ISSUE THREAD

**Issue by tracer8** [mopub/mopub-android-mediation#343]
1. **What is the issue?**
    > Admob Native MediaView scale wrong when use 4G(Mobile Data)

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Admob Native Video
    * **Platform** (*Android, iOS, Unity*)
        > Android
    * **MoPub SDK Version**
        > com.mopub:mopub-sdk:5.16.4
    * **Mediation SDK Name & Version**
        > 'com.mopub.mediation:admob:20.0.0'
    * **Mediation Adapter Version**
        > 'com.google.android.gms:play-services-ads:20.0.0'
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > a3548e07ced6467bbe6f7d98db9a4315
    * **Device model and OS Version**
        > Samsung A71 - Android 11
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Download Mopub Sample App: https://play.google.com/store/apps/details?id=com.mopub.simpleadsdemo&hl=en
        > 2. Or Implement Native Video Ad by yourself (Must have admob renderer, cause this bug only on Admob Video Native)
        > 3. Use this ad unit id: a3548e07ced6467bbe6f7d98db9a4315
        > This is test id of admob native video ad i setup
        > 4. Turn off Wifi . Then turn on your Mobile Data(4G), 
        > 5. Try to load and show this native video ad on manual
        > 6. If this issue not show up on first try, try 2,3 times, then you will see this. like image bellow

@chauduyphanvu : Nếu bác ở Việt Nam thì xài 4G của Viettel nhé. 4G mạng khác em chưa thử. 

![Screenshot_20210427-151331_MoPub](https://user-images.githubusercontent.com/15725821/116208878-8a62c480-a76b-11eb-9a0c-4bb9c14df3da.jpg)
![Screenshot_20210427-151339_MoPub](https://user-images.githubusercontent.com/15725821/116208882-8b93f180-a76b-11eb-8986-389ac97877a8.jpg)
![Screenshot_20210427-151433_MoPub](https://user-images.githubusercontent.com/15725821/116208885-8c2c8800-a76b-11eb-9739-e1efc430ee24.jpg)
![Screenshot_20210427-151505_MoPub](https://user-images.githubusercontent.com/15725821/116208886-8c2c8800-a76b-11eb-93dc-c1e59e134724.jpg)

**Comment by chauduyphanvu** [comment]
@tracer8, thanks for the report! While this issue was not reproducible internally, we've preemptively made an adjustment in https://github.com/mopub/mopub-android-mediation/commit/fd400baf91557bbd0c11a33a801540199638a041. Check out the new version and let us know if you continue to see the issue.

Bạn vui lòng thử phiên bản mới xem nó có giải vấn đề này không nhé. Cảm ơn bạn!

**Comment by tracer8** [comment]
@chauduyphanvu : I tested with version 'com.mopub.mediation:admob:20.0.0.1', this issue still remain.

**Comment by chauduyphanvu** [comment]
Thanks, so it sounds like this is a separate but related issue. I'll keep testing to see what I find!

**Comment by chauduyphanvu** [comment]
We've reproduced the issue and have escalated it to Google for investigation. Stay tuned!

**Comment by tracer8** [comment]
Glad to hear that!

**Comment by iForests** [comment]
Same here. Only happened when using mobile data network. Is there any updates from Google? Thanks.

**Comment by chauduyphanvu** [comment]
@iForests, there are currently no updates on this issue yet. I have followed up with Google again and will share more details when available.

**Comment by tracer8** [comment]
Reopen this issue please.
This issue still appear on newest version of mopub SDK!

**Comment by tracer8** [comment]
After testing with native Admob without use mopub, i find out it is not Google Issue. Bellow is screenshot of native video ad on Mobile Network(4g) with out scale issue.
![SmartSelect_20210927-233617_Gallery](https://user-images.githubusercontent.com/15725821/134949946-4b64d309-0cd9-4f1e-b0f4-6f0dfd8a3f86.jpg)
