### ISSUE TITLE
Interstitial Ads not have listener for Ads Show Fail.

### ISSUE THREAD

**Issue by tracer8** [mopub/mopub-android-mediation#344]
- When i try to show interstitial, sometimes will not show ads success. But not have Ad Show Fail listener. So i can't do anything to resolve this situation. So i hope this event will be add on next update of Mopub Android mediation.
- Example for this:
+ When i try to show Unity Interstitial, it can't show because error bellow:

> 2021-04-28 15:33:02.793 19833-19833/com.sample.mopub I/MoPub: [com.mopub.mobileads.UnityInterstitial][show] Adapter UnityInterstitial attempting to show ad
> 2021-04-28 15:33:12.802 19833-21742/com.sample.mopub I/MoPub: [com.mopub.mobileads.UnityInterstitial$3][onUnityAdsShowFailure] Adapter UnityInterstitial Log - Unity interstitial video encountered a playback error for placement video, with error message: [UnityAds] Timeout while trying to show video
> 2021-04-28 15:33:12.806 19833-21742/com.sample.mopub I/MoPub: [com.mopub.mobileads.UnityInterstitial$3][onUnityAdsShowFailure] Adapter UnityInterstitial failed to show ad: (10,000) Error playing a video.
> 2021-04-28 15:33:12.811 19833-19833/com.sample.mopub I/MoPub: [com.mopub.mobileads.MoPubInterstitial][onAdLoadFailed] Ad failed to load: (10,000) Error playing a video.

**Comment by p158276** [comment]
Hi @tracer8 ,
Thanks for reaching out. From the error log below, seems the logic triggers the UnityAd's callback [onUnityAdsShowFailure](https://github.com/mopub/mopub-android-mediation/blob/a46535257c483cf14a8e919f7f7c57a58b8eca81/UnityAds/src/main/java/com/mopub/mobileads/UnityInterstitial.java#L176-L184) when trying to show the ad. You don't have a dedicated callback for show error. You should listen [onInterstitialFailed](https://developers.mopub.com/publishers/reference/android/InterstitialAdListener/#public-void-oninterstitialfailedmopubinterstitial-interstitial-mopuberrorcode-errorcode) and handle the error according to the error code. Besides, to investigate the reason for the show error, you can filter Unity SDK log to check for detail.

Yoyo Lin
MoPub Team

**Comment by tracer8** [comment]
@p158276 : Oh so listener onInterstitialFailed not only trigger on Load fail, it can trigger on Show Fail too?
I have little confuse here.
thanks!

**Comment by p158276** [comment]
Hi @tracer8 , 
Yes, Interstitial doesn't have a dedicated callback for show error. So listener onInterstitialFailed will apply not only to Load fail but show fail.

**Comment by tracer8** [comment]
Thank you, i got it now!
