### ISSUE TITLE
Issue with latest mediation SDKs - Could not find com.mopub:mopub-sdk

### ISSUE THREAD

**Issue by patrickfrei** [mopub/mopub-android-mediation#347]
Hello,

In my build.gradle I have below settings for MoPub integration (two dependency blocks for API levels up to 18 [old MoPub and mediation SDKs] and from API level 19 up to the latest [new MoPub and mediation SDKs]. Everything is working fine.

Now, I've see in the mediation integration tool that for Facebook, a new version is available: "com.facebook.android:audience-network-sdk:6.**4**.0" and "com.mopub.mediation:facebookaudiencenetwork:6.**4**.0.0"

As soon as I change from version 6.**3**. to the new version 6.**4**., I get below error message. I can't figure out the problem. Can you please help me?

```
Execution failed for task ':app:checkFreeVersionMinApi19DebugAarMetadata'.
> Could not resolve all files for configuration ':app:freeVersionMinApi19DebugRuntimeClasspath'.
   > Could not find com.mopub:mopub-sdk:.
     Required by:
         project :app > com.mopub.mediation:facebookaudiencenetwork:6.4.0.0
```

```
repositories {
    mavenCentral()
    // Searches for the MoPub SDK and AVID library
    maven { url "https://s3.amazonaws.com/moat-sdk-builds" }
    // Searches for the AdColony SDK and libraries
    maven { url "https://adcolony.bintray.com/AdColony" }
}

dependencies {
    // MoPub SDK dependencies (minimum API 19)
    // MoPub Ads - Banners
    freeVersionMinApi19Implementation('com.mopub:mopub-sdk-banner:5.16.4@aar') { transitive = true }
    // MoPub Ads - Interstitial (=Fullscreen)
    freeVersionMinApi19Implementation('com.mopub:mopub-sdk-fullscreen:5.16.4@aar') { transitive = true }
    // MoPub Mediation - Facebook Audience Network (FAN)
    freeVersionMinApi19Implementation 'com.facebook.android:audience-network-sdk:6.3.0'
    freeVersionMinApi19Implementation 'com.mopub.mediation:facebookaudiencenetwork:6.3.0.0'
    // MoPub Mediation - AdColony Ads
    freeVersionMinApi19Implementation 'com.adcolony:sdk:4.4.1'
    freeVersionMinApi19Implementation 'com.mopub.mediation:adcolony:4.4.1.0'
    // MoPub Mediation - Unity Ads
    freeVersionMinApi19Implementation 'com.unity3d.ads:unity-ads:3.6.0'
    freeVersionMinApi19Implementation 'com.mopub.mediation:unityads:3.6.0.1'

    // MoPub SDK dependencies (minimum API 16)
    // MoPub Ads - Banners
    //freeVersionImplementation('com.mopub:mopub-sdk-banner:+@aar') { transitive = true }
    freeVersionMinApi16Implementation('com.mopub:mopub-sdk-banner:5.10.0@aar') { transitive = true }
    // MoPub Ads - Interstitial
    //freeVersionImplementation('com.mopub:mopub-sdk-interstitial:+@aar') { transitive = true }
    freeVersionMinApi16Implementation('com.mopub:mopub-sdk-interstitial:5.10.0@aar') { transitive = true }
    // MoPub Mediation - Facebook Audience Network (FAN)
    freeVersionMinApi16Implementation 'com.facebook.android:audience-network-sdk:5.6.1'
    freeVersionMinApi16Implementation 'com.mopub.mediation:facebookaudiencenetwork:5.6.1.0'
    // MoPub Mediation - AdColony Ads
    freeVersionMinApi16Implementation 'com.adcolony:sdk:4.1.1'
    freeVersionMinApi16Implementation 'com.mopub.mediation:adcolony:4.1.1.0'
    // MoPub Mediation - Unity Ads
    freeVersionMinApi16Implementation 'com.unity3d.ads:unity-ads:3.4.2'
    freeVersionMinApi16Implementation 'com.mopub.mediation:unityads:3.4.2.0'
}
```

**Comment by chauduyphanvu** [comment]
@patrickfrei, I'm not sure how the two dependency blocks you have interact with each other, but I tested `implementation 'com.mopub.mediation:facebookaudiencenetwork:6.4.0.0'` by itself with MoPub 5.16.4 and everything worked.

Could you confirm with our Android sample app's [build.gradle](https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sample/build.gradle)? Simply change the version number to 6.4.0 and 6.4.0.0 and see if it works for you. Then we can start narrowing down on the possible causes.

Vu Chau
MoPub Team

**Comment by patrickfrei** [comment]
@chauduyphanvu , your sample Android app is working as expected. However, I've just found out the issue in my code:

As described [here](https://github.com/mopub/mopub-android-sdk) and as shown in my code above, I'm using the SDK modularization because I just need the MoPub SDK for banners and fullscreen ads:

```
// MoPub Ads - Banners
    freeVersionMinApi19Implementation('com.mopub:mopub-sdk-banner:5.16.4@aar') { transitive = true }
// MoPub Ads - Interstitial (=Fullscreen)
    freeVersionMinApi19Implementation('com.mopub:mopub-sdk-fullscreen:5.16.4@aar') { transitive = true }
```

If I change that code to...
```
// MoPub no SDK modularization
   freeVersionMinApi19Implementation('com.mopub:mopub-sdk:5.16.4@aar') { transitive = true }   
```
...the error message disappears. This means, that SDK modularization is obviously not supported anymore since the last update of "Facebook", "AdColony" and "UnityAds" SDKs. The explicitly look for com.mopub:mopub-sdk but not for com.mopub:mopub-sdk-banner and com.mopub:mopub-sdk-fullscreen anymore.

Can you reproduce that issue on your side, too?

**Comment by chauduyphanvu** [comment]
@patrickfrei, we have addressed this issue internally now. New adapter versions will be released in 1-2 days for you. At that time, you can continue using the modularized MoPub SDKs together with mediation.

Stay tuned!

**Comment by patrickfrei** [comment]
@chauduyphanvu , thank you! I'll wait for the new versions and will let you know the results.

**Comment by patrickfrei** [comment]
@chauduyphanvu , just updated to the latest mediation SDKs and can confirm that all works well again. Thank you very much for the bugfix!

**Comment by chauduyphanvu** [comment]
@patrickfrei, just about to let you know :) thanks for the confirmation!
