### ISSUE TITLE
FacebookAdapterConfiguration missing in adapter 6.4.x.0

### ISSUE THREAD

**Issue by soenkegissel** [mopub/mopub-android-mediation#348]
1. **What is the issue?**
    > Last adapter version where FacebookAdapterConfiguration is found is 6.3.0.0, in 6.4.x.0 is missing.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [X ] I searched https://developers.mopub.com/ and found no answer.
    - [X ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [X ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Banner, Interstitial
    * **Platform** (*Android, iOS, Unity*)
        > Android
    * **MoPub SDK Version**
        > 5.16.4
    * **Mediation SDK Name & Version**
        > Facebook 6.4.0
    * **Mediation Adapter Version**
        > 6.4.x.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Provide the data here
    * **Device model and OS Version**
        > Provide the data here
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Update to adapter version 6.4.x.0
    * **Observed behavior**
        > Provide the data here
    * **Expected behavior** (if known)
        > Provide the data here
    * **Evidence** (if available)
        > Attach logs (device/network), mini debug builds (source code preferably), stack traces, screenshots / screen recordings, etc.

**Comment by chauduyphanvu** [comment]
@soenkegissel, I pulled v6.4.0.0 and confirmed that FacebookAdapterConfiguration exists:

![image](https://user-images.githubusercontent.com/25616035/117012155-a5c65600-acbc-11eb-83f4-ef379db8aaf0.png)

Do you have Proguard that might be removing that class by accident?

Vu Chau
MoPub Team

**Comment by soenkegissel** [comment]
My fault. I put in the iOS adapter version which is 6.4.1.0.
