### ISSUE TITLE
OnebyAOL Adapter Moat Issues

### ISSUE THREAD

**Issue by rbiddulph** [mopub/mopub-android-mediation#35]
Both Mopub SDK 5.0.0 and OnebyAOL SDK 6.8.1 include version 2.4.1 of Moat, the OnebyAOL project having these bundled and the Mopub SDK uses a gradle maven repo.

In Android Studio 3.1.2 and with the latest gradle and android build tools this is causing issues with dex merging when building, with the proguarded moat files causing a conflict:
 

> Program type already present: com.a.e.d
> Message{kind=ERROR, text=Program type already present: com.a.e.d, sources=[Unknown source file], tool name=Optional.of(D8)}

The workaround to get the app to build is to add `android.enableD8=false` to the project’s `gradle.properties` file to revert to the old Dexing process. The `com.a.e.d` class is found in the OnebyAOL aar file and also downloaded in the Mopub version of the Moat SDK as `com.a.a.b`.

One side effect is that D8 will be on permanently in a future release of Android Studio:

> WARNING: The option 'android.enableD8' is deprecated and should not be used anymore.
> Use 'android.enableD8=true' to remove this warning.
> It will be removed in AGP version 3.3.

Setting the `android.enableD8=false` flag allows debug builds to continue to work, however when performing a release build with Proguard enabled we get further issues:

> Warning: Exception while processing task java.io.IOException: Can't write [...\build\intermediates\transforms\proguard\...\release\0.jar] (Can't read [...\.gradle\caches\transforms-1\files-1.1\moat-mobile-app-kit-2.4.1.aar\...\jars\classes.jar(;;;;;;**.class)] (Duplicate zip entry [com/a/a/b.class == classes.jar:com/a/e/d.class]))
> Thread(Tasks limiter_1): destruction

**Comment by ScottishPig** [comment]
The issue existed in version 2.4.1 of their MoPub library, and it's fixed in version 2.4.5 ( direct AAR link here: https://s3.amazonaws.com/moat-sdk-builds/com/moat/analytics/mobile/mpub/moat-mobile-app-kit/2.4.5/moat-mobile-app-kit-2.4.5.aar ). 

If you clone down the MoPub repo, you can use this updated version... otherwise, MoPub needs to update their JCenter POM file-- https://jcenter.bintray.com/com/mopub/mopub-sdk-base/5.0.0/mopub-sdk-base-5.0.0.pom calls out the old version.

**Comment by chauduyphanvu1** [comment]
This should have been resolved with the [5.1.0 release of the MoPub SDK](https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sdk/mopub-sdk-base/build.gradle#L19). Check it out and let us know if you continue running into the issue!
