### ISSUE TITLE
Proguard config for SDK Mediation

### ISSUE THREAD

**Issue by tracer8** [mopub/mopub-android-mediation#352]
Hi,
I'm looking for proguard config of Mopub Mediation SDK.
So far so good, i found this config, but only for Mopub SDK, not Mopub Mediation Adapter. 
[https://github.com/mopub/mopub-android-sdk/blob/c6694a4cf584b33eaee9087ef3ad0b490095b644/mopub-sdk/proguard.txt](url)

**Comment by chauduyphanvu** [comment]
@tracer8, please refer to our documentation for each ad network's Proguard rules. For example, here's ironSource's configuration: https://developers.mopub.com/publishers/mediation/networks/ironsource/. Not all networks explicitly need a `keep` rule so if needed, you are recommended to check with the ad network's support team.

Vu Chau
MoPub Team
