### ISSUE TITLE
FacebookAudienceNetwork do not show the media icon when do not set main media view

### ISSUE THREAD

**Issue by sinhpn92** [mopub/mopub-android-mediation#357]
1. **What is the issue?**
    I have a small native ad row to show the native ad in the recyclerview list. And in this view, I remove main media view in the facebook placer. But `adIconView` do not showing up. I tried to add main media view again and `adIconView` is showing up. So the error in there when remove main mediaview.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ x] I searched https://developers.mopub.com/ and found no answer.
    - [ x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Native ad with facebook audience network
    * **Platform** (*Android, iOS, Unity*)
        > Android
    * **MoPub SDK Version**
       ```
       implementation('com.mopub:mopub-sdk:5.16.4@aar') {
          transitive = true
      }
      implementation('com.mopub:mopub-sdk-fullscreen:5.16.4@aar') {
          transitive = true
      }
      implementation('com.mopub:mopub-sdk-native-static:5.16.4@aar') {
          transitive = true
      }
      implementation('com.mopub:mopub-sdk-banner:5.16.4@aar') {
          transitive = true
      }
      implementation 'com.facebook.android:audience-network-sdk:6.5.0'
      implementation 'com.mopub.mediation:facebookaudiencenetwork:6.5.0.0'
    ```

    * **Device model and OS Version**
        > Pixel 3 android 9.0

    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. create layout for facebook audience network mediation without main media view
        > 2. set renderer
    
    * **Expected behavior** (if known)
        > show the ad icon when do not show the main media view.

    * **Evidence** (if available)
        > 
<img width="420" alt="Screen Shot 2021-06-11 at 10 37 44 AM" src="https://user-images.githubusercontent.com/9253441/121627468-99929d00-caa1-11eb-86a4-a151c209a5b8.png">

**Comment by chauduyphanvu** [comment]
@sinhpn92, are you using native or native banner? Could you show your code and share your ad unit ID?

Vu Chau
MoPub Team

**Comment by sinhpn92** [comment]
@chauduyphanvu
I have used native ad unit for that.

Init config:
```
val configInterstitialBuilder = SdkConfiguration.Builder(adUnit)

val facebookMediationConfig = hashMapOf<String, String>()
facebookMediationConfig["native"] = "true"
facebookMediationConfig["native-banner"] = "true"
facebookMediationConfig["banner"] = "true"
facebookMediationConfig["interstitial"] = "true"
configInterstitialBuilder.withMediatedNetworkConfiguration(FacebookAdapterConfiguration::class.java.name, facebookMediationConfig)

val initListener = SdkInitializationListener {
 }

MoPub.initializeSdk(this, configInterstitialBuilder.build(), initListener)
```

```
mopubAdsAdapter = MoPubRecyclerAdapter(requireActivity(), viewAdapter)
mopubAdsAdapter!!.registerAdRenderer(AdMediationHelper.facebookSmallRenderer())
mopubAdsAdapter!!.registerAdRenderer(AdMediationHelper.staticSmallRenderer())
mopubAdsAdapter!!.setContentChangeStrategy(MoPubRecyclerAdapter.ContentChangeStrategy.KEEP_ADS_FIXED)
mopubAdsAdapter!!.loadAds(id)
```

```
fun facebookSmallRenderer() = FacebookAdRenderer(
        FacebookAdRenderer.FacebookViewBinder.Builder(R.layout.mopub_placer_small_fb)
            .titleId(R.id.text_view_title)
            .textId(R.id.text_view_text)
            .adIconViewId(R.id.image_view_icon)
            .adChoicesRelativeLayoutId(R.id.layout_ad_choice)
            .advertiserNameId(R.id.text_view_advertiser)
            .callToActionId(R.id.cta)
            .build()
    )
```

```
<?xml version="1.0" encoding="utf-8"?>
<com.facebook.ads.NativeAdLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_margin="@dimen/padding_medium">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@drawable/background_rounder_fa_8dp"
        android:padding="@dimen/padding_medium">

        <com.facebook.ads.MediaView
            android:id="@+id/image_view_icon"
            android:layout_width="48dp"
            android:layout_height="48dp" />

        <TextView
            android:id="@+id/text_view_advertiser"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginStart="@dimen/padding_medium"
            android:layout_marginTop="@dimen/padding_small"
            android:layout_toStartOf="@id/layout_ad_choice"
            android:layout_toEndOf="@id/image_view_icon"
            android:textColor="@color/text_dark_80"
            android:textStyle="bold" />

        <RelativeLayout
            android:id="@+id/layout_ad_choice"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentEnd="true" />

        <TextView
            android:id="@+id/text_view_sponsored"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/text_view_advertiser"
            android:layout_marginStart="@dimen/padding_medium"
            android:layout_toEndOf="@id/image_view_icon"
            android:text="Sponsored"
            android:textColor="@color/text_dark_60"
            android:textSize="@dimen/text_sub_body" />

        <TextView
            android:id="@+id/text_view_title"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/text_view_sponsored"
            android:layout_marginTop="@dimen/padding_medium"
            android:textColor="@color/text_dark_80"
            android:textStyle="bold" />

        <TextView
            android:id="@+id/text_view_text"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/text_view_title"
            android:textColor="@color/text_dark_80"/>

        <TextView
            android:id="@+id/cta"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/text_view_text"
            android:layout_marginTop="@dimen/padding_small"
            android:background="@drawable/button_gradient_rounder_4dp"
            android:gravity="center"
            android:lines="1"
            android:paddingTop="@dimen/padding_small"
            android:paddingBottom="@dimen/padding_small"
            android:textColor="@color/text_white"
            android:textSize="@dimen/text_body"
            android:textStyle="bold" />

    </RelativeLayout>

</com.facebook.ads.NativeAdLayout>
```

**Comment by chauduyphanvu** [comment]
@sinhpn92, thank you! I have also reproduced this behavior myself.

The reason for that can be found in the [adapter code](https://github.com/mopub/mopub-android-mediation/blob/master/FacebookAudienceNetwork/src/main/java/com/mopub/nativeads/FacebookNative.java#L140-L146): 

```java
if (nativeAdBase instanceof NativeAd && mediaView != null) {            
    NativeAd nativeAd = (NativeAd) nativeAdBase;         

    if (clickableViews.size() == 1) {      
        nativeAd.registerViewForInteraction(view, mediaView, adIconView);
    } else {
        nativeAd.registerViewForInteraction(view, mediaView, adIconView, clickableViews);  
    }
}
```

Because you do not have a main MediaView, the `mediaView` is `null` in this case so the `nativeAd.registerViewForInteraction(view, mediaView, adIconView)` line (which has the `adIconView`) is not called. That explains why the ad icon does not display.

I am checking this behavior with the Facebook team and once we know whether it is expected, we will post an update on the next step. Thank you!

**Comment by sinhpn92** [comment]
Great. Thank you @chauduyphanvu . Waiting for next version....

**Comment by chauduyphanvu** [comment]
@sinhpn92, Facebook let us know that this use case is not valid, because you have to show the main MediaView. In this [documentation](https://developers.facebook.com/docs/audience-network/reference/android/com/facebook/ads/nativead.html/), check out the description for `registerViewForInteraction`:

> public void registerViewForInteraction(View view, MediaView mediaView, MediaView adIconView)
>
> Registers the given view as the container and the required MediaView as the contents display for this NativeAd to handle impressions and clicks. **MediaView must be within the view passed as the container for this NativeAd**. Applies a click handler to the entire unit.
>
> Parameters:
> view - the View containing this NativeAd for display
> mediaView - MediaView to display contents such as video, carousel, etc.
> **adIconView - optional MediaView to display Icon.**

As a result, the main MediaView must be present at all times. The AdIcon view is optional.

**Comment by sinhpn92** [comment]
Hm,
Thank you so much @chauduyphanvu ,

But How can I implement the native banner? This view does not contain the mediaView, right?. I need to show ad without mediaView for the native banner (small ad view) in the recyclerView.

**Comment by chauduyphanvu** [comment]
@sinhpn92, are you using [these steps](https://developers.mopub.com/publishers/mediation/networks/facebook/#request-native-banner-ads) to integrate Facebook native banner? If you enable the native banner flag from your app according to the instructions, then the adapters will know it's a native banner request, so the checks will bypass the MediaView: https://github.com/mopub/mopub-android-mediation/blob/master/FacebookAudienceNetwork/src/main/java/com/mopub/nativeads/FacebookNative.java#L147-L153.

```java
} else if (nativeAdBase instanceof NativeBannerAd) {
    NativeBannerAd nativeBannerAd = (NativeBannerAd) nativeAdBase;
    
    if (clickableViews.size() == 1) {
        nativeBannerAd.registerViewForInteraction(view, adIconView);
    } else {
        nativeBannerAd.registerViewForInteraction(view, adIconView, clickableViews);
    }
}
```

**Comment by sinhpn92** [comment]
@chauduyphanvu 
Yes, I'm integrating like that. You can see the code which I shared above. 
In my project, I'm using both native and native banner. Configuration:
```
facebookMediationConfig["native"] = "true"
facebookMediationConfig["native-banner"] = "true"
```

So, How to config the native ad is `native` or `native-banner` on each recyclerView adapter?

**Comment by chauduyphanvu** [comment]
@sinhpn92, because you are using `withMediatedNetworkConfiguration()` to pass the native banner preference, it requires a MoPub initialization in order for the setting to be reset (to regular native), because `withMediatedNetworkConfiguration()` is a MoPub initialization-level API. If you want to request native ad, the change will not take place in the same app session. I think that's the origin of the issue—you are trying to request both ads in the same app session and you are omitting the main MediaView while the ad requests are actually being made for non-native banner ads.

Because native banner already doesn't use a main MediaView, you don't need to do anything from your renderer/layout perspective. You can keep using the same layout you use for FB's regular native ad.

**Comment by sinhpn92** [comment]
Ok thank you so much @chauduyphanvu 
So Can I set height of mediaView to 0 for native banner (It's do not violate anything else?)? Because I cannot separate config the native banner or native ads on each recyclerview adapter. If not, It still facing the issue which I have expand above.

**Comment by chauduyphanvu** [comment]
@sinhpn92, I believe you do not have to do anything specific. You can leave the main MediaView as-is. It should not show for native banners. Let me know if you see otherwise.

The only limitation is you cannot request both native banner and native together in one RecyclerView session. You would need to restart the app, initialize MoPub again, and reset the flag you pass into `withMediatedNetworkConfiguration()`.

**Comment by sinhpn92** [comment]
@chauduyphanvu Thank you so much.
I decided to set the height of mediaView to 0.

If I do not set mediaView.
<img width="770" alt="Screen Shot 2021-06-30 at 8 38 44 AM" src="https://user-images.githubusercontent.com/9253441/123888870-9a22a300-d97e-11eb-9690-66f3d9c92bb8.png">

<img width="421" alt="Screen Shot 2021-06-30 at 8 37 03 AM" src="https://user-images.githubusercontent.com/9253441/123888819-80815b80-d97e-11eb-91b3-60c1898fd9ba.png">

Now for mediaView with height is 0, this layout is my expectation:
<img width="722" alt="Screen Shot 2021-06-30 at 8 39 14 AM" src="https://user-images.githubusercontent.com/9253441/123888922-b0c8fa00-d97e-11eb-97c8-a3dc691fa5f1.png">

<img width="421" alt="Screen Shot 2021-06-30 at 8 40 20 AM" src="https://user-images.githubusercontent.com/9253441/123889008-d229e600-d97e-11eb-9d0e-a67a838294bb.png">

**Comment by chauduyphanvu** [comment]
@sinhpn92, thanks for the update. What happens if you leave the MediaView untouched while also keeping its dimensions (without setting the size to 0)?

**Comment by sinhpn92** [comment]
@chauduyphanvu Oh. I don't want to display the MediaView. It's will be make the ad item in the list too height. I just want to show a small ad view like above.

**Comment by chauduyphanvu** [comment]
@sinhpn92, I understand, but when you keep the MediaView there and request for native banners, the MediaView is not going to be used and inflated with content. It should be an empty view. You don't need to keep removing/adding it.
