### ISSUE TITLE
How to set localExtras for  CustomEventNative   when I request an Ad with MoPubRecyclerAdapter

### ISSUE THREAD

**Issue by WuBingHui** [mopub/mopub-android-mediation#358]
1. **What is the issue?**
    > How to set localExtras for  CustomEventNative   when I request an Ad with MoPubRecyclerAdapter

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Native Static
    * **Platform** (*Android, iOS, Unity*)
        > Android
    * **MoPub SDK Version**
        > implementation ( 'com.mopub:mopub-sdk:+@aar' )
   etc.

**Comment by chauduyphanvu** [comment]
@WuBingHui, this feature is not supported at this time. We'll share an update once it's available. Stay tuned!

Vu Chau
MoPub Team

**Comment by WuBingHui** [comment]
@chauduyphanvu  thanks!!
