### ISSUE TITLE
AdMob Rewarded Video Adapter not actually GDPR-Compliant?

### ISSUE THREAD

**Issue by thomasmso** [mopub/mopub-android-mediation#36]
Hi,

For AdMob rewarded video adapter, you are trying to [obtain the `"npa"` flag from the `localExtras`](https://github.com/mopub/mopub-android-mediation/blob/master/AdMob/com/mopub/mobileads/GooglePlayServicesRewardedVideo.java#L256) to pass into AdMob's SDK. However, I'm not sure if there is a way in MoPub's rewarded video API to pass in a `localExtras`, as it is created anew [here](https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sdk/mopub-sdk-rewardedvideo/src/main/java/com/mopub/mobileads/MoPubRewardedVideoManager.java#L532).

**Comment by chauduyphanvu1** [comment]
Thanks for going above and beyond to inspect that. That definitely slipped through the cracks. I'll PR new adapters.

**Comment by oRRs** [comment]
@chauduyphanvu1 why do you use `boolean canCollectPersonalInfo = MoPub.canCollectPersonalInformation();` on all other adapters?
Can't you just pass `npa=1` if this call results in `false`?
If I understand this correctly, AdMob is the only adapter that developers need to manually pass this info to.

**Comment by chauduyphanvu1** [comment]
@oRRs, yes, we expect publishers to manually set their `npa` field in their implementation. The adapter will manually pass it along to AdMob.

**Comment by chauduyphanvu1** [comment]
This should be resolved in https://github.com/mopub/mopub-android-mediation/pull/37. Thanks!

**Comment by thomasmso** [comment]
@chauduyphanvu1 - So the issue in #37 is now it does not allow updating of the consent flag _after_ initialization which is required by GDPR.

To allow toggling of the `"npa"` flag, it might be best to implement it this way:

```
    public static final class GooglePlayServicesMediationSettings
            implements MediationSettings
    {
        private String mNpa;

        public GooglePlayServicesMediationSettings() {}
        public GooglePlayServicesMediationSettings(final String npa)
        {
            mNpa = npa;
        }

        public void setNpa(final String npa)
        {
            mNpa = npa;
        }

        Bundle getBundle()
        {
            if ( TextUtils.isEmpty( mNpa ) )
            {
                return new Bundle();
            }
            else
            {
                Bundle bundle = new Bundle();
                bundle.putString( "npa", mNpa );

                return bundle;
            }
        }
    }
```

Then publishers can keep a reference to `GooglePlayServicesMediationSettings`, and update it later on in their code using `xxx.setNpa(...)` if the user decides to change his/her consent flag. The adapters can then call `settings.getBundle()` to retrieve a nonnull Bundle to pass into AdMob.

A couple side notes:

1. Would it be cleaner for the adapters *and* publishers to move `GooglePlayServicesMediationSettings` into it's own class instead of making it a nested class of each adapter? I believe @rsatrasala did that for iOS.
2. There's no reason to keep the `npaBundle` as a field on the custom event right? It's only used in the scope of the request ad method (for example [here](https://github.com/mopub/mopub-android-mediation/blob/master/AdMob/com/mopub/mobileads/GooglePlayServicesBanner.java#L33))

**Comment by chauduyphanvu1** [comment]
@thomasmso, thanks! The nested class pattern has been the norm on the Android side (adopted by a few other adapters on the repo). Thanks for the suggestion to add a setter for the `npa` - it's added.

**Comment by thomasmso** [comment]
Sounds good, thank you.
