### ISSUE TITLE
mInteractionListener is null and mInteractionListener.onAdImpression() 、 mInteractionListener.onClicked() not work when MoPubView request banner ad for BaseAd

### ISSUE THREAD

**Issue by WuBingHui** [mopub/mopub-android-mediation#362]
1. **What is the issue?**
    > mInteractionListener is null and mInteractionListener.onAdImpression() 、 mInteractionListener.onClicked() not work when MoPubView request banner ad for BaseAd

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Banner
    * **Platform** (*Android, iOS, Unity*)
        > Android
    * **MoPub SDK Version**
        > implementation('com.mopub:mopub-sdk:+@aar') {
        transitive = true
    }
 etc.

**Comment by p158276** [comment]
Hi @WuBingHui ,
Thanks for reaching out. mInteractionListener is only available after the ad is loaded. You can also refer to the document [here](https://developers.mopub.com/networks/integrate/build-adapters-android/) for building the custom mediation adapter.

Yoyo Lin
MoPub Team

**Comment by WuBingHui** [comment]
Hi @p158276  
After loading the ad and triggering a third-party impression and click, I did use mInteractionListener to notify imp & click, but mInteractionListener was empty.

 `override fun load(context: Context, adData: AdData) {

        setAutomaticImpressionAndClickTracking(false)

        try {

            val extrasMap = adData.extras

            val clientId = extrasMap[TrekMoPubDataKey.CLIENT_ID] ?: ""

            val placeUid = extrasMap[TrekMoPubDataKey.PLACE_UID] ?: ""

            val category = extrasMap[TrekMoPubDataKey.CATEGORY] ?: ""

            Log.e("load", extrasMap.toString())

            if (clientId.isEmpty()) {
                throw NullPointerException(NEED_CLIENT_ID_TAG)
            }

            if (placeUid.isEmpty()) {
                throw NullPointerException(NEED_PLACE_UUID_TAG)
            }

            AotterTrek.initAotterService(
                context,
                clientId
            ) {

                Log.e("AotterTrek", "initAotterService finish callback.")

                Log.e("Automatic", adData.toString())

                val trekService = AotterTrek.trekService(context)

                trekMediaView = TrekMediaView(context, null)

                trekService.setTrekAdStatusListener(
                    TrekMoPubCustomBannerEventForwarder(
                        context,
                        trekService,
                        mLoadListener,
                        mInteractionListener,
                        trekMediaView
                    )
                )

                trekService.setPlaceUid(placeUid).setCategory(category)
                    .applyTrekAd()

            }

        } catch (e: Exception) {

            Log.e("load", e.toString())

            mLoadListener?.onAdLoadFailed(MoPubErrorCode.UNSPECIFIED)

            throw IllegalArgumentException(ERROR_SERVER_PARAMETER)

        }

    }`

TrekMoPubCustomBannerEventForwarder:

`class TrekMoPubCustomBannerEventForwarder(
    private val context: Context,
    private val trekService: TrekAd,
    private val loadListener: AdLifecycleListener.LoadListener?,
    private val interactionListener: AdLifecycleListener.InteractionListener?,
    private var trekMediaView: TrekMediaView
) : TrekAdStatusCallBack {

    override fun onAdLoaded(adData: AdData) {

        trekService.registerSuprAd(context, trekMediaView, adData)

        loadListener?.onAdLoaded()

        Log.e("BannerEventForwarder", "onAdLoaded")

    }

    override fun onAdError(message: String) {
        Log.e("BannerEventForwarder", "onAdError: $message")
        loadListener?.onAdLoadFailed(MoPubErrorCode.AD_NOT_AVAILABLE)
    }

    override fun onAdImpression(view: View) {

        interactionListener?.let {
            it.onAdImpression()
            Log.e("BannerEventForwarder", "onAdImpression")
        }

    }

    override fun onAdClicked(adData: AdData) {

        interactionListener?.let {
            it.onAdClicked()
            Log.e("BannerEventForwarder", "onAdClicked")
        }

    }

}`
