### ISSUE TITLE
java.lang.OutOfMemoryError pthread_create (1040KB stack) failed: Try again java.lang.Thread.nativeCreate

### ISSUE THREAD

**Issue by TaoGEe** [mopub/mopub-android-mediation#363]
A lot of OutOfMemoryError crashes in our app, devices have plenty of RAM, and most are Samsung phones. I guess the reason is that too many ad threads running at the same time, each has more than 100 threads. Is there any way to solve it?
![image](https://user-images.githubusercontent.com/11844963/123912938-3618d280-d9b0-11eb-892f-558437387ff4.png)
![image](https://user-images.githubusercontent.com/11844963/123913028-547ece00-d9b0-11eb-8722-2ca2d8caddd6.png)
![image](https://user-images.githubusercontent.com/11844963/123913155-76785080-d9b0-11eb-9327-a3bc71d5df76.png)

**Comment by dravyan** [comment]
@TaoGEe, thank you for the report. Could you share the complete stack trace to review?. Can you also share the list of network adapters you are integrating?

Thanks,
MoPub Team

**Comment by TaoGEe** [comment]
![image](https://user-images.githubusercontent.com/11844963/124052460-0a015e00-da51-11eb-9999-3b70abf3bf5f.png)
![image](https://user-images.githubusercontent.com/11844963/124052510-20a7b500-da51-11eb-8bcf-84e257643cf2.png)
![image](https://user-images.githubusercontent.com/11844963/124052541-34531b80-da51-11eb-8bbf-6af12b9a6c56.png)
![image](https://user-images.githubusercontent.com/11844963/124052557-3f0db080-da51-11eb-8154-e1b461d7e9e0.png)
![image](https://user-images.githubusercontent.com/11844963/124052591-5351ad80-da51-11eb-9f65-4a1d815b9b6a.png)
There are many more crashing happen everywhere...

**Comment by dravyan** [comment]
@TaoGEe, this could be related to the memory leaks. Could you check for leaks in the app using https://developer.android.com/studio/profile/memory-profiler#profiler-memory-leak-detection?Also if you are able to replicate the issue, please share the project zip.

**Comment by chauduyphanvu** [comment]
Closing due to no actions and no repro cases.
