### ISSUE TITLE
MoPubStaticNativeAdRenderer grabs VerizonAds

### ISSUE THREAD

**Issue by brstgt** [mopub/mopub-android-mediation#364]
1. **What is the issue?**
    If `MoPubStaticNativeAdRenderer` is registered before `VerizonNativeAdRenderer` then `MoPubStaticNativeAdRenderer` will render the Verizon Native ad. This results in no impressions being tracked and the ad is not clickable.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Native Static
    * **Platform** (*Android, iOS, Unity*)
        > Android
    * **MoPub SDK Version**
        > 5.17
    * **Mediation SDK Name & Version**
        > Verizon 1.13
    * **Mediation Adapter Version**
        > Verizon 1.13
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Irrelevant
    * **Device model and OS Version**
        > Irrelevant
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Register `MoPubStaticNativeAdRenderer`
        > 2. Then register `VerizonNativeAdRenderer`
        > 3. Display a verizon native ad
    * **Observed behavior**
        > No impression tracked. Ad is not clickable
    * **Expected behavior** (if known)
        > The opposite ;)
    * **Evidence** (if available)
 

Some code that proves is:

```
class MoPubStaticNativeAdRenderer
...
    public boolean supports(@NonNull BaseNativeAd nativeAd) {
        Preconditions.checkNotNull(nativeAd);
        return nativeAd instanceof StaticNativeAd;
    }
...

class VerizonNativeAdRenderer
...
    public boolean supports(@NonNull BaseNativeAd nativeAd) {
        Preconditions.checkNotNull(nativeAd);
        return nativeAd instanceof VerizonStaticNativeAd;
    }

...
    static class VerizonStaticNativeAd extends StaticNativeAd {
...

```

QED

**Comment by chauduyphanvu** [comment]
@brstgt, you need to register the MoPub renderer last, as recommended in our [documentation](https://developers.mopub.com/publishers/mediation/integrate-android/):

> Finally, register your ad renderers, as shown below. Your `classThatRegistersAdRenderers` varies depending on which native ad integration you are using. **Remember to register your `MoPubStaticNativeAdRenderer` instance last**.

Vu Chau
MoPub Team
