### ISSUE TITLE
Unabled to get custom class name and custom data when using custom sdk adapter

### ISSUE THREAD

**Issue by windinwork** [mopub/mopub-android-mediation#366]
Hello, we want to use a custom sdk mediation, but we found that after configuring a custom SDK mediation on the publisher UI of mopub, we turned on the test mode, add test device and filled in the custom event class and custom event data, but found that the mediation response was not with custom event class and custom event data.

**Comment by chauduyphanvu** [comment]
@windinwork, could you share with us an ad unit ID you are testing with so we can reproduce on our side? Thanks!

Vu Chau
MoPub Team
