### ISSUE TITLE
Facebook  6.5.1.0 always return test ads in release app

### ISSUE THREAD

**Issue by parmarravi** [mopub/mopub-android-mediation#369]
When I update from  
'com.google.ads.mediation:facebook:6.4.0.0' to 'com.google.ads.mediation:facebook:6.5.1.0'
The ads in-app are always test ads. Even in the release app customers are receiving test ads. 

Are there any configuration changes that have happened due to which app is showing test ads only?

**Comment by chauduyphanvu** [comment]
The `com.google.ads.mediation` package belongs to Google AdMob. You need to reach out to Google on this support forum: https://groups.google.com/g/google-admob-ads-sdk.

Vu Chau
MoPub Team
