### ISSUE TITLE
facebook and ironsource Interstitial ad cannot show

### ISSUE THREAD

**Issue by williamycyh** [mopub/mopub-android-mediation#372]
Hello
I recently integrated the sdk of Facebook and ironsource through mopub mediation, but found that Facebook’s native and banner are running normally. Facebook and ironsource's Interstitial did not show . (There are requests in the backend of fb and ironsource, but no impression).   Mopub's native and Interstitial is normal. I donnot konw why. pls help.

the code is below(Android):
gradle:
 implementation 'com.facebook.android:audience-network-sdk:6.5.0'
   implementation 'com.mopub.mediation:facebookaudiencenetwork:6.5.0.0'
   implementation 'com.ironsource.sdk:mediationsdk:7.1.6.1'
   implementation 'com.mopub.mediation:ironsource:7.1.6.1.0'
  implementation('com.mopub:mopub-sdk:+@aar') {
        transitive = true
    }

Application:
var ironSourceSettings: HashMap<String, String> = HashMap()
            ironSourceSettings.put("​applicationKey​", "mykey")

            val sdkConfiguration = SdkConfiguration.Builder("my ad unit")
                    .withMediatedNetworkConfiguration(IronSourceAdapterConfiguration::class.java.name,
                            ironSourceSettings)
                    .build()

            MoPub.initializeSdk(activity, sdkConfiguration, object : SdkInitializationListener {
                override fun onInitializationFinished() {
                    MoPubInited = true
                }

            })

MainActivity:

  var mInterstitial:MoPubInterstitial? = null
// load ad in activity's oncreate
    fun loadMopub(){
       if(!MoPubInited){
          //will retry here
          return;
       }
        mInterstitial = MoPubInterstitial(activity!!, mopubId)
        mInterstitial?.interstitialAdListener = mopubListener
        mInterstitial?.load()
    }

var mopubListener = object: MoPubInterstitial.InterstitialAdListener {
        override fun onInterstitialLoaded(interstitial: MoPubInterstitial?) {
            Log.d(TAG, "loadMopub onInterstitialLoaded")
            isMopubLoaded = true
        }

        override fun onInterstitialShown(interstitial: MoPubInterstitial?) {
        }

        override fun onInterstitialFailed(interstitial: MoPubInterstitial?, errorCode: MoPubErrorCode?) {
            Log.d(TAG, "loadMopub onInterstitialFailed")
            }

        override fun onInterstitialDismissed(interstitial: MoPubInterstitial?) {
         }

        override fun onInterstitialClicked(interstitial: MoPubInterstitial?) {
        }
    }

// show ad when click a button
  fun showAd(): Boolean{
        if(mInterstitial != null){
            mInterstitial?.show()
            mInterstitial = null
            isMopubLoaded = false
           return true
        }
        return false
    }

**Comment by p158276** [comment]
Hi @williamycyh ,
Thanks for reaching out. 

For the code logic you provided, you can use [isReady()](https://developers.mopub.com/publishers/android/interstitial/#step-2-display-an-interstitial-ad) to check when showing the ad. And please make sure you are showing the ad only after onInterstitialLoaded() callback.

Ad is not showing can be no fill or any other setting problem. To dig in further, can you provide the device log with [log enabled](https://developers.mopub.com/publishers/android/test/#enable-logging)? Besides, to get the test ad, please make sure to enable test mode on [ironSource](https://developers.mopub.com/publishers/mediation/networks/ironsource/#set-up-test-mode-on-the-ironsource-side) and [Facebook](https://developers.mopub.com/publishers/mediation/networks/facebook/#set-up-test-mode-on-the-facebook-side). 
Let us know if you have any other questions here.

Thanks,
Yoyo Lin
MoPub Team

**Comment by williamycyh** [comment]
> Hi @williamycyh ,
> Thanks for reaching out.
> 
> For the code logic you provided, you can use [isReady()](https://developers.mopub.com/publishers/android/interstitial/#step-2-display-an-interstitial-ad) to check when showing the ad. And please make sure you are showing the ad only after onInterstitialLoaded() callback.
> 
> Ad is not showing can be no fill or any other setting problem. To dig in further, can you provide the device log with [log enabled](https://developers.mopub.com/publishers/android/test/#enable-logging)? Besides, to get the test ad, please make sure to enable test mode on [ironSource](https://developers.mopub.com/publishers/mediation/networks/ironsource/#set-up-test-mode-on-the-ironsource-side) and [Facebook](https://developers.mopub.com/publishers/mediation/networks/facebook/#set-up-test-mode-on-the-facebook-side).
> Let us know if you have any other questions here.
> 
> Thanks,
> Yoyo Lin
> MoPub Team

Thanks for your feedback. 
I use isready() to have the same effect. How do I open log?
In addition, I have never seen any ads(except mopub) in the test mode. . . .

Let me show you a screenshot of the background data, why there are so many bid requests from mopub, but very few from Facebook. My native ads are just the opposite. it is Strange.

![image](https://user-images.githubusercontent.com/8869509/125908254-2c462c7f-e74c-48ce-99ab-83d58bea25b2.png)

**Comment by p158276** [comment]
Hi @williamycyh ,
You can follow the tutorial here (https://developers.mopub.com/publishers/android/test/#enable-logging) to enable the SDK log when initializing MoPub SDK. Have you enabled the test mode in the network dashboard? Besides, please provide the affected ad unit and device log so we can help to take a look. 

Yoyo Lin

**Comment by williamycyh** [comment]
hi
I found a log exception about IronSource, but I don't know how to modify it. I configured the same appkey on dashbord in the network tab. My affected ad unit : 59b9ce7280184a0c827f9edea17bfdc8 (mopub)

22021-07-16 17:25:47.889 7394-11389/apppackage I/MoPub: [com.mopub.common.BaseAdapterConfiguration][setCachedInitializationParameters] SDK Log - Updating init settings for base ad com.mopub.mobileads.IronSourceAdapterConfiguration with params {"​applicationKey​":"1002d3e29"}
2021-07-16 17:25:47.889 7394-11389/apppackage I/MoPub: [com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log - Initializing com.mopub.mobileads.IronSourceAdapterConfiguration version 7.1.6.1.0 with network sdk version 7.1.6.1 and with params {​applicationKey​=1002d3e29}
2021-07-16 17:25:47.890 7394-11389/apppackage I/MoPub: [com.mopub.mobileads.IronSourceAdapterConfiguration][initializeNetwork] Adapter IronSource's initialization not started. Ensure ironSource's applicationKey is populated on the MoPub dashboard. Log - null
2021-07-16 17:25:47.890 7394-11389/apppackage I/MoPub: [com.mopub.mobileads.IronSourceAdapterConfiguration][initializeNetwork] Adapter IronSourceAdapterConfiguration Log - IronSource's initialization via IronSourceAdapterConfiguration failed.
2021-07-16 17:25:47.890 7394-11389/apppackage I/MoPub: [com.mopub.common.AdapterConfigurationManager][onNetworkInitializationFinished] SDK Log - class com.mopub.mobileads.IronSourceAdapterConfiguration initialized with error code Native Network or ad adapter was configured incorrectly.

**Comment by hoanghiephui** [comment]
> > Hi @williamycyh ,
> > Thanks for reaching out.
> > For the code logic you provided, you can use [isReady()](https://developers.mopub.com/publishers/android/interstitial/#step-2-display-an-interstitial-ad) to check when showing the ad. And please make sure you are showing the ad only after onInterstitialLoaded() callback.
> > Ad is not showing can be no fill or any other setting problem. To dig in further, can you provide the device log with [log enabled](https://developers.mopub.com/publishers/android/test/#enable-logging)? Besides, to get the test ad, please make sure to enable test mode on [ironSource](https://developers.mopub.com/publishers/mediation/networks/ironsource/#set-up-test-mode-on-the-ironsource-side) and [Facebook](https://developers.mopub.com/publishers/mediation/networks/facebook/#set-up-test-mode-on-the-facebook-side).
> > Let us know if you have any other questions here.
> > Thanks,
> > Yoyo Lin
> > MoPub Team
> 
> Thanks for your feedback.
> I use isready() to have the same effect. How do I open log?
> In addition, I have never seen any ads(except mopub) in the test mode. . . .
> 
> Let me show you a screenshot of the background data, why there are so many bid requests from mopub, but very few from Facebook. My native ads are just the opposite. it is Strange.
> 
> ![image](https://user-images.githubusercontent.com/8869509/125908254-2c462c7f-e74c-48ce-99ab-83d58bea25b2.png)

Hi @p158276 I have the same problem with iron

**Comment by chauduyphanvu** [comment]
@hoanghiephui, could you add some relevant details so our team can help investigate? I'm not sure what the exact issue you are facing is.

Vu Chau
MoPub Team

**Comment by williamycyh** [comment]
it is ok now, thanks.

**Comment by chauduyphanvu** [comment]
Thanks for confirmation. I will close this thread now, but feel free to let us know if the issue persists.
