### ISSUE TITLE
AdMob 20.2.0.2 adapter (R. class)

### ISSUE THREAD

**Issue by Luklek** [mopub/mopub-android-mediation#380]
I have always been using the adapter java files directly in my project (not with Gradle nor generating .aar file)
With the newest AdMob adapters, it requires to use R.color.gradient_strip_start_color, R.color.gradient_strip_end_color from the generated R. class (but I can't import com.mopub.mobileads.admob.R;)

Sorry if it's something very easy/obvious, but I really have no idea what I should replace those values with?

Thanks

**Comment by chauduyphanvu** [comment]
@Luklek, no need to say sorry! We have addressed the issue you are running into in this release: https://github.com/mopub/mopub-android-mediation/commit/d6a0e3bf93606f37c27b53f6059ec2f300c932fd. Please update to the new adapter versions and let us know if that works for you!

Vu Chau
MoPub Team

**Comment by Luklek** [comment]
Hello,
I think I wasn't clear in my post.
I updated both MoPub SDK to 5.18 and used the AdMob adapter release: d6a0e3b https://github.com/mopub/mopub-android-mediation/commit/d6a0e3bf93606f37c27b53f6059ec2f300c932fd

The problem is that I can't import com.mopub.mobileads.admob.R; (as I don't use the gradle or .aar files to add the adapter; I simply copy the GooglePlayServicesMediaLayout.java in the proper folders in my project)
So in this case, I was wondering what are the values of R.color.gradient_strip_start_color, R.color.gradient_strip_end_color so I could replace them manually.

**Comment by chauduyphanvu** [comment]
Ah I see. You can manually replace those with the [following values](https://github.com/mopub/mopub-android-sdk/blob/ad8f5f9204da85ff74219e7dce059fb89648d0b4/mopub-sdk/mopub-sdk-base/res/values/drawable_colors.xml#L6-L7) from the MoPub Android SDK:

```xml
    <color name="gradient_strip_start_color">#66000000</color>
    <color name="gradient_strip_end_color">#00000000</color>
```

**Comment by Luklek** [comment]
Thanks so much!! I should have thought to look for those new resources in the MoPob SDK itself, I will do so next time :)
At the moment I had replaced them with Color.argb(102, 0, 0, 0), Color.argb(0, 0, 0, 0) as in the previous MoPub version. Which is anyway the same value as the new version.
