### ISSUE TITLE
facebook audience network adapter 6.5.1.0 return just test ads

### ISSUE THREAD

**Issue by AKBIROCK3** [mopub/mopub-android-mediation#382]
1. **What is the issue?**
    > Provide a one-line summary of the issue here.
facebook audience network adapter 6.5.1.0 return test ads

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (Banner, Interstitial, Rewarded Video)
        > Provide the data here
    * **Platform** (*Android*)
        > Provide the data here
    * **MoPub SDK Version**
5.18.0

**Comment by chauduyphanvu** [comment]
@AKBIROCK3, are you able to provide additional information (e.g. console logs, and screenshots) that confirms the behavior you are seeing? 

We've checked the distributed adapters (both the source code and the AAR) but did not find evidence of test mode being included. It might be possible that you might have accidentally enabled test mode from the server or from somewhere else in your app.

Vu Chau
MoPub Team
