### ISSUE TITLE
Failed resolution of: Lcom/mopub/common/privacy/ConsentStatusChangeListener;

### ISSUE THREAD

**Issue by AndrewBarvinok** [mopub/mopub-android-mediation#391]
Hello. I'm trying to run test ads on Android device and getting this error when starting scene with ads.

2021.08.29 21:33:24.321 9446 9483 Error Unity AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mopub/common/privacy/ConsentStatusChangeListener;
2021.08.29 21:33:24.321 9446 9483 Error Unity java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mopub/common/privacy/ConsentStatusChangeListener;
2021.08.29 21:33:24.321 9446 9483 Error Unity 	at java.lang.reflect.Executable.getMethodReturnTypeInternal(Native Method)
2021.08.29 21:33:24.321 9446 9483 Error Unity 	at java.lang.reflect.Method.getReturnType(Method.java:148)
2021.08.29 21:33:24.321 9446 9483 Error Unity 	at java.lang.Class.getDeclaredMethods(Class.java:1880)
2021.08.29 21:33:24.321 9446 9483 Error Unity 	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:26)
2021.08.29 21:33:24.321 9446 9483 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2021.08.29 21:33:24.321 9446 9483 Error Unity 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
2021.08.29 21:33:24.321 9446 9483 Error Unity 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:83)
2021.08.29 21:33:24.321 9446 9483 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:108)
2021.08.29 21:33:24.321 9446 9483 Error Unity 	at android.os.Looper.loop(Looper.java:216)
2021.08.29 21:33:24.321 9446 9483 Error Unity 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
2021.08.29 21:33:24.321 9446 9483 Error Unity Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mopub.common.privacy.ConsentStatusChangeListener" on path: DexPathList[[zip file "/data/app/

Please help.

One more thing. When I run the ads in Unity Editor I call RequestRewardedVideo("test ads unit id") method and receive OnRewardedVideoLoadedEvent event and call the ShowRewardedVideo("test ads unit id") method. Then I receive OnRewardedVideoShownEvent event and OnRewardedVideoClosedEvent event, but no ads is showing. Is it normal for test?

Thank you.

My code snipet with test AdUnitId:

MoPub.LoadRewardedVideoPluginsForAdUnits(new string[] { "920b6145fb1546cf8b5cf2ac34638bb7" });
MoPubManager.OnRewardedVideoLoadedEvent += OnRewardedLoaded;
MoPubManager.OnRewardedVideoFailedEvent += OnRewardedFailed;
MoPubManager.OnRewardedVideoClosedEvent += OnMoPubClosedEvent;
MoPubManager.OnRewardedVideoReceivedRewardEvent += OnMoPubReceivedRewardEvent;
MoPubManager.OnRewardedVideoShownEvent += OnRewardedVideoShownEvent;
MoPub.RequestRewardedVideo("920b6145fb1546cf8b5cf2ac34638bb7");

**Comment by khchen428** [comment]
Hi @AndrewBarvinok -
Thanks for filing the issues!  Both of them are not expected in testing.  Can you please confirm if you are initializing the Unity SDK using the [SDK Manager](https://developers.mopub.com/publishers/unity/integrate/#step-1-integrate-the-plugin-and-mediation-adapters) or importing the plugin manually?    If you are using the Unity Manager, can you please file these are two separate issues in the https://github.com/mopub/mopub-unity-sdk repository?
Also, are you using the [Sample App](https://github.com/mopub/mopub-unity-sdk#new-sample-app) or your own app to test? 
Best,
