### ISSUE TITLE
Test ad not show in Unity game mode.

### ISSUE THREAD

**Issue by AndrewBarvinok** [mopub/mopub-android-mediation#392]
Hello. 
When I run the ads in Unity Editor (in game mode) I call RequestRewardedVideo("test ads unit id") method and receive OnRewardedVideoLoadedEvent event and then I call the ShowRewardedVideo("test ads unit id") method. Then I receive OnRewardedVideoShownEvent event and OnRewardedVideoClosedEvent event, but no ads is showing.

Unity 2021.1.18

**Comment by p158276** [comment]
Hi @AndrewBarvinok ,
Thanks for reaching out. Have you exported your project to either iOS or Android? Besides, could you provide the ad unit you are currently using. You can always follow the best practice from our [sample app](https://developers.mopub.com/publishers/tools/sample-apps/). Let us know if you need any other help.

Yoyo Lin
MoPub Team

**Comment by AndrewBarvinok** [comment]
Hello!

I am creating app fpr Android. And using this test unit ID fo rewarded ads: 920b6145fb1546cf8b5cf2ac34638bb7

**Comment by p158276** [comment]
Hi @AndrewBarvinok ,
The scenario you observed is expected. MoPub Unity SDK is just like a wrapper on top of native Android and iOS SDK. So it would only work when export with the Mobile project.

**Comment by AndrewBarvinok** [comment]
Ok. Thank you very much!
