### ISSUE TITLE
About AdColonyAdapterConfiguration.getAdColonyAppOptionsAndSetConsent

### ISSUE THREAD

**Issue by 1008k** [mopub/mopub-android-mediation#396]
Hello.
I am working on pre-initializing AdColony for use with AdvancedBidding.

In the following page, the following sample code is mentioned.
[https://developers.mopub.com/ja/publishers/mediation/networks/adcolony/#advanced-bidding-requirements](https://developers.mopub.com/ja/publishers/mediation/networks/adcolony/#advanced-bidding-requirements)

`AdColonyAppOptions adColonyAppOptions = AdColonyAdapterConfiguration . getAdColonyAppOptionsAndSetConsent("");`

This method is protected and cannot be referenced by the app you are trying to embed.
Is it possible to make this method public?

Best Regard.

**Comment by p158276** [comment]
Hi @1008k ,
Thanks for reaching out. Publishers can initialize networks outside of MoPub and AdColony has API to do that as stated in our documentation
https://developers.mopub.com/publishers/advanced-features/advanced-bidding/#initialize-your-network-sdks. No need to call getAdColonyAppOptionsAndSetConsent.

The document you provided there is a bit out of date. We'll modify accordingly. 

Yoyo Lin
MoPub Team

**Comment by 1008k** [comment]
@p158276 
Thank you for your reply!
I see now that the option is not needed.
I'll try to implement it without the argument
