### ISSUE TITLE
No respond when click a Native ads 

### ISSUE THREAD

**Issue by phoche** [mopub/mopub-android-mediation#409]
1. **What is the issue?**
    > couldn't click native ad on some high Android os

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ ] I searched https://developers.mopub.com/ and found no answer.
    - [ ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Native Static
    * **Platform** (*Android, iOS, Unity*)
        > Android
    * **MoPub SDK Version**
        > 5.17.0
    * **Mediation SDK Name & Version**
        > admob:20.2.0 and facebookaudiencenetwork:6.5.1
    * **Mediation Adapter Version**
        > admob:20.2.0.1 and facebookaudiencenetwork:6.5.1.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > 00e487d1c5b84b259268fdfc8415b7f8
    * **Device model and OS Version**
        > part of Android11
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. click action in native ad
    * **Observed behavior**
        > no respond
    * **Expected behavior** (if known)
        > turn to some activity
    * **Evidence** (if available)
        >

**Comment by phoche** [comment]
@chauduyphanvu Yes, it is still happen, here is my app link: https://play.google.com/store/apps/details?id=com.onesports.score&gl=GB.

**Comment by MKelman** [comment]
I am also still having this issue. I am trying to create a apk to submit to mopub and facebook to help debug. @phoche still an issue for your team as well?

**Comment by phoche** [comment]
I find a resolution, that is "one request, one Item", you can call RecyclerView.ViewHolder.setIsRecyclable(false), let the item which is display nativead don't recycle

**Comment by MKelman** [comment]
@phoche can you let me know a bit more about the "one request, one item"? For example we have a caching mechanism that requests up to n items and hold them in cache until a user views them for quick loading

**Comment by phoche** [comment]
@MKelman For example, when you are caching a request, load it in to a fixed item and mustn't let the request load in to any other item. the function of method "RecyclerView.ViewHolder.setIsRecyclable" is make sure the cached request which you have loaded in to a fixed item won't load in to the other item. For some mediation sdks like admob, facebook..., the callback "onAdClicked" will not be executed, It is why this issue occurs

**Comment by MKelman** [comment]
I appreciate the information @phoche. I will try to debug and see what i can find!

**Comment by MKelman** [comment]
I finally figured it out.. context. when creating new MoPubNative(....), the context in the first parameter must be the fragments/activity context. I was using the application context
