### ISSUE TITLE
facebookaudiencenetwork 6.8.0

### ISSUE THREAD

**Issue by Juski** [mopub/mopub-android-mediation#419]
Hello mopub，

I want to know when the facebookaudiencenetwork version 6.8.0 can be supported
 
thanks

**Comment by chauduyphanvu** [comment]
@Juski, please reference our Mediation Integration Tool at https://developers.mopub.com/publishers/mediation/integrate/ for usage instructions. Thanks!

Vu Chau
MoPub Team
