### ISSUE TITLE
Incorrect usage of WeakHashMap causes memory leaks

### ISSUE THREAD

**Issue by linean** [mopub/mopub-android-mediation#420]
1. **What is the issue?**
Incorrect usage of WeakHashMap in MoPub ad renderers prevents garbage collection and causes memory leaks.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [X] I searched https://developers.mopub.com/ and found no answer.
    - [X] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [X] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Native static
    * **Platform** (*Android, iOS, Unity*)
        > Android
    * **Mediation Adapter Version**
        > com.mopub.mediation:verizon:1.14.0.1
        > com.mopub.mediation:admob:20.3.0.0
        > com.mopub.mediation:pangle:3.9.0.3.0
        > com.mopub.mediation:facebookaudiencenetwork:6.7.0.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > 83942960038e4fc9a962e8f38d7b471d

**Steps to reproduce the issue** (include integration steps if not standard)
- Instantiate multiple ad views with `adapterHelper.getAdView(null, null, nativeAd)`
- Run garbage collection
- Check memory usage

**Observed behavior**
WeakHashMaps entries in ad renderers are never discarded and collected by the garbage collector.

Affected renderers:
- PangleAdRenderer
- VerizonNativeAdRenderer
- MoPubStaticNativeAdRenderer
- GooglePlayServicesAdRenderer
- FacebookAdRenderer

From [WeakHashMap docs](https://docs.oracle.com/javase/8/docs/api/java/util/WeakHashMap.html)
> The value objects in a WeakHashMap are held by ordinary strong references. Thus care should be taken to ensure that value objects do not strongly refer to their own keys, either directly or indirectly, since that will prevent the keys from being discarded.

All mentioned renderers have direct or indirect relation between value objects and their keys. For ex. `StaticNativeViewHolder.mainView` is the same as WeahHashMap key.

 **Expected behavior** (if known)
WeakHashMaps entries in ad renderers can be collected by the garbage collector.

**Evidence** (if available)
![image](https://user-images.githubusercontent.com/17886739/142627356-2d34d0b0-40a6-4baa-a3f8-a6f164b8f855.png)

**Comment by rsatrasala** [comment]
Thank you @linean for the report. We noted this internally and we will address if we have further releases for the mentioned adapters
