### ISSUE TITLE
Facebook Mediation requires activity/fragment context

### ISSUE THREAD

**Issue by MKelman** [mopub/mopub-android-mediation#421]
1. **What is the issue?**
    > If facebook mediation native ad gets application context, native ad wont click. The nativeAd needs to be given the fragment/activity context as i noted in ([see it doesn't click](https://github.com/mopub/mopub-android-mediation/issues/409#issuecomment-974215278)). 

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ x] I searched https://developers.mopub.com/ and found no answer.
    - [ x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Native static
    * **Platform** (*Android, iOS, Unity*)
        > Android
    * **MoPub SDK Version**
        > 5.17.0
    * **Mediation SDK Name & Version**
        > facebookaudiencenetwork:6.5.1
    * **Mediation Adapter Version**
        > facebookaudiencenetwork:6.5.1.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > fafcd1fcaf9f492088e0b9e414dbbb8d
    * **Device model and OS Version**
        > any android os
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. view facebook native ad
        > 2. click on ad
    * **Observed behavior**
        > doesn't click
    * **Expected behavior** (if known)
        > it clicks

Below is an hprof file. you can see the CoverActivity is leaking
[memory-20211119T160427.hprof.zip](https://github.com/mopub/mopub-android-mediation/files/7572916/memory-20211119T160427.hprof.zip)

**Comment by MKelman** [comment]
After a massive amount of research, i finally figured out what caused the issue. Setting the activity with the code below that contains the ad causes the ad now to click:

 window.addFlags(WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED)

**Comment by MKelman** [comment]
I unfortunately need that boolean on for our implementation and causes other issues that do not work for us. How can we get this fixed asap? This is a test apk with a service running that allows you to see what I found:
https://drive.google.com/file/d/1UCCs1yQveMuGn1I9k2fIYwoBIy5RxYw1/view?usp=sharing

**Comment by chauduyphanvu** [comment]
@MKelman, I'm curious if this is a larger issue. Could you put a breakpoint [here ](https://github.com/mopub/mopub-android-mediation/blob/master/FacebookAudienceNetwork/src/main/java/com/mopub/nativeads/FacebookNative.java#L319-L323)to see where it breaks?

```java
@Override
public void onAdClicked(final Ad ad) {
    notifyAdClicked();
    MoPubLog.log(getAdNetworkId(), CLICKED, ADAPTER_NAME);
}
```

`onAdClicked()` is the API from Facebook, and `notifyAdClicked()` is MoPub's. If you can't get inside `onAdClicked()` at all then it means Facebook is not notifying MoPub to track the click.

Vu Chau
MoPub Team

**Comment by MKelman** [comment]
@chauduyphanvu I just tried and it doesn't get triggered. I have opened a case with facebook already too but if theres anything you can help pushing facebook or anything else you may see?

**Comment by chauduyphanvu** [comment]
Thanks for the confirmation. I'll see what we can do!

**Comment by kylegrymonprez** [comment]
Closing given that this is a Facebook implementation issue required by their SDK.
