### ISSUE TITLE
mopub(maybe facebook) causes memory leak from activity

### ISSUE THREAD

**Issue by MKelman** [mopub/mopub-android-mediation#422]
1. **What is the issue?**
    > As I am trying to my current issue https://github.com/mopub/mopub-android-mediation/issues/421, I am seeing a huge memory leak that isn't allowing me to ship my fix due to a memory leak. I have made a test APK that after clicking a button launches the activity. Clicking back and then clicking the button over and over again begins to show the huge leak.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > native
    * **Platform** (*Android, iOS, Unity*)
        > android
    * **MoPub SDK Version**
        > 5.18.0
    * **Mediation SDK Name & Version**
        > implementation 'com.facebook.android:facebook-android-sdk:9.1.1'
           implementation 'com.facebook.android:audience-network-sdk:6.8.0'
           implementation 'com.mopub.mediation:facebookaudiencenetwork:6.5.1.0'
    * **Mediation Adapter Version**
        > facebook
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > fafcd1fcaf9f492088e0b9e414dbbb8d
    * **Device model and OS Version**
        > any android model and os
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. click button
        > 2. click back
    * **Observed behavior**
        > after doing steps many times, you'll see leak canary start screaming
    * **Expected behavior** (if known)
        > no memory leak
    * **Evidence** (if available)
        
![image](https://user-images.githubusercontent.com/10063610/142938896-4888a5a7-f2d9-4895-9f79-f3f67053f4be.png)

[memory-20211122T163918.hprof.zip](https://github.com/mopub/mopub-android-mediation/files/7584546/memory-20211122T163918.hprof.zip)

he ZIP of the test repo i made wasn't allowing me to attach so its in this drive link: https://drive.google.com/file/d/1I5G6_sM9zUP-HuZPfkXgJVdHOgp6A7lT/view?usp=sharing

Leak canary items:

![image](https://user-images.githubusercontent.com/10063610/142942555-67bb7482-bc2e-4b7e-956d-8a6ea4f2c336.png)

![image](https://user-images.githubusercontent.com/10063610/142942725-0a85e3d7-cc9a-4ca9-8824-4a8c73b66f1b.png)

**Comment by MKelman** [comment]
@rsatrasala its not facebook, its happening for mopub too 
![image](https://user-images.githubusercontent.com/10063610/144123539-50100c38-de99-4971-9fda-e91a3d4012b1.png)

**Comment by MKelman** [comment]
@rsatrasala after some more debugging, we had to use reflection to fix the memory leak using the code below. Since we are cacheing, as seen in the zip project, our cache is causing a memory leak due to holding of the native network listener. trying to call moPubNative?.destroy() in the ondestroy also fixes the leak however when we unlock the device to view the store cached item, it is blank due to the destroy destroying the item too. 

        val field = MoPubNative::class.java.getDeclaredField("mMoPubNativeNetworkListener")
        field.isAccessible = true
        field.set(moPubNative!!, EMPTY_NETWORK_LISTENER)

**Comment by p158276** [comment]
Hi @MKelman ,
Thanks for putting all this together. I am able to reproduce the same leak on our end. Let me bring it back to our team and will update here when there's any update.

Yoyo Lin
MoPub Team

**Comment by MKelman** [comment]
@p158276 ended up fixing it on my end by not using reflection actually but moving the MoPubNativeNetworkListener creation into our singleton in our cacheing mechanism so its in the same scope when creating a MoPubNative. However, this probably isn't ideal and interested in what the team finds out.

**Comment by kylegrymonprez** [comment]
@MKelman thanks for the update. Given this was a leak in your custom implementation of caching, we're going to close this for now.

Given the pending MoPub shutdown, we will almost certainly not be addressing any other callback issues.
