### ISSUE TITLE
pangle crash: MediationAdapterUtil.java line 458

### ISSUE THREAD

**Issue by MKelman** [mopub/mopub-android-mediation#427]
1. **What is the issue?**
    > seeing a pangle crash during mediation in the MediationAdapterUtil.java line 458

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > native
    * **Platform** (*Android, iOS, Unity*)
        > android
    * **MoPub SDK Version**
        > com.pangle.global:ads-sdk: 15.18.0
    * **Mediation SDK Name & Version**
        > com.pangle.global:ads-sdk: 1.0.1
    * **Mediation Adapter Version**
        > com.mopub.mediation:pangle:: 4.1.1.2.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Provide the data here
    * **Device model and OS Version**
        > all android  os versions
    * **Observed behavior**
        > crash on firebase
    * **Expected behavior** (if known)
        > no crash
    * **Evidence** (if available)
        
![image](https://user-images.githubusercontent.com/10063610/146856495-893a8ba7-a074-4fc5-b9d6-155954cbe002.png)

**Comment by p158276** [comment]
Hi @MKelman ,
Thanks for reaching out. The error seems to happen in Pangle SDK [classes](https://github.com/mopub/mopub-android-mediation/blob/d66ed19e6dce87f07925b699fb5192854a4f7519/Pangle/src/main/java/com/mopub/nativeads/PangleAdRenderer.java#L10). Can you provide the reproducible steps with the Pangle team? 

Yoyo Lin
MoPub Team
