### ISSUE TITLE
Got Error "Rewarded Video was initialized in mediation mode. Use isRewardedVideoAvailable instead"

### ISSUE THREAD

**Issue by maplelol** [mopub/mopub-android-mediation#47]
I'm using the Mediation with ironSource, and
I get the error "Rewarded Video was initialized in mediation mode. Use isRewardedVideoAvailable instead" when I try to show the rewarded video. And I have tried several different SDK version, still does not work.

**Comment by rsatrasala** [comment]
Hello @maplelol, please reach out to support@mopub.com so our team can review your integration and help you further. Thank you.
