### ISSUE TITLE
FAN native banner adverts not clickable on Android

### ISSUE THREAD

**Issue by benMap3** [mopub/mopub-android-mediation#52]
I have been trying to upgrade to MoPub 4.2.0 and FAN 4.99.1 to request native Facebook ads via MoPub. For standard Native ads that show the main image this appears to work fine. For Native Banner ads the 'onAdLoaded' is called and the ad layout is rendered and shown to the user, but the recyclerview item view and call-to-action button registers no call to 'onAdClicked'. I have checked the setup via monetization manager and have a Native Banner setup for this request and the new Adapters appear to hit the onAdLoaded but none of the facebook ads will allow a click to be registered. The one thing that does allow a click through is the AdChoices logo. Any help would be greatly appreciated. 

`FacebookAdRenderer facebookAdRenderer = new FacebookAdRenderer(new FacebookAdRenderer.FacebookViewBinder.Builder(R.layout.native_ad_facebook_layout)
                    .titleId(R.id.native_ad_facebook_title)
                    .textId(R.id.native_ad_facebook_text)
                    // Binding to new layouts from Facebook 4.99.0+
                    .adIconViewId(R.id.native_ad_facebook_icon)
                    .adChoicesRelativeLayoutId(R.id.native_ad_facebook_privacy_information_icon)
                    .callToActionId(R.id.native_ad_facebook_cta)
                    .build());

MoPubRecyclerAdapter nativeMoPubAdapter = new MoPubRecyclerAdapter(getActivity(), adapter);
nativeMoPubAdapter.registerAdRenderer(facebookAdRenderer);
recyclerView.setAdapter(nativeMoPubAdapter);
nativeMoPubAdapter.loadAds("AD_UNIT_ID");`

[nearby_layout.txt](https://github.com/mopub/mopub-android-mediation/files/2209017/nearby_layout.txt)

**Comment by chauduyphanvu1** [comment]
@benMap3 - if you are mediating Facebook's new [native banner ad](https://developers.facebook.com/docs/audience-network/android-native-banner) format, we/adapters currently do not support that format yet. Native banner uses different APIs to return assets, so they are not being added (via the regular native ad adapter) to the [list of clickable views](https://github.com/mopub/mopub-android-mediation/blob/master/FacebookAudienceNetwork/com/mopub/nativeads/FacebookNative.java#L92), causing them to not click. 

Feel free to check back for official support!

**Comment by chauduyphanvu1** [comment]
@benMap3 - thanks for your interest. We will be assessing demand for this mediation use case, but we currently don't have a support plan or estimate timeline for supporting Facebook's native banner ad yet. Feel free to "watch" this repo to stay updated!
