### ISSUE TITLE
FlurryNativeAdRenderer NullPointerException

### ISSUE THREAD

**Issue by HebrewToYou** [mopub/mopub-android-mediation#7]
The latest adapters for Flurry Native generates an NPE due to the code added from lines 75-78. Video ads work without issue, but non-video ads fail to load the image. This is likely due to our particular implementation, but the Flurry renderer shouldn't be setting visibility flags on our views.

**Comment by chauduyphanvu1** [comment]
Hello, thanks for reporting the crash! Would you mind sharing the stack trace?

**Comment by linked67** [comment]
Line 79 of FlurryNativeAdRenderer.java don't check if the main image is null or not, that why we get NPE. I was forced to add a fake main image view (i don't use it) to bypass this problem.

**Comment by chauduyphanvu1** [comment]
Thanks! This has been patched in https://github.com/mopub/mopub-android-mediation/commit/3ae0ef3f94f81c1973a1eec3fc61a3b650e3f473.
