### ISSUE TITLE
AdMob BannerAdapter no Impressions

### ISSUE THREAD

**Issue by xgear-public** [mopub/mopub-android-mediation#76]
Hello! I use [GooglePlayServicesBanner](https://github.com/mopub/mopub-android-mediation/blob/master/AdMob/com/mopub/mobileads/GooglePlayServicesBanner.java) as an adapter for AdMob banners. But, after last update, adapter doesn't track impression back to MoPub. This code is never called:
`

        public void onAdImpression() {
            if (mBannerListener != null) {
                mBannerListener.onBannerImpression();
            }
        }
`
According to AdMob docs this callback is called [**only for native ads**](https://developers.google.com/android/reference/com/google/android/gms/ads/AdListener.html#onAdImpression()). Could you please suggest the best way to handle this situation and track impressions back to MoPub?

**Comment by chauduyphanvu1** [comment]
Fixed in https://github.com/mopub/mopub-android-mediation/commit/5f58f0718ed627f51377e5d03eba8e712c23bb8a.
