### ISSUE TITLE
wrong render in mopub recyclerview with new native integration

### ISSUE THREAD

**Issue by Kyba1985** [mopub/mopub-android-mediation#99]
Mopub sdk -> 5.4.0
admob sdk ->  "com.google.android.gms:play-services-ads:17.0.0"

issue:
wrong render on native adv with last integration admob.

Example:
![screenshot_2018-11-06-18-09-30](https://user-images.githubusercontent.com/13661071/48081227-d44c3e80-e1ef-11e8-9a65-e9f06e5006c5.png)

This not happens always. 

####################
Code of layout and renderer.

Layout:
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/native_outer_view"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@android:color/white">

    <ImageView
        android:id="@+id/native_icon_image"
        android:layout_width="64dp"
        android:layout_height="64dp"
        android:layout_alignParentLeft="true"
        android:layout_alignParentTop="true"
        android:layout_marginLeft="10dp"
        android:layout_marginTop="10dp"
        android:background="@null" />

    <TextView
        android:id="@+id/native_title"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentLeft="true"
        android:layout_alignParentTop="true"
        android:layout_marginLeft="84dp"
        android:layout_marginTop="32dp"
        android:textColor="@android:color/darker_gray"
        android:textStyle="bold" />

    <TextView
        android:id="@+id/native_text"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@+id/native_icon_image"
        android:layout_alignParentLeft="true"
        android:layout_marginLeft="10dp"
        android:layout_marginTop="10dp"
        android:textColor="@android:color/darker_gray" />

    <com.mopub.nativeads.MediaLayout
        android:id="@+id/native_media_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/native_text"
        android:layout_centerHorizontal="true"
        android:layout_marginLeft="10dp"
        android:layout_marginTop="10dp"
        android:layout_marginRight="10dp"
        android:layout_marginBottom="10dp" />

    <Button
        android:id="@+id/native_cta"
        android:layout_width="wrap_content"
        android:layout_height="40dp"
        android:layout_below="@id/native_media_layout"
        android:layout_alignParentRight="true"
        android:layout_marginTop="10dp"
        android:layout_marginRight="10dp"
        android:backgroundTint="@color/archive_primary_dark"
        android:clickable="true"
        android:paddingBottom="16dp"
        android:text="@string/learn_more"
        android:textColor="@android:color/white"
        android:textSize="12sp"
        android:textStyle="bold" />

    <ImageView
        android:id="@+id/native_privacy_information_icon_image"
        android:layout_width="40dp"
        android:layout_height="40dp"
        android:layout_alignParentTop="true"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:padding="10dp" />

</RelativeLayout>

Code in the recyclerview:

```
        final GooglePlayServicesAdRenderer googlePlayServicesAdRenderer = new GooglePlayServicesAdRenderer(new MediaViewBinder.Builder(R.layout.video_ad_list_item).mediaLayoutId(R.id.native_media_layout) // bind to your `com.mopub.nativeads.MediaLayout` element
                .iconImageId(R.id.native_icon_image).titleId(R.id.native_title).textId(R.id.native_text).callToActionId(R.id.native_cta).privacyInformationIconImageId(R.id.native_privacy_information_icon_image).build());
```

Any ideas about this issue?

**Comment by chauduyphanvu1** [comment]
Could you try with the [17.0.0.1](https://github.com/mopub/mopub-android-mediation/blob/master/AdMob/CHANGELOG.md) version of the adapters (implementation 'com.mopub.mediation:admob:17.0.0.1')? We fixed an issue very similar to this that we think will also fix this one.

**Comment by Kyba1985** [comment]
I have tried 17.0.0.1 but didn't work.
Seems that in this type of adv is present a list of images to render and the medialayout can't render properly.

In this morning during tests other types of native adv was rendered properly with video inside (Amazon and tik tok adv) but with this the issue stay yet. 

Am i the only developer with this issue? Can you provide some tips?
With this issue i can't go in production with the last integration version. 

thanks.

**Comment by chauduyphanvu1** [comment]
Closing as irreproducible.
